### ISSUE TITLE
pgadmin4 fails to start backup job (RM #2323)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1104]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2323***
*Originally created by **Jacek Jablonski** at 2017-04-06 16:04:04 UTC.*

I am trying to do a backup, first thing to notice is that filename path choosing dialog is blank (I cannot see any directories).
Then when trying to create backup job - nothing happens.
In log I can see error below:
[Thu Apr 06 17:58:25.553988 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025] mod_wsgi (pid=17225): Exception occurred processing WSGI script '/srv/pgadmin/lib64/python3.4/site-packages/pgadmin4/pgAdmin4.wsgi'.
[Thu Apr 06 17:58:25.554143 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025] Traceback (most recent call last):
[Thu Apr 06 17:58:25.555374 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 2000, in __call__
[Thu Apr 06 17:58:25.555399 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     return self.wsgi_app(environ, start_response)
[Thu Apr 06 17:58:25.555471 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
[Thu Apr 06 17:58:25.555480 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     response = self.make_response(self.handle_exception(e))
[Thu Apr 06 17:58:25.555528 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
[Thu Apr 06 17:58:25.555535 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     reraise(exc_type, exc_value, tb)
[Thu Apr 06 17:58:25.555833 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
[Thu Apr 06 17:58:25.555854 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     raise value
[Thu Apr 06 17:58:25.555916 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
[Thu Apr 06 17:58:25.555925 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     response = self.full_dispatch_request()
[Thu Apr 06 17:58:25.555967 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Thu Apr 06 17:58:25.555974 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     rv = self.handle_user_exception(e)
[Thu Apr 06 17:58:25.556012 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
[Thu Apr 06 17:58:25.556034 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     reraise(exc_type, exc_value, tb)
[Thu Apr 06 17:58:25.556079 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
[Thu Apr 06 17:58:25.556087 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     raise value
[Thu Apr 06 17:58:25.556124 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Thu Apr 06 17:58:25.556131 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     rv = self.dispatch_request()
[Thu Apr 06 17:58:25.556168 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
[Thu Apr 06 17:58:25.556175 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Apr 06 17:58:25.556771 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/flask_login.py", line 792, in decorated_view
[Thu Apr 06 17:58:25.556791 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     return func(*args, **kwargs)
[Thu Apr 06 17:58:25.557257 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/pgadmin4/pgadmin/tools/backup/__init__.py", line 353, in create_backup_objects_job
[Thu Apr 06 17:58:25.557271 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     utility = manager.utility('backup')
[Thu Apr 06 17:58:25.558294 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 1649, in utility
[Thu Apr 06 17:58:25.558316 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     return self.server_cls.utility(operation, self.sversion)
[Thu Apr 06 17:58:25.558611 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]   File "/srv/pgadmin/lib/python3.4/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/types.py", line 115, in utility
[Thu Apr 06 17:58:25.558625 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025]     bin_path = self.utility_path.get().replace("$DIR", os.path.dirname(sys.modules['__main__'].__file__))
[Thu Apr 06 17:58:25.558669 2017] [wsgi:error] [pid 17225] [remote 10.148.58.130:38025] AttributeError: 'module' object has no attribute '__file__'

**Comment by dpage** [comment]
Issue closed on Redmine.
