### ISSUE TITLE
Table column edit breaks when using column level permissions (RM #2335)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1114]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2335***
*Originally created by **Mathis Neumann** at 2017-04-11 10:18:45 UTC.*

When using column level permissions on a table, the editor for table properties is no longer usable.
In the attached screenshot, I clicked the edit icon on all columns that have a restricted UPDATE permission.
The tabs (General, Definition, ....) are shown, but when clicked will alter the rendered component on the first open element that does not have restricted permissions (id), its weird, see the attached gif.

The javascript console in the Chrome Browser states the following:
<pre>
Uncaught TypeError: Cannot read property 'server' of undefined
    at s.omit_selected_roles (/browser/server/static/js/privilege.js:143:46)
    at s.render (/static/js/backgrid.pgadmin.js:599:49)
    at s.render (/static/vendor/backgrid/backgrid.min.js:8:16623)
    at s.render (/static/vendor/backgrid/backgrid.min.js:8:21526)
    at s.render (/static/vendor/backgrid/backgrid.min.js:8:25023)
    at showGridControl (/static/js/backform.pgadmin.js:1055:26)
    at s.render (/static/js/backform.pgadmin.js:962:19)
    at /static/js/backform.pgadmin.js:566:26
    at Function.m.each.m.forEach (/static/vendor/underscore/underscore-min.js:5:2350)
    at s.g.(anonymous function) [as each] (/static/vendor/backbone/backbone-min.js:1:12091)
</pre>

Steps to reproduce:

# 1. create table with 3 columns
# 2. Grant partial update permissions, e.g.: 
<pre>
GRANT SELECT, UPDATE ("col1", "col3") ON TABLE "test" TO "someuser";
</pre>
# 3. Edit properties on the table in pgAdmin, go columns tab, try to edit "col1" or "col2" (also open "col2" for the effect from the attached gif)

Version info:
<pre>
Version 1.3
Python Version 2.7.13 (default, Mar 3 2017, 23:23:44) [GCC 5.3.0]
Flask Version 0.11.1
Application Mode Desktop
Current User pgadmin4@pgadmin.org
</pre>

I am running the following Docker image of 1.3: https://hub.docker.com/r/thajeztah/pgadmin4/builds/

Sidenote: The permissions should also be listed on the columns, which they are not. I guess that this behaviour is related to the issue.

**Comment by dpage** [comment]
Issue closed on Redmine.
