### ISSUE TITLE
"Initializing the query execution"  message displayed If Click on Explain through query tool window on IE Browser (RM #2347)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1123]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2347***
*Originally created by **Fahar Abbas** at 2017-04-18 12:43:58 UTC.*

Commit ID:
-----------
commit c35dbc7211fe2c32a0bae76bc112b10da183de30

Browsers:
Internal Explorer 11

Tested Platform:
Windows 64

Tested Version:
Python 2.7.11

Steps
1. Launch pgAdmin4 on IE Browser
2. Click on database postgres
3. Launch Query tool window
4. select * from version();
5. Click on explain

Expected Result:
----------------
Explain query should be working fine in IE Browser

Here is the message in Initializing the query execution query tool window:

Here is the output in command line

Exception in thread Thread-245:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\Lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "c:\python27\Lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "c:\python27\Lib\socket.py", line 283, in close
    self.flush()
  File "c:\python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st

Please note that this issue is not reproducible on other browsers.

**Comment by dpage** [comment]
Issue closed on Redmine.
