### ISSUE TITLE
Delete row server error not shown to GUI user (RM #2356)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1131]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2356***
*Originally created by **Matt B** at 2017-04-25 13:35:36 UTC.*

Pgadmin4 v1.4

When deleting a row ( by checking the box on the row and clicking the garbage can delete button) there is an error and the row is not deleted due to foreign key constraint (ok that's expected) but the error is not shown to user on the GUI.
Instead of the GUI showing the error, the query output window selects the "Messages" tab and displays:
Total query runtime: 272 msec.
249 rows retrieved.

Here's my error message:

2017-04-25 09:26:22,497: ERROR  pgadmin:
Failed to execute query (execute_void) for the server #6 - CONN:6136910
(Query-id: 1865129):
Error Message:ERROR:  update or delete on table "message_fields" violates foreign key constraint "fk_alertable_event_fields_1" on table "alertable_event_fields"
DETAIL:  Key (message_name, field_name)=(HEARTBEAT_CHANGED, HB_CHANGED_ON) is still referenced from table "alertable_event_fields".

Exception in thread Thread-120020:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 615, in save
    status, res, query_res, _rowid = trans_obj.save(changed_data)
  File "/usr/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/command.py", line 529, in save
    _rowid = list_of_rowid[i]
IndexError: list index out of range

**Comment by dpage** [comment]
Issue closed on Redmine.
