### ISSUE TITLE
pgAdmin4 test-suite failed to execute with Python2.6.6 on Windows (RM #2367)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1137]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2367***
*Originally created by **navnath gadakh** at 2017-04-28 13:30:05 UTC.*

Getting  ImportError: cannot import name c_ssize_t after I run python runtests.py

Traceback is:
<pre>
Traceback (most recent call last):
  File "pgAdmin4.py", line 23, in <module>
    import config
  File "C:\Users\edb\pgadmin4\web\config.py", line 24, in <module>
    from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
  File "C:\Users\edb\pgadmin4\web\pgadmin\__init__.py", line 17, in <module>
    from flask import Flask, abort, request, current_app, session
  File "C:\Users\edb\venv26\lib\site-packages\flask\__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "C:\Users\edb\venv26\lib\site-packages\flask\app.py", line 27, in <module>
    from . import json, cli
  File "C:\Users\edb\venv26\lib\site-packages\flask\cli.py", line 17, in <module>
    import click
  File "C:\Users\edb\venv26\lib\site-packages\click\__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "C:\Users\edb\venv26\lib\site-packages\click\core.py", line 7, in <module>
    from .types import convert_type, IntRange, BOOL
  File "C:\Users\edb\venv26\lib\site-packages\click\types.py", line 4, in <module>
    from ._compat import open_stream, text_type, filename_to_ui, \
  File "C:\Users\edb\venv26\lib\site-packages\click\_compat.py", line 530, in <module>
    from ._winconsole import _get_windows_console_stream
  File "C:\Users\edb\venv26\lib\site-packages\click\_winconsole.py", line 19, in <module>
    from ctypes import byref, POINTER, c_int, c_char, c_char_p, \
ImportError: cannot import name c_ssize_t
</pre>

Apparently looks like it failed while creating app.

**Comment by dpage** [comment]
Issue closed on Redmine.
