### ISSUE TITLE
Server Exception (RM #2428)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1177]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2428***
*Originally created by **Matt B** at 2017-05-23 15:41:03 UTC.*

Pgadmin 1.5

Not sure what causes this yet but I have multiple instances of this exception over a work session.
Will update issue once I figure out what causes this.

Exception in thread Thread-40041:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 322, in start_query_tool
    return internal_server_error(errormsg=str(e))
  File "/usr/lib/python2.7/site-packages/werkzeug/_compat.py", line 49, in <lambda>
    cls.__str__ = lambda x: x.__unicode__().encode('utf-8')
  File "/usr/lib/python2.7/site-packages/werkzeug/exceptions.py", line 157, in __str__
    return '%d: %s' % (self.code, self.name)
TypeError: %d format: a number is required, not NoneType

**Comment by dpage** [comment]
Issue closed on Redmine.
