### ISSUE TITLE
Query tool polling error (RM #2470)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1197]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2470***
*Originally created by **Murtuza Zabuawala** at 2017-06-07 12:24:46 UTC.*

This issue is impermanent and occurs only when there is some psycopg2 cursor related error occurs during polling.

@Traceback (most recent call last):
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 507, in poll
    status, result = conn.poll(formatted_exception_msg=True)
ValueError: too many values to unpack (expected 2)@

**Comment by dpage** [comment]
Issue closed on Redmine.
