### ISSUE TITLE
simplejson missing a serializer for the bytea[] postgresql column type (RM #2498)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1218]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2498***
*Originally created by **Sander Eikelenboom** at 2017-06-16 10:18:30 UTC.*

While testing pgAdmin 4 v1.5 with postgresql 10 Beta, 
I noticed that pgAdmin 4 doesn't seem to have a simplejson serializer for the bytea[] type,
(haven't tested it, but probably the same applies for the bytea type).

Exception in thread Thread-20200:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/pgadmin4/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 562, in poll
    'additional_messages': additional_messages
  File "/opt/pgadmin4/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/ajax.py", line 58, in make_json_response
    response=json.dumps(doc, cls=DataTypeJSONEncoder, separators=(',',':')),
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/simplejson/__init__.py", line 386, in dumps
    **kw).encode(obj)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/opt/pgadmin4/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/ajax.py", line 30, in default
    return json.JSONEncoder.default(self, obj)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <read-only buffer for 0x7f88a8e178b0, size 14, offset 0 at 0x7f88a94774b0> is not JSON serializable

**Comment by dpage** [comment]
Issue closed on Redmine.
