### ISSUE TITLE
Select query on table with point[] type column fails: ValueError: could not convert string to float: (5.48612858634442,51.4255154435523 (RM #2576)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1282]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2576***
*Originally created by **Sander Eikelenboom** at 2017-07-17 13:26:40 UTC.*

While trying to do a select * on a table with a point[] type column, i get this splat with pgadmin4 1.6:

Exception in thread Thread-47260:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pgadmin4/pgadmin4/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/pgadmin4/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 548, in poll
    st, result = conn.async_fetchmany_2darray(ON_DEMAND_RECORD_COUNT)
  File "/opt/pgadmin4/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 1115, in async_fetchmany_2darray
    res = cur.fetchmany(records)
  File "/opt/pgadmin4/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/cursor.py", line 196, in fetchmany
    tuples = _cursor.fetchmany(self, size)
ValueError: could not convert string to float: (5.48612858634442,51.4255154435523)

**Comment by dpage** [comment]
Issue closed on Redmine.
