### ISSUE TITLE
Runtime using wrong Python version (RM #2614)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1311]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2614***
*Originally created by **Vikash Kathirvel** at 2017-07-28 19:55:39 UTC.*

The pgAdmin 4.1.6 runtime when building from source is causing problems.

OS: ubuntu 17.04
qmake version: 3.0
QT version: 5.7.1
default python: 2.7.13

I built the source using the above configuration.
I create a virtual environment and install the requirements using the requirements.txt

I add the following line in .config/pgadmin/pgadmin4.conf
PythonPath=/home/vikash/.virtualenvs/pgadmin4/lib/python2.7/site-packages

I setup the config_local.py to run in desktop mode by setting SERVER_MODE=False

However, if i execute the runtime, it throws an exception: module backports not found.
But when i try to import it in my python virtualenv, i can successfully import it.

<pre>
Python path:  "/home/vikash/.virtualenvs/pgadmin4/lib/python2.7/site-packages"
Python Home:  ""
Webapp path:  "/home/vikash/Sources/pgadmin4-1.6/web/pgAdmin4.py"
2017-07-29 01:08:49,777: INFO	pgadmin:	################################
########################
2017-07-29 01:08:49,777: INFO	pgadmin:	Starting pgAdmin 4 v1.6...
2017-07-29 01:08:49,777: INFO	pgadmin:	################################
########################
2017-07-29 01:08:49,777: DEBUG	pgadmin:	Python syspath: ['/home/vikash/S
ources/pgadmin4-1.6/web', '/home/vikash/.virtualenvs/pgadmin4/lib/python2.7/site
-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/
usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib
-dynload', '/home/vikash/.virtualenvs/pgadmin4/lib/python2.7/site-packages']
2017-07-29 01:08:49,777: DEBUG	pgadmin:	Available translations: [Locale('zh'), Locale('de'), Locale('pl')]
NOTE: Configuring authentication for DESKTOP mode.
Traceback (most recent call last):
  File "/home/vikash/Sources/pgadmin4-1.6/web/pgAdmin4.py", line 44, in <module>
    exec(open(file_quote(setupfile), 'r').read())
  File "<string>", line 37, in <module>
  File "/home/vikash/Sources/pgadmin4-1.6/web/pgadmin/__init__.py", line 291, in create_app
    driver.init_app(app)
  File "/home/vikash/Sources/pgadmin4-1.6/web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/home/vikash/Sources/pgadmin4-1.6/web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vikash/Sources/pgadmin4-1.6/web/pgadmin/utils/driver/psycopg2/__init__.py", line 41, in <module>
    from backports import csv
ImportError: No module named backports

</pre>
 
The only problem i could see from the logs is that importlib is using "/usr/lib/python2.7/importlib/__init__.py" rather than the one in the virtualenv.
Is that the intended behavior? What could be causing the issue?

**Comment by dpage** [comment]
Issue closed on Redmine.
