### ISSUE TITLE
[Web based] Error message displayed related to "AttributeError: 'module' object has no attribute 'SERVER_MODE'" If user perform git pull on pgAdmin4 setup (RM #2663)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1352]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2663***
*Originally created by **Fahar Abbas** at 2017-08-25 10:49:32 UTC.*

 git log -n 1
commit 0e5ea582943dd345c6b5e62a1d5213f89f6ca834
Author: Dave Page <dpage@pgadmin.org>
Date:   Fri Aug 25 11:19:27 2017 +0100

    Ensure builtins.SERVER_MODE is present so the docs build cleanly.
(venv) fahar@ubuntu:~/Projects/pgadmin4$ cd web/
(venv) fahar@ubuntu:~/Projects/pgadmin4/web$ python setup.py 
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    import config
  File "/home/fahar/Projects/pgadmin4/web/config.py", line 118, in <module>
    if builtins.SERVER_MODE is None:
AttributeError: 'module' object has no attribute 'SERVER_MODE'

**Comment by dpage** [comment]
Issue closed on Redmine.
