### ISSUE TITLE
ValueError: IV must be 16 bytes long (RM #2765)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1415]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2765***
*Originally created by **Philipp Neuhaus** at 2017-10-06 09:13:07 UTC.*

I don't know under which circumstances this error occured, but I have several of them in my console output:

<pre>
2017-10-06 08:45:55,481: ERROR	pgadmin:	IV must be 16 bytes long
Traceback (most recent call last):
  File "/XXX/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 289, in connect
    password = decrypt(encpass, user.password)
  File "/XXX/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/crypto.py", line 54, in decrypt
    cipher = AES.new(pad(key), AES.MODE_CFB, iv)
  File "/XXX/pgadmin4/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/XXX/pgadmin4/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/XXX/pgadmin4/local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long
</pre>

Version:
<pre>
Version1.6
CopyrightCopyright 2013 - 2017, The pgAdmin Development Team
Python Version2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Flask Version0.11.1
Application ModeDesktop
Current Userpgadmin4@pgadmin.org
</pre>

I don't know much about crypto and how you use it here - but if the IV is really uninitialised this may result in weak crypto....

If this isn't really a bug - please catch that Exception.

**Comment by dpage** [comment]
Issue closed on Redmine.
