### ISSUE TITLE
pgAdmin4 desktop startup error (RM #2770)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1419]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2770***
*Originally created by **Marc Hanisch** at 2017-10-09 08:19:16 UTC.*

I'm using pgAdmin4 since the first version and just downloaded pgAdmin4 v2.0.
I'm starting it on my desktop with the following command:

<pre>source ~/pgadmin4/bin/activate && python ~/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py</pre>

With version 2.0 I get the following error:

<pre>
Traceback (most recent call last):
  File "/home/marc/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 56, in <module>
    exec(open(file_quote(setupfile), 'r').read())
  File "<string>", line 46, in <module>
  File "/home/marc/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 23, in create_app_data_directory
    _create_directory_if_not_exists(os.path.dirname(config.SQLITE_PATH))
  File "/home/marc/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 15, in _create_directory_if_not_exists
    os.mkdir(_path)
OSError: [Errno 13] Permission denied: '/var/lib/pgadmin'
</pre>

Why is it searching for the data_directory in /var/lib/pgadmin, although I've setup 

<pre>SERVER_MODE = false</pre> in config_local.py?

**Comment by dpage** [comment]
Issue closed on Redmine.
