### ISSUE TITLE
[Desktop Runtime] 500 Internal Server Error (RM #2806)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1445]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2806***
*Originally created by **Pavel Klimenko** at 2017-10-17 06:21:37 UTC.*

After a long time with pgAdmin4, queries stop executing and text is displayed in the Messages window:

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> 
The problem is solved only by reconnecting to the DBMS.

I'm try follow the steps:

1) Change the logging level to debug, Refer: https://www.pgadmin.org/faq/#8
2) Change the refresh time interval values from '1' to '123456' for all the graphs to prevent unwanted logging from dashboard queries.
File -> Preferences -> Paths -> Dashboards -> Graphs
3) Close pgAdmin4
4) Delete/Rename existing pgAdmin4.log file from 
Windows:
C:\Users\<YourUsername>\AppData\Roaming\pgAdmin\pgadmin4.log
Linux:
~/.pgadmin/pgadmin4.log
5) Open pgAdmin4 again, try to re-produce the issue.
6) Upload/Attach pgAdmin4.log file on bug tracker.

but
In my case application not run with config_local.py
Fatal error "The application server could not be contacted."
I set DEBUG = True in config.py. is it equivalent to create config_local.py for debug?
But with this option query window dont open currectly on PG10 server.

I'm re-produce error with call command:
> CREATE PUBLICATION alltables FOR ALL TABLES;
But this is not the same error that occurs when you work for a long time, since other requests are executed.

Error in log:

> 2017-10-17 09:08:06,367: ERROR	werkzeug:	Error on request:
> Traceback (most recent call last):
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
> execute(self.server.app)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\werkzeug\serving.py", line 197, in execute
> application_iter = app(environ, start_response)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1997, in __call__
> return self.wsgi_app(environ, start_response)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
> response = self.handle_exception(e)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1540, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
> response = self.full_dispatch_request()
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1517, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
> rv = self.dispatch_request()
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1598, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "D:\Program Files\pgAdmin 4\v2\venv\Lib\site-packages\flask_login.py", line 792, in decorated_view
> return func(*args, **kwargs)
> File "D:\Program Files\pgAdmin 4\v2\web\pgadmin\tools\sqleditor\__init__.py", line 541, in poll
> status, result = conn.poll(formatted_exception_msg=True, no_result=True)
> File "D:\Program Files\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\__init__.py", line 1395, in poll
> errmsg = self._formatted_exception_msg(pe, formatted_exception_msg)
> File "D:\Program Files\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\__init__.py", line 1612, in _formatted_exception_msg
> self.decode_to_utf8(exception_obj.diag.message_primary)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
>

**Comment by dpage** [comment]
Issue closed on Redmine.
