### ISSUE TITLE
[Web Based] User can Click on select button if it is disable in query tool window (RM #2923)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1526]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2923***
*Originally created by **Fahar Abbas** at 2017-11-30 10:37:21 UTC.*

Platform:
Windows 2012(Python 2.7) and MAC 10.12(Python 3.6)

Commit ID:
-----------------
commit d54c35d74f5851a6aa6f79c162c1ea1f7fa75b52

Steps

1. Launch query tool windows
2. Click on Open file
3. Click on select button that is disabled
4. File opened 
5. Loading that File message displayed.

Here is the exception displayed:

Exception in thread Thread-400:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\Lib\SocketServer.py", line 652, in __init__
    self.handle()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 20
0, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "c:\python27\Lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 23
5, in handle_one_request
    return self.run_wsgi()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 17
7, in run_wsgi
    execute(self.server.app)
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 16
5, in execute
    application_iter = app(environ, start_response)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 2000, in
__call__
    return self.wsgi_app(environ, start_response)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1991, in
wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1567, in
handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1988, in
wsgi_app
    response = self.full_dispatch_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1641, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1544, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1639, in
full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1625, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask_login.py", line 792, in
 decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\__init__.py", line 1628
, in load_file
    file_path
  File "C:\Projects\pgadmin4\web\pgadmin\misc\file_manager\__init__.py", line 11
00, in check_file_for_bom_and_binary
    return status, err_msg, is_binary, is_startswith_bom, enc
UnboundLocalError: local variable 'is_binary' referenced before assignment

**Comment by dpage** [comment]
Issue closed on Redmine.
