### ISSUE TITLE
Getting transient error after application restart (RM #2983)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1570]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2983***
*Originally created by **Murtuza Zabuawala** at 2018-01-05 07:22:10 UTC.*

Getting random exception, No exact steps to re-produce the issue,

<pre>
Traceback (most recent call last):
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/utils.py", line 242, in dispatch_request
    return method(*args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 157, in wrapped
    return f(self, *args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 246, in nodes
    res = self.get_nodes(gid, sid)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 208, in get_nodes
    db_restrictions=db_disp_res
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/edb/Documents/projects/venv_pg4/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/utils/versioned_template_loader.py", line 47, in get_source
    if server_version['number'] > int(specified_version_number):
ValueError: invalid literal for int() with base 10: 'None'

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
