### ISSUE TITLE
500 Internal Server (RM #3053)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1625]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3053***
*Originally created by **German Eduardo Wilches Cabrera** at 2018-01-24 21:24:15 UTC.*

when i login the database i cant query the data, show me the error only in 1 database, other databases query is not a problem. Please need help because i cant development on database.

pgadmin4 v2.1
python >2.7
windows 8

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

On the log pgadmin

2018-01-23 15:35:48,790: ERROR werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\werkzeug\serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\tools\sqleditor\__init__.py", line 690, in poll
    st, result = conn.async_fetchmany_2darray(ON_DEMAND_RECORD_COUNT)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\__init__.py", line 1099, in async_fetchmany_2darray
    res = cur.fetchmany(records)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\cursor.py", line 196, in fetchmany
    tuples = _cursor.fetchmany(self, size)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 4: invalid continuation byte

**Comment by dpage** [comment]
Issue closed on Redmine.
