### ISSUE TITLE
pgadmin shows misleading "Query returned successfully" with incorrect SQL (RM #3090)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1654]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3090***
*Originally created by **Mateusz Kondej** at 2018-02-07 10:10:28 UTC.*

When executing invalid SQL eg:
<pre<code class="sql">
INSERT non_existing_table (dup) VALUES ('kaka');
</code></pre>

pgAdmin4 returns misleading result:
<pre>
Query returned successfully in 91 msec.
</pre>

!pgadmin4_non_existing_table_but_successfull.png!

pgadmin serwer returns error:
<pre>
Exception in thread Thread-117718:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/user/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/user/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/home/user/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/user/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 674, in poll
    status, result = conn.poll(formatted_exception_msg=True, no_result=True)
  File "/home/user/.local/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 1304, in poll
    errmsg = self._formatted_exception_msg(pe, formatted_exception_msg)
  File "/home/user/.local/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 1541, in _formatted_exception_msg
    self.decode_to_utf8(exception_obj.diag.message_primary)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1: ordinal not in range(128)
</pre>

I'm using:
 - pgAdmin 4 (Python Wheel: pgadmin4-2.1-py2.py3-none-any.whl) in server mode
 - Python 2.7.12
 - Ubuntu 16.04.3 LTS
 - Qt version 5.9.3
 - pip freeze in attachment
 - Postgesql Version: "PostgreSQL 9.6.5 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit"

**Comment by dpage** [comment]
Issue closed on Redmine.
