### ISSUE TITLE
pgAdmin4 v. 1.21 cannot handle Tables who's pk is called uppercase "ID" (RM #3105)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1665]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3105***
*Originally created by **Khushboo Vashi** at 2018-02-12 10:11:18 UTC.*

As per Nicolas Dechamps <nick@moonsilence.de>

Create a table with "ID" als primary key.

Try to enter data into a row in the grid, click save.

This Error appears in the Application:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

This Error appears in the pgadmin4 log:

2018-02-12 09:43:53,704: ERROR    werkzeug:    Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\werkzeug\serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\pgAdmin 4\v2\venv\Lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\tools\sqleditor\__init__.py", line 991, in save
    default_conn)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\tools\sqleditor\command.py", line 647, in save
    item['select_sql'], res['rows'][0])
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\__init__.py", line 1028, in execute_dict
    self.__internal_blocking_execute(cur, query, params)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\__init__.py", line 575, in __internal_blocking_execute
    cur.execute(query, params)
  File "C:\Program Files (x86)\pgAdmin 4\v2\web\pgadmin\utils\driver\psycopg2\cursor.py", line 176, in execute
    return _cursor.execute(self, query, params)
KeyError: '"ID"'

**Comment by dpage** [comment]
Issue closed on Redmine.
