### ISSUE TITLE
Fix TableSpace regression test on Python3.x (RM #3138)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1680]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3138***
*Originally created by **Murtuza Zabuawala** at 2018-02-21 05:53:18 UTC.*

<pre>
NOTE: Configuring authentication for DESKTOP mode.
pgAdmin 4 - Application Initialisation
======================================

Traceback (most recent call last):
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/utils/route.py", line 74, in load_generators
    import_module(module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/tablespaces/tests/test_backend_supported.py", line 10, in <module>
    from mock import MagicMock
ModuleNotFoundError: No module named 'mock'

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
