### ISSUE TITLE
[Web based] Exception displayed if user try to select query and Click on Explain for query tool window (RM #3139)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1681]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3139***
*Originally created by **Fahar Abbas** at 2018-02-21 05:59:54 UTC.*

Tested Platform:
Windows 2012R2 64(Python 2.7.13)
Commit ID:
commit ba70634e5f4bcd952facf68c0f4d39a651867c67

Steps:
1. Launch query tool window
2. write select * from version
3. Click on Explain query 
4. Initializing query execution message displayed and following exception displayed in terminal:

(Scripts) C:\Projects\pgadmin4\web>python pgAdmin4.py
Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
Exception in thread Thread-148:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\Lib\SocketServer.py", line 652, in __init__
    self.handle()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 20
0, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "c:\python27\Lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 23
5, in handle_one_request
    return self.run_wsgi()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 17
7, in run_wsgi
    execute(self.server.app)
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 16
5, in execute
    application_iter = app(environ, start_response)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 2000, in
__call__
    return self.wsgi_app(environ, start_response)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1991, in
wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1567, in
handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1988, in
wsgi_app
    response = self.full_dispatch_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1641, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1544, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1639, in
full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1625, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask_login.py", line 792, in
 decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\__init__.py", line 537,
 in start_query_tool
    sql, trans_id, session
  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\utils\start_running_que
ry.py", line 70, in execute
    effective_sql_statement = apply_explain_plan_wrapper_if_needed(manager, sql)

  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\utils\apply_explain_pla
n_wrapper.py", line 22, in apply_explain_plan_wrapper_if_needed
    return render_template(template_path, sql=sql['sql'], **explain_plan)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\templating.py", line 13
3, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_lis
t),
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\environment.py", line
830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\environment.py", line
791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\environment.py", line
765, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\loaders.py", line 113,
 in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Projects\pgadmin4\web\pgadmin\utils\versioned_template_loader.py", li
ne 63, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: sqleditor/sql\#100000#\explain_plan.sql

Exception in thread Thread-149:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\Lib\SocketServer.py", line 652, in __init__
    self.handle()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 20
0, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "c:\python27\Lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 23
5, in handle_one_request
    return self.run_wsgi()
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 17
7, in run_wsgi
    execute(self.server.app)
  File "C:\Projects\venv\Scripts\lib\site-packages\werkzeug\serving.py", line 16
5, in execute
    application_iter = app(environ, start_response)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 2000, in
__call__
    return self.wsgi_app(environ, start_response)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1991, in
wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1567, in
handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1988, in
wsgi_app
    response = self.full_dispatch_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1641, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1544, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1639, in
full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\app.py", line 1625, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask_login.py", line 792, in
 decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\__init__.py", line 537,
 in start_query_tool
    sql, trans_id, session
  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\utils\start_running_que
ry.py", line 70, in execute
    effective_sql_statement = apply_explain_plan_wrapper_if_needed(manager, sql)

  File "C:\Projects\pgadmin4\web\pgadmin\tools\sqleditor\utils\apply_explain_pla
n_wrapper.py", line 22, in apply_explain_plan_wrapper_if_needed
    return render_template(template_path, sql=sql['sql'], **explain_plan)
  File "C:\Projects\venv\Scripts\lib\site-packages\flask\templating.py", line 13
3, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_lis
t),
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\environment.py", line
830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\environment.py", line
791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\environment.py", line
765, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Projects\venv\Scripts\lib\site-packages\jinja2\loaders.py", line 113,
 in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Projects\pgadmin4\web\pgadmin\utils\versioned_template_loader.py", li
ne 63, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: sqleditor/sql\#100000#\explain_plan.sql

Please note that this is specific to windows 2012 server 64 bit and using python 2.7.13 and this issue is not reproducible on MAC OS 12(Python 3.6)

**Comment by dpage** [comment]
Issue closed on Redmine.
