### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__context__': Issue on server delete  (RM #1172)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#173]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1172***
*Originally created by **Karen Blatchley** at 2016-05-17 20:48:30 UTC.*

1. Delete any added server
 (right click on server -> click Delete/Drop)

Observation:
server get deleted,in JSON response it throws error

runTest (pgadmin.browser.server_groups.servers.tests.test_server_delete.ServersDeleteTestCase)
This function will get all available servers under object browser (Default Server Node url) ... 2016-05-13 14:23:54,443: ERROR pgadmin:	'NoneType' object has no attribute '__context__'
Traceback (most recent call last):
  File "/home/edb/Downloads/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 301, in delete
    info = traceback.format_exc()
  File "/usr/lib/python3.4/traceback.py", line 
256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'

Created by Priyanka Shendge 2016-05-13

**Comment by dpage** [comment]
Issue closed on Redmine.
