### ISSUE TITLE
User can not delete/Drop any object from shift+Alt+d in IE Browsers (RM #3220)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1741]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3220***
*Originally created by **Fahar Abbas** at 2018-03-19 09:53:38 UTC.*

Testing platform:
----------------------
Windows 2012R2(Python 2.7.13)
Commit ID:

commit 93d44d5643f36362cd6dff458b527714d7a6f4fb

1. Launch pgAdmin4 with IE Browser
2. Connect to PG-10 server
3. Click on database
4. Press shift+Alt+d
5. nothing happen

(Scripts) C:\Projects\pgadmin4\web>python pgAdmin4.py
Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2018-03-19 14:48:49,549: ERROR  pgadmin:        Exception when checking for upda
te
Traceback (most recent call last):
  File "C:\Projects\pgadmin4\web\pgadmin\browser\__init__.py", line 761, in inde
x
    response = urlreq.urlopen(url, data, 5)
  File "c:\python27\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python27\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "c:\python27\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "c:\python27\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\Lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "c:\python27\Lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Please note that User can drop object through shift+Alt+d command on firefox, safari, chrome

**Comment by dpage** [comment]
Issue closed on Redmine.
