### ISSUE TITLE
[Web based] Exception displayed if user change the language to Japanese and try to Click on Prefrences after reset layout (RM #3252)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1765]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3252***
*Originally created by **Fahar Abbas** at 2018-04-06 09:13:49 UTC.*

Commit ID:

commit fa1854bd85502ea9db2716f18d5edf0bd79cacdc

Platform:
MAC 10.12(Python 3.6)

Steps:
1. Launch pgAdmin4 on MAC OS X 10.12(Python 3.6)
2. go into preferences and change language to Japanese and Click on Reset layout
3. Again Click on Preferences
4. No information displayed
5. Exception displayed 

Once we change Japanese language under preferences and click on preferences the following exception displayed:

(myenv) Fahars-Mac:web fahar12$ python pgAdmin4.py
/Users/fahar12/myenv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2018-04-06 00:18:29,605: ERROR    werkzeug:    Error on request:
Traceback (most recent call last):
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/fahar12/Projects/pgadmin4/web/pgadmin/preferences/__init__.py", line 131, in preferences
    p['help_str'] = gettext(p['help_str'])
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask_babelex/__init__.py", line 623, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/Users/fahar12/myenv/lib/python3.6/site-packages/flask_babelex/__init__.py", line 534, in gettext
    return t.ugettext(string) % variables
ValueError: unsupported format character '?' (0x5927) at index 70

**Comment by dpage** [comment]
Issue closed on Redmine.
