### ISSUE TITLE
can't connect to any server (RM #3293)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1798]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3293***
*Originally created by **Rudolf Naujack** at 2018-04-18 07:59:35 UTC.*

after update from 4.21 to 4.3 on ubuntu 16.04 LTS i can't connect to any server. 

The dialog for the password said "readonly attribute" and nothing happens.

I've delete ~/.pgadmin and startet anew. Now i can't create a new server because "Error saving properties: readonly attribute"

I've installed/updated  pgadmin via apt and ppa

The log file is here:

2018-04-18 09:51:05,604: ERROR	pgadmin:	readonly attribute
Traceback (most recent call last):
  File "/usr/share/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 770, in create
    server_types=ServerType.types()
  File "/usr/share/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 313, in connect
    pg_conn.notices = deque([], self.ASYNC_NOTICE_MAXLENGTH)
AttributeError: readonly attribute
2018-04-18 09:56:06,920: ERROR	pgadmin:	readonly attribute
Traceback (most recent call last):
  File "/usr/share/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 770, in create
    server_types=ServerType.types()
  File "/usr/share/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 313, in connect
    pg_conn.notices = deque([], self.ASYNC_NOTICE_MAXLENGTH)
AttributeError: readonly attribute

**Comment by dpage** [comment]
Issue closed on Redmine.
