### ISSUE TITLE
Password Dialog Problem after update from 2.1 to 3.0 (RM #3296)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1801]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3296***
*Originally created by **Isaias Sanchez** at 2018-04-18 13:50:57 UTC.*

The password dialog was displaying an error about encrypting saved passwords.
After deleting all the passwords to store them again the an internal error appear and I cannot connect the server.

I am using python wheel version over python 3.6.

The log are:

=======
2018-04-18 13:30:12,584: ERROR  pgadmin:        Object type <class 'str'> cannot be passed to C code
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 962, in connect
    if password is not None else server.password
  File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/utils/crypto.py", line 31, in encrypt
    cipher = AES.new(pad(key), AES.MODE_CFB, iv)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 200, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 55, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/_mode_cfb.py", line 230, in _create_cfb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 100, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 196, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
2018-04-18 13:30:12,597: ERROR  werkzeug:       Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/browser/utils.py", line 254, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 965, in connect
    return internal_server_error(errormsg=e.message)
AttributeError: 'TypeError' object has no attribute 'message'

======

**Comment by dpage** [comment]
Issue closed on Redmine.
