### ISSUE TITLE
ERROR	pgadmin:	Object type <class 'str'> cannot be passed to C code (RM #3297)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1802]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3297***
*Originally created by **Hans Nieuwenhuis** at 2018-04-18 14:02:33 UTC.*

I am testing pgadmin4 3.0

When I try to create a new server, someting goes wrong with the password handling

The error is :

hn-pgadmin4     | 2018-04-18 15:59:12,051: ERROR	pgadmin:	Object type <class 'str'> cannot be passed to C code
hn-pgadmin4     | Traceback (most recent call last):
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 761, in create
hn-pgadmin4     |     password = encrypt(password, current_user.password)
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/utils/crypto.py", line 31, in encrypt
hn-pgadmin4     |     cipher = AES.new(pad(key), AES.MODE_CFB, iv)
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 200, in new
hn-pgadmin4     |     return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 55, in _create_cipher
hn-pgadmin4     |     return modes[mode](factory, **kwargs)
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/_mode_cfb.py", line 230, in _create_cfb_cipher
hn-pgadmin4     |     cipher_state = factory._create_base_cipher(kwargs)
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 100, in _create_base_cipher
hn-pgadmin4     |     result = start_operation(c_uint8_ptr(key),
hn-pgadmin4     |   File "/usr/local/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 196, in c_uint8_ptr
hn-pgadmin4     |     raise TypeError("Object type %s cannot be passed to C code" % type(data))
hn-pgadmin4     | TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by dpage** [comment]
Issue closed on Redmine.
