### ISSUE TITLE
Error when trying to display trigger functions in SQL view. (RM #3302)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1806]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3302***
*Originally created by **Matt B** at 2018-04-19 13:33:55 UTC.*

Postgresql 9.5.11
Pgadmin4 3.0

When I select tables, they show the schema correctly in the SQL view.
Selecting a trigger function always causes an error.

GUI Error:
"Error retrieving the information - INTERNAL SERVER ERROR Click for details."
Clicking that shows AlertifyJS prompt that cannot be closed.

Server log has this:
2018-04-19 09:26:10,626: ERROR	pgadmin:	Exception when checking for update
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/__init__.py", line 508, in index
    response = urlreq.urlopen(url, data, 5)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>
2018-04-19 09:26:28,771: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/utils.py", line 254, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/server_groups/servers/databases/schemas/functions/__init__.py", line 345, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/server_groups/servers/databases/schemas/functions/__init__.py", line 1053, in sql
    ) + '(' + res['rows'][0]['func_args'] + ')'
KeyError: 'nspname'
2018-04-19 09:27:19,375: ERROR	pgadmin:	Exception when checking for update
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/__init__.py", line 508, in index
    response = urlreq.urlopen(url, data, 5)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>
2018-04-19 09:28:00,469: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/utils.py", line 254, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/server_groups/servers/databases/schemas/functions/__init__.py", line 345, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/browser/server_groups/servers/databases/schemas/functions/__init__.py", line 1053, in sql
    ) + '(' + res['rows'][0]['func_args'] + ')'
KeyError: 'nspname'

Installed Packages:
pgadmin4-python-pbr-3.1.1-1.rhel7.noarch
pgadmin4-python-flask-gravatar-0.5.0-1.rhel7.noarch
pgadmin4-3.0-5.rhel7.x86_64
pgadmin4-python-babel-2.3.4-2.rhel7.noarch
pgadmin4-python-flask-sqlalchemy-2.3.2-1.rhel7.noarch
pgadmin4-python-flask-wtf-0.14.2-1.rhel7.noarch
pgadmin4-python-flask-migrate-2.1.1-1.rhel7.noarch
pgadmin4-python-mimeparse-1.6.0-1.rhel7.noarch
pgadmin4-desktop-gnome-3.0-5.rhel7.noarch
pgadmin4-python-werkzeug-0.11.11-4.rhel7.noarch
pgadmin4-python-htmlmin-0.1.12-1.rhel7.noarch
pgadmin4-python-dateutil-2.7.2-1.rhel7.noarch
pgadmin4-python-pyrsistent-0.14.2-1.rhel7.x86_64
pgadmin4-python-Flask-Mail-0.9.1-4.rhel7.noarch
pgadmin4-python-flask-babel-0.11.1-4.rhel7.noarch
pgadmin4-python-flask-paranoid-0.2-1.rhel7.noarch
pgadmin4-python-itsdangerous-0.24-10.rhel7.noarch
pgadmin4-python-simplejson-3.13.2-1.rhel7.x86_64
pgadmin4-python-blinker-1.4-3.rhel7.noarch
pgadmin4-python-jinja2-2.8-9.rhel7.noarch
pgadmin4-python-extras-1.0.0-2.rhel7.noarch
pgadmin4-python-html5lib-1.0.1-1.rhel7.noarch
pgadmin4-python-flask-login-0.3.2-3.rhel7.noarch
pgadmin4-python-markupsafe-0.23-13.rhel7.x86_64
pgadmin4-python-flask-babelex-0.9.3-1.rhel7.noarch
pgadmin4-python-sqlalchemy-1.2.5-1.rhel7.x86_64
pgadmin4-desktop-common-3.0-5.rhel7.x86_64
pgadmin4-python-backports.csv-1.0.5-3.rhel7.noarch
pgadmin4-python-passlib-1.7.1-1.rhel7.noarch
pgadmin4-python-wtforms-2.1-3.rhel7.noarch
pgadmin4-python-beautifulsoup4-4.5.1-3.rhel7.noarch
pgadmin4-python-flask-0.12.2-1.rhel7.noarch
pgadmin4-python-flask-htmlmin-1.3.2-1.rhel7.noarch
pgadmin4-web-3.0-5.rhel7.noarch
pgadmin4-pytz-2018.3-1.rhel7.noarch
pgadmin4-python-fixtures-3.0.0-5.rhel7.noarch
pgadmin4-python-flask-security-3.0.0-1.rhel7.noarch
pgadmin4-python-alembic-0.9.7-3.rhel7.noarch
pgadmin4-python-flask-principal-0.4.0-14.rhel7.noarch
pgadmin4-docs-3.0-5.rhel7.noarch
pgadmin4-python-sqlparse-0.2.4-1.rhel7.noarch

**Comment by dpage** [comment]
Issue closed on Redmine.
