### ISSUE TITLE
Backup fails and the screen still shows countdown (RM #3312)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1814]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3312***
*Originally created by **Joao Pereira** at 2018-04-25 14:13:24 UTC.*

When there is a problem with the path of the postgres binaries an error is thrown by the backend:

---
2018-04-25 09:43:40,956: INFO	pgadmin:	Executing the process executor with the arguments: ['/home/pivotal/.pyenv/versions/python36/bin/python', '/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py', '/usr/local/bin/pg_dump', '--file', '/home/pivotal/bamm.sql', '--host', '35.193.86.64', '--port', '5432', '--username', 'pgadmin', '--no-password', '--verbose', '--format=c', '--blobs', 'postgres']
2018-04-25 09:43:40,969: INFO	werkzeug:	127.0.0.1 - - [25/Apr/2018 09:43:40] "POST /backup/job/3/object HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py", line 322, in execute
    command, stdout=PIPE, stderr=PIPE, stdin=None, **kwargs
  File "/home/pivotal/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/pivotal/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/pg_dump': '/usr/local/bin/pg_dump'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py", line 544, in <module>
    execute()
  File "/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py", line 359, in execute
    info = _log_exception()
  File "/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py", line 72, in _log_exception
    fp.write('EXCEPTION::\n{0}'.format(res))
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py", line 546, in <module>
    _log_exception()
  File "/home/pivotal/workspace/pgadmin4/web/pgadmin/misc/bgprocess/process_executor.py", line 72, in _log_exception
    fp.write('EXCEPTION::\n{0}'.format(res))
TypeError: a bytes-like object is required, not 'str'
---

But the screen looks like the attachment.

Steps to reproduce:
1 - Setup binary path that is incorrect
2 - Try to backup a schema

**Comment by dpage** [comment]
Issue closed on Redmine.
