### ISSUE TITLE
[Windows] user cannot load "External Tables" on the navigation pane. (RM #3324)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1821]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3324***
*Originally created by **Anthony Emengo** at 2018-05-02 16:27:58 UTC.*

When a user on a *windows* OS attempts to expand the dropdown called "External Tables", there is no change in the UI of pgadmin4 - even when external tables do exist. Furthermore, the console network results show a 500 Internal Server Error, directly as a result of the action.

The following can be seen in the logs following reproduction:
<pre><code class="text">
2018-04-30 09:04:15,604: ERROR              werkzeug:           Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files (x86)\pgAdmin 4\v3\web\pgadmin\browser\utils.py", line 254, in dispatch_request
    return method(*args, **kwargs)
  File "C:\Program Files (x86)\pgAdmin 4\v3\web\pgadmin\browser\server_groups\servers\databases\external_tables\__init__.py", line 141, in wrap
    return function_wrapped(*args, **kwargs)
  File "C:\Program Files (x86)\pgAdmin 4\v3\web\pgadmin\browser\server_groups\servers\databases\external_tables\__init__.py", line 164, in nodes
    os.path.join(self.sql_template_path, 'list.sql')
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Program Files (x86)\pgAdmin 4\v3\web\pgadmin\utils\versioned_template_loader.py", line 63, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: sql/#gpdb#80323#\list.sql
</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
