### ISSUE TITLE
Server setup fails: assert '.' not in view_func.__name__, "Blueprint view function name should not contain dots" (RM #3360)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1849]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3360***
*Originally created by **Marcelo Mendes** at 2018-05-18 16:07:56 UTC.*

After perform an aptitude upgrade, pgadmin fails to installs

<pre>
$cat /etc/debian_version
buster/sid

$ dpkg -l | grep pgadmin
iF  pgadmin4-apache2                            3.0-2.pgdg+1                            all          PostgreSQL management tool - WSGI application
ii  pgadmin4-common                             3.0-2.pgdg+1                            all          PostgreSQL management tool - common files

dpkg -l | grep flask
ii  python3-flask                               1.0.2-1                                 all          micro web framework based on Werkzeug and Jinja2 - Python 3.x
ii  python3-flask-babelex                       0.9.3-1                                 all          Adds i18n/l10n support to Flask applications
ii  python3-flask-gravatar                      0.4.2-1                                 all          Extension for Flask to make usage of Gravatar service
ii  python3-flask-htmlmin                       1.3.2-1                                 all          Minimize render templates html
ii  python3-flask-login                         0.4.1-2                                 all          user session management for Flask -- Python 3 module
ii  python3-flask-mail                          0.9.1+dfsg1-1                           all          Flask extension for sending email
ii  python3-flask-migrate                       2.1.1-2                                 all          SQLAlchemy migrations for Flask using Alembic and Python 3
ii  python3-flask-paranoid                      0.2.0-2                                 all          Simple user session protection
ii  python3-flask-principal                     0.4.0-1                                 all          identity management for Flask
ii  python3-flask-security                      1.7.5-2                                 all          Simple security for Flask apps (Python 3)
ii  python3-flask-sqlalchemy                    2.1-3                                   all          adds SQLAlchemy support to your Python 3 Flask application
ii  python3-flaskext.wtf                        0.14.2-2                                all          Simple integration of Flask and WTForms (Python 3)
</pre>

<pre>

Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    app = create_app()
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 542, in create_app
    app.register_blueprint(module)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1115, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/share/pgadmin4/web/pgadmin/utils/__init__.py", line 68, in register
    app.register_blueprint(module)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1115, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/share/pgadmin4/web/pgadmin/utils/__init__.py", line 61, in register
    self.submodules = list(app.find_submodules(self.import_name))
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 64, in find_submodules
    module = import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 1380, in <module>
    ServerNode.register_node_view(blueprint)
  File "/usr/share/pgadmin4/web/pgadmin/browser/utils.py", line 283, in register_node_view
    methods=c['methods']
  File "/usr/lib/python3/dist-packages/flask/blueprints.py", line 206, in add_url_rule
    assert '.' not in view_func.__name__, "Blueprint view function name should not contain dots"
AssertionError: Blueprint view function name should not contain dots
dpkg: error processing package pgadmin4-apache2 (--configure):
 installed pgadmin4-apache2 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 pgadmin4-apache2
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
