### ISSUE TITLE
Code autocomplete is broken in pgadmin4 V 3.0 (RM #3374)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1861]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3374***
*Originally created by **Lazaro Garcia** at 2018-05-23 13:47:44 UTC.*

After installing pgadmin4 V 3.0 from source, the autocomplete code  on query tool is not working, these errors are logged in apache-error.log. I think this is a bug. Is there any help to solve that?

PgAdmin4 was installed from source code and running behind apache2.4 server on Ubuntu Server 16.04. The python version is: Python 2.7.12
 
For reproducing go to query tool and table fields are not autocompleted for instance:
 
Select person.{ctrl+space does not autocomplete table fields, the error is triggered here} from person

the same here:

Select * from person where {ctrl+space does not autocomplete table fields, the error is triggered here}

[Tue Apr 17 13:27:27.741741 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348] mod_wsgi (pid=4921): Exception occurred processing WSGI script '/var/www/vhosts/pgadmin4/web/pgAdmin4.wsgi'.
[Tue Apr 17 13:27:27.741915 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348] Traceback (most recent call last):
[Tue Apr 17 13:27:27.741945 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
[Tue Apr 17 13:27:27.741987 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     return self.wsgi_app(environ, start_response)
[Tue Apr 17 13:27:27.742006 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
[Tue Apr 17 13:27:27.742033 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     response = self.handle_exception(e)
[Tue Apr 17 13:27:27.742051 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
[Tue Apr 17 13:27:27.742078 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     reraise(exc_type, exc_value, tb)
[Tue Apr 17 13:27:27.742095 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
[Tue Apr 17 13:27:27.742121 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     response = self.full_dispatch_request()
[Tue Apr 17 13:27:27.742138 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Tue Apr 17 13:27:27.742165 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     rv = self.handle_user_exception(e)
[Tue Apr 17 13:27:27.742182 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Tue Apr 17 13:27:27.742208 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     reraise(exc_type, exc_value, tb)
[Tue Apr 17 13:27:27.742225 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Tue Apr 17 13:27:27.742252 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     rv = self.dispatch_request()
[Tue Apr 17 13:27:27.742269 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
[Tue Apr 17 13:27:27.742295 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Apr 17 13:27:27.742313 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
[Tue Apr 17 13:27:27.742340 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     return func(*args, **kwargs)
[Tue Apr 17 13:27:27.742357 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 1231, in auto_complete
[Tue Apr 17 13:27:27.742391 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     res = auto_complete_obj.get_completions(full_sql, text_before_cursor)
[Tue Apr 17 13:27:27.742409 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 239, in get_completions
[Tue Apr 17 13:27:27.742436 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     suggestions = self.suggest_type(text, text_before_cursor)
[Tue Apr 17 13:27:27.742453 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 721, in suggest_type
[Tue Apr 17 13:27:27.742481 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     last_token, text_before_cursor, full_text, identifier
[Tue Apr 17 13:27:27.742505 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 833, in suggest_based_on_last_token
[Tue Apr 17 13:27:27.742533 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     tables = extract_tables(full_text)
[Tue Apr 17 13:27:27.742551 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/parseutils.py", line 193, in extract_tables
[Tue Apr 17 13:27:27.742578 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     return tuple(identifiers)
[Tue Apr 17 13:27:27.742595 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/parseutils.py", line 130, in extract_table_identifiers
[Tue Apr 17 13:27:27.742623 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     for item in token_stream:
[Tue Apr 17 13:27:27.742640 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/parseutils.py", line 93, in extract_from_part
[Tue Apr 17 13:27:27.742667 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     if is_subselect(item):
[Tue Apr 17 13:27:27.742684 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]   File "/var/www/vhosts/pgadmin4/web/pgadmin/utils/sqlautocomplete/parseutils.py", line 76, in is_subselect
[Tue Apr 17 13:27:27.742711 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348]     if not parsed.is_group():
[Tue Apr 17 13:27:27.742736 2018] [wsgi:error] [pid 4921] [remote 192.168.5.130:45348] TypeError: 'bool' object is not callable

**Comment by dpage** [comment]
Issue closed on Redmine.
