### ISSUE TITLE
PGAdmin4 3.0 docker version fails to run (RM #3382)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1867]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3382***
*Originally created by **Rob Tos** at 2018-05-25 08:04:31 UTC.*

Hi,

I don't get PGAdmin4 3.0 docker version running in docker:

<pre>
$ sudo docker start -a pgadmin4
[2018-05-25 07:51:41 +0000] [1] [INFO] Starting gunicorn 19.7.1
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 198, in run
    self.start()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 157, in start
    self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/sock.py", line 158, in create_sockets
    raise ValueError('certfile "%s" does not exist' % conf.certfile)
ValueError: certfile "/certs/server.cert" does not exist
</pre>

I tried to remove and recreate the container and get the same error.

Do I miss something ?

Thx.

**Comment by dpage** [comment]
Issue closed on Redmine.
