### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd8 in position 0: unexpected end of data (RM #3399)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1880]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3399***
*Originally created by **Ibrahim Bakhsh** at 2018-06-03 14:12:19 UTC.*

Environment: 
1- MacOs 
2- Install postgresql + pgadmin 4 v3 

Steps to reproduce: 
1- create a database UTF8 Encoding 
2- create a sample table like this: 
<pre><code class="sql">
CREATE TABLE public.arabic_letters
(
    id integer NOT NULL DEFAULT nextval('arabic_letters_id_seq'::regclass),
    letter "char" NOT NULL,
    ascii_val integer,
    CONSTRAINT arabic_letters_pkey PRIMARY KEY (id)
)
</code></pre>

3- Use this plpgsql code to populate the table with arabic letters: 

<pre><code class="sql">
DO $$
declare 
	c char;
	n int := 0;
begin
	foreach c in ARRAY ARRAY['أ','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي'] 
	loop
		n := n+1;
		insert into arabic_letters(letter,ascii_val) values (c,ascii(c));
	end loop;
	RAISE NOTICE 'Called % Times',n;
end;
$$ LANGUAGE 'plpgsql';

</code></pre>

4- Now from pgadmin browser panel try to retrieve the data stored in the table: 
<pre><code class="sql">
  select * from arabic_letters;
</code></pre>

the log of pgadmin4 on mac shows this error: 

<pre>
2018-06-03 16:53:57,516: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/sqleditor/__init__.py", line 443, in poll
    st, result = conn.async_fetchmany_2darray(ON_DEMAND_RECORD_COUNT)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/connection.py", line 1141, in async_fetchmany_2darray
    res = cur.fetchmany(records)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/cursor.py", line 196, in fetchmany
    tuples = _cursor.fetchmany(self, size)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd8 in position 0: unexpected end of data

</pre>

for any additional information please don't hesitate to contact me
Ibrahim Bakhsh 
Email: igbmadinah@gmail.com

**Comment by dpage** [comment]
Issue closed on Redmine.
