### ISSUE TITLE
pgAdmin 4, Mac. The application server could not be contacted (RM #3411)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1888]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3411***
*Originally created by **Jérémy Lamie** at 2018-06-11 09:14:25 UTC.*

Hello,

I have an issue with launching pgAdmin4 on my Mac (MacOS 10.13.4) since I reboot my computer.
I get  : The Application server could not be contacted.

If I delete the folder ".pgadmin", pgAdmin will launch. But I cannot do that each time I reboot, due to the loss of pgAdmin configuration.

I see in this folder a file named pgamin.log which contains this line of error.
Could you provide me a definitive fix ?
Thanks a lot 

Jeremy

2018-06-11 10:55:32,485: ERROR  werkzeug:       Error on request:
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/__init__.py", line 46, in create_module_preference
    self.register_preferences()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/sqleditor/__init__.py", line 114, in register_preferences
    RegisterQueryToolPreferences(self)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/sqleditor/utils/query_tool_preferences.py", line 84, in RegisterQueryToolPreferences
    'The font size to use for the SQL text boxes and editors. '
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask_babelex/__init__.py", line 623, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask_babelex/__init__.py", line 534, in gettext
    return t.ugettext(string) % variables
TypeError: %d format: a number is required, not dict

**Comment by dpage** [comment]
Issue closed on Redmine.
