### ISSUE TITLE
Error when using python 3.7 (RM #3458)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1925]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3458***
*Originally created by **Hans Nieuwenhuis** at 2018-07-01 07:29:07 UTC.*

When using python 3.7 i get an error when running setup.sh ( see below )

I searched and found : https://github.com/psycopg/psycopg2/issues/714

In pyhton 3.7 aysnc and await are now keywords.

OUTPUT OF setup.sh
==================

Enter the email address and password to use for the initial pgAdmin user account:

Email address: jhmnieuwenhuis@gmail.com
Password: 
Retype password:
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    app = create_app()
  File "/usr/local/lib/python3.7/site-packages/pgadmin4/pgadmin/__init__.py", line 367, in create_app
    driver.init_app(app)
  File "/usr/local/lib/python3.7/site-packages/pgadmin4/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/usr/local/lib/python3.7/site-packages/pgadmin4/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 26, in <module>
    from .connection import Connection
  File "/usr/local/lib/python3.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 148
    def __init__(self, manager, conn_id, db, auto_reconnect=True, async=0,
                                                                      ^
SyntaxError: invalid syntax

**Comment by dpage** [comment]
Issue closed on Redmine.
