### ISSUE TITLE
'module' object has no attribute 'GSSException' (RM #3470)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1936]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3470***
*Originally created by **Samuel Teixeira Santos** at 2018-07-05 13:42:26 UTC.*

I run a HTTPD version compiled by hand to run locally in my user folder on a CentOS 7.

When I updated to *pgadmin 3.1*, using a +Python wheel on virtualenv enviroment+ and +SERVER_MODE=True+, this error was listed on HTTPD log:

<pre>
[Thu Jul 05 10:08:37.283959 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012] mod_wsgi (pid=7630): Failed to exec Python script file '~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/pgadmin4/wsgi.py'.
[Thu Jul 05 10:08:37.283997 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012] mod_wsgi (pid=7630): Exception occurred processing WSGI script '~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/pgadmin4/wsgi.py'.
[Thu Jul 05 10:08:37.284024 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012] Traceback (most recent call last):
[Thu Jul 05 10:08:37.284047 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/pgadmin4/wsgi.py", line 15, in <module>
[Thu Jul 05 10:08:37.284125 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     from pgAdmin4 import app as application
[Thu Jul 05 10:08:37.284144 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/2.7.14/envs/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 70, in <module>
[Thu Jul 05 10:08:37.284221 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     app = create_app()
[Thu Jul 05 10:08:37.284240 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/2.7.14/envs/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 367, in create_app
[Thu Jul 05 10:08:37.284398 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     driver.init_app(app)
[Thu Jul 05 10:08:37.284418 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/2.7.14/envs/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/__init__.py", line 40, in init_app
[Thu Jul 05 10:08:37.284482 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     DriverRegistry.load_drivers()
[Thu Jul 05 10:08:37.284505 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/2.7.14/envs/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/registry.py", line 88, in load_drivers
[Thu Jul 05 10:08:37.284571 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     module = import_module(module_name)
[Thu Jul 05 10:08:37.284590 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Jul 05 10:08:37.284649 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     __import__(name)
[Thu Jul 05 10:08:37.284671 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/2.7.14/envs/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 27, in <module>
[Thu Jul 05 10:08:37.284786 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     from .server_manager import ServerManager
[Thu Jul 05 10:08:37.284807 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/2.7.14/envs/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/server_manager.py", line 27, in <module>
[Thu Jul 05 10:08:37.284928 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     from sshtunnel import SSHTunnelForwarder, BaseSSHTunnelForwarderError
[Thu Jul 05 10:08:37.284955 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/sshtunnel.py", line 25, in <module>
[Thu Jul 05 10:08:37.285293 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     import paramiko
[Thu Jul 05 10:08:37.285315 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
[Thu Jul 05 10:08:37.285386 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     from paramiko.transport import SecurityOptions, Transport
[Thu Jul 05 10:08:37.285406 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
[Thu Jul 05 10:08:37.285910 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     from paramiko.auth_handler import AuthHandler
[Thu Jul 05 10:08:37.285933 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/paramiko/auth_handler.py", line 48, in <module>
[Thu Jul 05 10:08:37.286117 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
[Thu Jul 05 10:08:37.286139 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]   File "~/.pyenv/versions/pgadmin4/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 54, in <module>
[Thu Jul 05 10:08:37.286282 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012]     GSS_EXCEPTIONS = (gssapi.GSSException,)
[Thu Jul 05 10:08:37.286312 2018] [wsgi:error] [pid 7630] [remote 10.143.10.134:50012] AttributeError: 'module' object has no attribute 'GSSException'

</pre>

I replace _my home directory_ to *~/* in log above.

I *fix* this on my _config_local.py_ using *SUPPORT_SSH_TUNNEL = False*

this is my first access and interaction here. 

sorry if I post on wrong place or fill it wrong this form. 

I just want to documented this to others

thanks.

**Comment by dpage** [comment]
Issue closed on Redmine.
