### ISSUE TITLE
[PG-11] Autocomplete throws exception on PG-11 (RM #3476)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1940]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3476***
*Originally created by **Aditya Toshniwal** at 2018-07-06 09:43:57 UTC.*

I get below exception when hit Ctrl+Space on PG-11 query window. It works fine for other versions of PG.
2018-07-06 15:11:19,588: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/adityatoshniwal/projects/pypg2/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 1236, in auto_complete
    res = auto_complete_obj.get_completions(full_sql, text_before_cursor)
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 249, in get_completions
    suggestions = self.suggest_type(text, text_before_cursor)
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 711, in suggest_type
    stmt_len = len(statement.to_unicode())
AttributeError: 'Statement' object has no attribute 'to_unicode'

**Comment by dpage** [comment]
Issue closed on Redmine.
