### ISSUE TITLE
Python 3.6 certificate error mac (RM #3492)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1952]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3492***
*Originally created by **David Clarke** at 2018-07-11 22:10:24 UTC.*

pgAdmin 4 no longer works on Mac. Log indicates an issue with certificate

<pre>
2018-07-12 10:06:30,491: ERROR	pgadmin:	Exception when checking for update
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/__init__.py", line 508, in index
    response = urlreq.urlopen(url, data, 5)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
