### ISSUE TITLE
Changing password throws error in the logs when connecting back to a server (RM #3539)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1989]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3539***
*Originally created by **Landon Abney** at 2018-08-02 17:40:49 UTC.*

If a user changes their password and then tries to connect to a saved PostgreSQL server the following is printed in the logs:

<pre>
2018-08-02 10:19:09,990: ERROR\tpgadmin:\t'utf8' codec can't decode byte 0xcf in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/psycopg2/connection.py", line 257, in connect
    password = password.decode('utf-8').encode('utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 0: invalid continuation byte
2018-08-02 10:19:09,990: ERROR\tpgadmin:\tCould not connected to server(#10) - 'servername'.
Error: Failed to decrypt the saved password.
Error: 'utf8' codec can't decode byte 0xcf in position 0: invalid continuation byte
</pre>

Steps to reproduce:
1. Create a user
2. Log into the user, add a server and save the password
3. Disconnect from the server
3. Change the user's password
5. Attempt to connect to the server

Versions:
<pre>
Version: 3.1
Copyright: Copyright 2013 - 2018, The pgAdmin Development Team
Python Version: 2.7.5 (default, Aug 4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Flask Version: 0.12.2
Application Mode: Server
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
