### ISSUE TITLE
Make session implementation thread safe (RM #3547)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1996]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3547***
*Originally created by **Harshal Dhumal** at 2018-08-06 07:12:20 UTC.*

@Traceback (most recent call last):
   File "/Python-3.4/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
     return self.wsgi_app(environ, start_response)
   File "/Python-3.4/lib/python3.4/site-packages/flask/app.py", line 1978, in wsgi_app
     ctx.push()
   File "/Python-3.4/lib/python3.4/site-packages/flask/ctx.py", line 332, in push
     self.session = self.app.open_session(self.request)
   File "/Python-3.4/lib/python3.4/site-packages/flask/app.py", line 912, in open_session
     return self.session_interface.open_session(self, request)
   File "/server/share/web/pgadmin/utils/session.py", line 391, in open_session
     return self.manager.get(sid, digest)
   File "/server/share/web/pgadmin/utils/session.py", line 182, in get
     del self._cache[sid]
   File "/languagepack-10/Python-3.4/lib/python3.4/collections/__init__.py", line 81, in __delitem__
     link = self.__map.pop(key)
 KeyError: '1505b241-c379-4386-ab5a-3f42e3032bed'
 mod_wsgi (pid=1593): Exception occurred processing WSGI script '/share/web/pgAdmin4.wsgi'.
 Traceback (most recent call last):
   File "/Python-3.4/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
     return self.wsgi_app(environ, start_response)
   File "/Python-3.4/lib/python3.4/site-packages/flask/app.py", line 1978, in wsgi_app
     ctx.push()
   File "/Python-3.4/lib/python3.4/site-packages/flask/ctx.py", line 332, in push
     self.session = self.app.open_session(self.request)
   File "/Python-3.4/lib/python3.4/site-packages/flask/app.py", line 912, in open_session
     return self.session_interface.open_session(self, request)
   File "/web/pgadmin/utils/session.py", line 391, in open_session
     return self.manager.get(sid, digest)
   File "/web/pgadmin/utils/session.py", line 182, in get
     del self._cache[sid]
   File "/Python-3.4/lib/python3.4/collections/__init__.py", line 84, in __delitem__
     link_prev.next = link_next
 ReferenceError: weakly-referenced object no longer exists
@

**Comment by dpage** [comment]
Issue closed on Redmine.
