### ISSUE TITLE
Unable to launch pgAdmin4.py with python with latest git pull (RM #1206)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#203]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1206***
*Originally created by **Fahar Abbas** at 2016-05-23 04:45:17 UTC.*

python pgAdmin4.py 
Traceback (most recent call last):
  File "pgAdmin4.py", line 56, in <module>
    app = create_app()
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/__init__.py", line 223, in create_app
    app.register_blueprint(module)
  File "/home/fahar/venv/lib/python3.4/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/fahar/venv/lib/python3.4/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/__init__.py", line 55, in register
    self.submodules = list(app.find_submodules(self.import_name))
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/__init__.py", line 44, in find_submodules
    module = import_module(module_name)
  File "/home/fahar/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/tools/datagrid/__init__.py", line 19, in <module>
    from pgadmin.tools.sqleditor.command import *
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 27, in <module>
    from pgadmin.utils.sqlautocomplete.autocomplete import SQLAutoComplete
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 14, in <module>
    import sqlparse
ImportError: No module named 'sqlparse'

**Comment by dpage** [comment]
Issue closed on Redmine.
