### ISSUE TITLE
[Web based] Internal server error displayed if user use Simplified Chinese on pgadmin login and Click on change password screen (RM #3654)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2080]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3654***
*Originally created by **Fahar Abbas** at 2018-09-18 06:16:09 UTC.*

Chinese

Commit ID:
commit 003889f15e8aa6fb8d70431a523f19da1dc50195
Python 2.7.13
Windows 2012 R2 64:

Browser:
Chrome
Internal server error displayed if user use Simplified Chinese on pgadmin login and Click on change password screen. 
please note that this is not reproducible with other languages  

Steps:
------
1. Launch pgAdmin4 with latest commit through git pull
2. Launch Browser and Select simplified Chinese language 
3. pgAdmin4 opened with simplified Chinese 
4. Expand user name field 
5. Click on change password field
6. Internal server error displayed
Here is the output in terminal:
-----
(venv) C:\Projects\pgAdmin4\pgadmin4\web>python pgAdmin4.py
Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2018-09-18 10:59:31,053: ERROR  werkzeug:       Error on request:
Traceback (most recent call last):
  File "C:\Projects\venv\lib\site-packages\werkzeug\serving.py", line 270, in ru
n_wsgi
    execute(self.server.app)
  File "C:\Projects\venv\lib\site-packages\werkzeug\serving.py", line 258, in ex
ecute
    application_iter = app(environ, start_response)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1997, in __call__

    return self.wsgi_app(environ, start_response)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1985, in wsgi_app

    response = self.handle_exception(e)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1540, in handle_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app

    response = self.full_dispatch_request()
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1614, in full_dis
patch_request
    rv = self.handle_user_exception(e)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1517, in handle_u
ser_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1612, in full_dis
patch_request
    rv = self.dispatch_request()
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1598, in dispatch
_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\venv\lib\site-packages\flask_login.py", line 792, in decorat
ed_view
    return func(*args, **kwargs)
  File "C:\Projects\pgAdmin4\pgadmin4\web\pgadmin\browser\__init__.py", line 772
, in change_password
    **_ctx('change_password'))
  File "C:\Projects\venv\lib\site-packages\flask_security\core.py", line 528, in
 render_template
    return render_template(*args, **kwargs)
  File "C:\Projects\venv\lib\site-packages\flask\templating.py", line 134, in re
nder_template
    context, ctx.app)
  File "C:\Projects\venv\lib\site-packages\flask\templating.py", line 116, in _r
ender
    rv = template.render(context)
  File "C:\Projects\venv\lib\site-packages\jinja2\environment.py", line 1008, in
 render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Projects\venv\lib\site-packages\jinja2\environment.py", line 780, in
handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\pgAdmin4\pgadmin4\web\pgadmin\templates\security\change_pass
word.html", line 1, in top-level template code
    {% extends "security/panel.html" %}
  File "C:\Projects\pgAdmin4\pgadmin4\web\pgadmin\templates\security\panel.html"
, line 2, in top-level template code
    {% from "security/fields.html" import render_field_with_errors %}
  File "C:\Projects\pgAdmin4\pgadmin4\web\pgadmin\templates\base.html", line 70,
 in top-level template code
    {% block body %}{% endblock %}
  File "C:\Projects\pgAdmin4\pgadmin4\web\pgadmin\templates\security\panel.html"
, line 10, in block "body"
    <h3 class="panel-title">{% block panel_title %}{% endblock %}</h3>
  File "C:\Projects\pgAdmin4\pgadmin4\web\pgadmin\templates\security\change_pass
word.html", line 2, in block "panel_title"
    {% block panel_title %}{{ _('%(appname)s Password Change', appname=config.AP
P_NAME) }}{% endblock %}
  File "C:\Projects\venv\lib\site-packages\jinja2\ext.py", line 134, in _gettext
_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "C:\Projects\venv\lib\site-packages\jinja2\ext.py", line 143, in gettext
    return rv % variables
  File "C:\Projects\venv\lib\site-packages\markupsafe\__init__.py", line 102, in
 __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character '?' (0x7684) at index 11

**Comment by dpage** [comment]
Issue closed on Redmine.
