### ISSUE TITLE
Error on clicking on SQL panel on EPAS-11 (EPAS-11 installed via RPM) (RM #3706)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2123]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3706***
*Originally created by **Murtuza Zabuawala** at 2018-10-16 06:49:21 UTC.*

Please find attached screenshot for details.

Traceback
-----------

2018-10-16 12:08:47,998: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/utils.py", line 259, in dispatch_request
    return method(*args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/functions/__init__.py", line 350, in wrap
    return f(*args, **kwargs)
  File "/Users/edb/Documents/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/functions/__init__.py", line 1010, in sql
    name_with_default_args = res['rows'][0]['name_with_default_args'].replace(', ', ',\r\t').replace('(', '(\r\t')
  File "/Users/edb/Documents/projects/venv3_pem/lib/python3.6/site-packages/psycopg2/extras.py", line 169, in __getitem__
    x = self._index[x]
KeyError: 'name_with_default_args'

Please also check below nodes as well as I'm getting same error,
- Package > Procedure
- Package > Function

**Comment by dpage** [comment]
Issue closed on Redmine.
