### ISSUE TITLE
Trying to open properties window for a (declaritive) partitioned table fails. (RM #3748)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2150]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3748***
*Originally created by **Sander Eikelenboom** at 2018-11-05 20:02:57 UTC.*

While using Pgadmin 3.5 and Postgresql 11 and trying to open properties window for an existing (declaritive) partitioned table, it fails with this backtrace below.
Opening a properties window for the individual partitions works OK.

--
Sander

2018-11-05 20:36:04,494: ERROR  werkzeug:   Error on request:
Traceback (most recent call last):
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/pgadmin4/pgadmin/browser/utils.py", line 259, in dispatch_request
    return method(*args, **kwargs)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/databases/schemas/tables/utils.py", line 154, in wrap
    return f(*args, **kwargs)
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/databases/schemas/tables/__init__.py", line 613, in properties
    gid, sid, did, scid, tid, res
  File "/opt/pgadmin4/pgadmin4-3.5/lib/python3.7/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/databases/schemas/tables/utils.py", line 2191, in properties
    'FOR VALUES FROM (')[1].split(') TO')
IndexError: list index out of range

**Comment by dpage** [comment]
Issue closed on Redmine.
