### ISSUE TITLE
AttributeError if pgadmin4-web-setup.sh stopped in between login setup and run again  (RM #3830)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2212]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/3830***
*Originally created by **Fahar Abbas** at 2018-12-19 09:58:30 UTC.*

Steps:
Tested Platform:
Centos 07

1.Now install pg repo:
yum install https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
2.. yum clean all
3. yum install epel-release*
4. yum install pgadmin4*
5. Launch pgadmin4-web-setup.sh
6. Provide user name and not provide any password
7. Press Enter twice
8.  Click on Control C+
9. Now session is terminated
10. Again launch pgadmin4-web-setup.sh
11. Attribute Error displayed
------
/usr/pgadmin4/bin/pgadmin4-web-setup.sh
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

Email address:
Invalid email address. Please try again.
Email address:
Invalid email address. Please try again.
Email address: fahar.abbas@####.com
Password:
Retype password:
Password must be at least 6 characters. Please try again.
Password:
Retype password:
Password must be at least 6 characters. Please try again.
Password:
Retype password:
Password must be at least 6 characters. Please try again.
Password:
Retype password:
Password must be at least 6 characters. Please try again.
Password:
Retype password:
Password must be at least 6 characters. Please try again.
Password: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/setup.py", line 410, in <module>
    setup_db()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/setup.py", line 347, in setup_db
    app = create_app()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/__init__.py", line 308, in create_app
    db_upgrade(app)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/../../migrations/env.py", line 94, in <module>
    run_migrations_online()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/migrations/versions/fdc58d9bd449_.py", line 112, in upgrade
    email, password = user_info()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/user_info.py", line 72, in user_info
    p1, p2 = pprompt()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/user_info.py", line 61, in pprompt
    return getpass.getpass(), getpass.getpass('Retype password:')
  File "/usr/lib64/python2.7/getpass.py", line 71, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
  File "/usr/lib64/python2.7/getpass.py", line 133, in _raw_input
    line = input.readline()
KeyboardInterrupt
Error setting up server mode. Please examine the output above.
[root@localhost ~]# /usr/pgadmin4/bin/pgadmin4-web-setup.sh
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/setup.py", line 410, in <module>
    setup_db()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/setup.py", line 347, in setup_db
    app = create_app()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/__init__.py", line 311, in create_app
    schema_version = version.value
AttributeError: 'NoneType' object has no attribute 'value'
Error setting up server mode. Please examine the output above.

**Comment by dpage** [comment]
Issue closed on Redmine.
