### ISSUE TITLE
Getting "No password or public key available!" even when private key file definitely exists (RM #4331)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2652]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4331***
*Originally created by **Jason Grosz** at 2019-06-06 18:42:23 UTC.*

Hey folks!

We are setting up a half dozen users to SSH tunnel through a "jump box" at an enterprise.

* We are getting this error even when the key definitely exists, and can be used to SSH to the machine in question using either OpenSSH on Mac, or PuTty on Windows.
* We did a group tech support meeting, and it appeared to also be intermittent, it would give this error once, and then succeed.
* For some users it appears to be "permanent" and we can't get past it.
* This is happening on Mac OS and on Windows.
* The keys we set up have no passphrase, and these users do not have passwords on the destination machine (SSH keys are their only way in.)

Sorry if this is a duplicate issue, I searched and don't see anything related to this.

Thanks for your efforts!

Love the new pgAdmin 4 interface and built in SSH tunneling is so good for "business users" who don't want to mess with setting up a tunnel outside of the app.

Grosz

<pre>
2019-06-06 12:51:59,220: ERROR	flask.app:	No password or public key available!
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/__init__.py", line 1060, in connect
    server_types=ServerType.types()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/connection.py", line 234, in connect
    status, error = manager.create_ssh_tunnel(tunnel_password)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/server_manager.py", line 432, in create_ssh_tunnel
    remote_bind_address=(self.host, self.port)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/sshtunnel.py", line 905, in __init__
    logger=self.logger
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/sshtunnel.py", line 1096, in _consolidate_auth
    raise ValueError('No password or public key available!')
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
