### ISSUE TITLE
ERROR  flask.app:      connection already closed (RM #4346)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2664]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4346***
*Originally created by **Roland Elferink** at 2019-06-11 13:50:47 UTC.*

I am seeing the following error in my pgadmin log file.  I am running version 4.8 of pgadmin4 on a server and the appliction seems to work correctly but given the number of these errors there must be something wrong somewhere, either a configuration problem or an actual code issue.

<pre>
2019-06-11 14:08:29,004: ERROR  flask.app:      connection already closed
Traceback (most recent call last):
  File "/home/pgadmin/.pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pgadmin/.pgadmin4/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pgadmin/.pgadmin4/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pgadmin/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/tools/sqleditor/__init__.py", line 1446, in query_tool_status
    conn.check_notifies(True)
  File "/home/pgadmin/.pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 1845, in check_notifies
    self.conn.poll()
InterfaceError: connection already closed
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
