### ISSUE TITLE
Download as CSV error with special characters in comment (RM #4418)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2716]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4418***
*Originally created by **Ralf Kraudelt** at 2019-07-01 12:04:15 UTC.*

Hi,

PGAdmin 4.8. Given a simple SQL query with comment: @SELECT 1 -- µ@

When you try to download the result as CSV, you get this error <pre>'exceptions.UnicodeEncodeError' object has no attribute 'strerror'
</pre>

Logfile (CentOS 7, default installation):
<pre>
2019-07-01 13:51:48,496: ERROR  flask.app:      'exceptions.UnicodeEncodeError' object has no attribute 'strerror'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/tools/sqleditor/__init__.py", line 1401, in start_query_download_tool
    err_msg = "Error: {0}".format(e.strerror)
AttributeError: 'exceptions.UnicodeEncodeError' object has no attribute 'strerror'
</pre>

Perhaps there is a problem with Unicode characters in the comment. German umlauts also don't work: äöüß.

Regards
Ralf

**Comment by dpage** [comment]
Issue closed on Redmine.
