### ISSUE TITLE
Ppgadmin 4.11 bug when using the query tool (RM #4550)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2829]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4550***
*Originally created by **Xiangguang Li** at 2019-08-01 13:18:35 UTC.*

Hello lovely pgadmin developers, 
    I just updated my pgadmin 4.3 to 4.11 with Ubuntu Software Update and it seems like my query tool is not working any more. 
    Right click on the table, "View/Edit Data" still work, but when I click "Query Tool" and execute anything (even "select version()"), I just get 'table_oid' as a result. 
    
    Here are the log infos:

    2019-08-01 15:05:38,882: ERROR	flask.app:	'table_oid'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/share/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 432, in poll
    trans_obj.check_updatable_results_pkeys()
  File "/usr/share/pgadmin4/web/pgadmin/tools/sqleditor/command.py", line 899, in check_updatable_results_pkeys
    is_query_resultset_updatable(conn, sql_path)
  File "/usr/share/pgadmin4/web/pgadmin/tools/sqleditor/utils/is_query_resultset_updatable.py", line 38, in is_query_resultset_updatable
    table_oid = _check_single_table(columns_info)
  File "/usr/share/pgadmin4/web/pgadmin/tools/sqleditor/utils/is_query_resultset_updatable.py", line 61, in _check_single_table
    table_oid = columns_info[0]['table_oid']
KeyError: 'table_oid'

    
    Also I have tried to remove pgadmin 4 and reinstall. Problem stays. Probably that is a bug, in the software or in the install packet. Some online forum says psycopg2 version 2.8 is needed, and I only have 2.7. In apt the 2.8 is still not visible currently.

**Comment by dpage** [comment]
Issue closed on Redmine.
