### ISSUE TITLE
fails to run as a regular user (RM #4580)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2857]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4580***
*Originally created by **starenka .** at 2019-08-07 10:34:31 UTC.*

<pre>
starenka /tmp % mktmpenv 
New python executable in /data/.envs/tmp-d251bbd0965f2a3/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d251bbd0965f2a3/bin/predeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d251bbd0965f2a3/bin/postdeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d251bbd0965f2a3/bin/preactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d251bbd0965f2a3/bin/postactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d251bbd0965f2a3/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-d251bbd0965f2a3) starenka /data/.envs/tmp-d251bbd0965f2a3 % pip install /tmp/pgadmin4-4.11-py2.py3-none-any.whl
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /tmp/pgadmin4-4.11-py2.py3-none-any.whl
Collecting Flask-Migrate==2.4.0 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/07/6a/53695aab4c7cf7b230e46a5e4f06e0c9719c01a51223590fd75804439a01/Flask_Migrate-2.4.0-py2.py3-none-any.whl
Collecting htmlmin==0.1.12 (from pgadmin4==4.11)
Collecting speaklater==1.3 (from pgadmin4==4.11)
Collecting sqlparse==0.2.4 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Collecting psutil==5.5.1 (from pgadmin4==4.11)
Collecting blinker==1.4 (from pgadmin4==4.11)
Collecting six>=1.12.0 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting simplejson==3.16.0 (from pgadmin4==4.11)
Collecting Flask==1.0.2 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting WTForms==2.2.1 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/9f/c8/dac5dce9908df1d9d48ec0e26e2a250839fa36ea2c602cc4f85ccfeb5c65/WTForms-2.2.1-py2.py3-none-any.whl
Collecting SQLAlchemy>=1.2.18 (from pgadmin4==4.11)
Collecting pytz==2018.9 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting Flask-Gravatar==0.5.0 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/58/4a/b20260e8d383d0037f2791dd8a3f3ea729ca9f02d7638677a34a236a8702/Flask_Gravatar-0.5.0-py2.py3-none-any.whl
Collecting Flask-Login==0.4.1 (from pgadmin4==4.11)
Collecting python-dateutil>=2.8.0 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting passlib==1.7.1 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl
Collecting Flask-HTMLmin==1.5.0 (from pgadmin4==4.11)
Collecting sshtunnel>=0.1.4 (from pgadmin4==4.11)
Collecting Flask-Security>=3.0.0 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/88/47/4908a5040120768ff4fb2465c7eeafeb9239c27d2919bd67c4ccc1b43e14/Flask_Security-3.0.0-py2.py3-none-any.whl
Collecting Flask-Principal==0.4.0 (from pgadmin4==4.11)
Collecting Flask-Paranoid==0.2.0 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/0e/14/359033a218c5403872e11ff7267e6c638c0279067fa932d93653188f4052/Flask_Paranoid-0.2.0-py2.py3-none-any.whl
Collecting psycopg2-binary>=2.8 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/a1/92/a27986cb7b4bddc7d57781a0e1163d683110907edfca1db3fbce25536492/psycopg2_binary-2.8.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Flask-WTF==0.14.2 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/60/3a/58c629472d10539ae5167dc7c1fecfa95dd7d0b7864623931e3776438a24/Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting Flask-Mail==0.9.1 (from pgadmin4==4.11)
Collecting Flask-SQLAlchemy==2.3.2 (from pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/a1/44/294fb7f6bf49cc7224417cd0637018db9fee0729b4fe166e43e2bbb1f1c8/Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Collecting alembic>=0.7 (from Flask-Migrate==2.4.0->pgadmin4==4.11)
Collecting Jinja2>=2.10 (from Flask==1.0.2->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask==1.0.2->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting click>=5.1 (from Flask==1.0.2->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.14 (from Flask==1.0.2->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/d1/ab/d3bed6b92042622d24decc7aadc8877badf18aeca1571045840ad4956d3f/Werkzeug-0.15.5-py2.py3-none-any.whl
Collecting paramiko>=1.15.2 (from sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl
Collecting Flask-BabelEx>=0.9.3 (from Flask-Security>=3.0.0->pgadmin4==4.11)
Collecting Mako (from alembic>=0.7->Flask-Migrate==2.4.0->pgadmin4==4.11)
Collecting python-editor>=0.3 (from alembic>=0.7->Flask-Migrate==2.4.0->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/55/a0/3c0ba1c10f2ca381645dd46cb7afbb73fddc8de9f957e1f9e726a846eabc/python_editor-1.0.4-py2-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask==1.0.2->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting bcrypt>=3.1.3 (from paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/ad/36/9a0227d048e98409f012570f7bef8a8c2373b9c9c5dfbf82963cbae05ede/bcrypt-3.1.7-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cryptography>=2.5 (from paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/e6/68/50698ce24c61db7d44d93a5043c621a0ca7839d4ef9dff913e6ab465fc92/cryptography-2.7-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pynacl>=1.0.1 (from paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/b3/25/e605574f24948a8a53b497744e93f061eb1dbe7c44b6465fc1c172d591aa/PyNaCl-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Babel>=1.0 (from Flask-BabelEx>=0.9.3->Flask-Security>=3.0.0->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/2c/60/f2af68eb046c5de5b1fe6dd4743bf42c074f7141fe7b2737d3061533b093/Babel-2.7.0-py2.py3-none-any.whl
Collecting cffi>=1.1 (from bcrypt>=3.1.3->paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=2.5->paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.5->paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=2.5->paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=1.15.2->sshtunnel>=0.1.4->pgadmin4==4.11)
Installing collected packages: MarkupSafe, Mako, SQLAlchemy, python-editor, six, python-dateutil, alembic, Jinja2, itsdangerous, click, Werkzeug, Flask, Flask-SQLAlchemy, Flask-Migrate, htmlmin, speaklater, sqlparse, psutil, blinker, simplejson, WTForms, pytz, Flask-Gravatar, Flask-Login, passlib, Flask-HTMLmin, pycparser, cffi, bcrypt, enum34, asn1crypto, ipaddress, cryptography, pynacl, paramiko, sshtunnel, Flask-WTF, Flask-Principal, Flask-Mail, Babel, Flask-BabelEx, Flask-Security, Flask-Paranoid, psycopg2-binary, pgadmin4
Successfully installed Babel-2.7.0 Flask-1.0.2 Flask-BabelEx-0.9.3 Flask-Gravatar-0.5.0 Flask-HTMLmin-1.5.0 Flask-Login-0.4.1 Flask-Mail-0.9.1 Flask-Migrate-2.4.0 Flask-Paranoid-0.2.0 Flask-Principal-0.4.0 Flask-SQLAlchemy-2.3.2 Flask-Security-3.0.0 Flask-WTF-0.14.2 Jinja2-2.10.1 Mako-1.1.0 MarkupSafe-1.1.1 SQLAlchemy-1.3.6 WTForms-2.2.1 Werkzeug-0.15.5 alembic-1.0.11 asn1crypto-0.24.0 bcrypt-3.1.7 blinker-1.4 cffi-1.12.3 click-7.0 cryptography-2.7 enum34-1.1.6 htmlmin-0.1.12 ipaddress-1.0.22 itsdangerous-1.1.0 paramiko-2.6.0 passlib-1.7.1 pgadmin4-4.11 psutil-5.5.1 psycopg2-binary-2.8.3 pycparser-2.19 pynacl-1.3.0 python-dateutil-2.8.0 python-editor-1.0.4 pytz-2018.9 simplejson-3.16.0 six-1.12.0 speaklater-1.3 sqlparse-0.2.4 sshtunnel-0.1.5
(tmp-d251bbd0965f2a3) starenka /data/.envs/tmp-d251bbd0965f2a3 % cdvirtualenv 
(tmp-d251bbd0965f2a3) starenka /data/.envs/tmp-d251bbd0965f2a3 % python lib/python2.7/site-packages/pgadmin4/pgAdmin4.py
Traceback (most recent call last):
  File "lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 64, in <module>
    exec(open(file_quote(setupfile), 'r').read())
  File "<string>", line 413, in <module>
  File "<string>", line 345, in setup_db
  File "/data/.envs/tmp-d251bbd0965f2a3/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 24, in create_app_data_directory
    _create_directory_if_not_exists(os.path.dirname(config.SQLITE_PATH))
  File "/data/.envs/tmp-d251bbd0965f2a3/lib/python2.7/site-packages/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
OSError: [Errno 13] Permission denied: '/var/lib/pgadmin'

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
