### ISSUE TITLE
Blank screen upon opening pgadmin after logging in (RM #4645)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2921]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4645***
*Originally created by **Usama Mehboob** at 2019-08-21 08:09:03 UTC.*

Hi this only happens intermittently. sometime we are able to log in successfully and see our servers and otherwise we are presented with a blank screen.
we are running a 4.10 version of pgadmin pod on EKS cluster. 
This is the error I get 
@2019-08-21 07:57:45,699: ERROR	flask.app:	invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/pgadmin4/pgadmin/browser/utils.py", line 286, in dispatch_request
    return method(*args, **kwargs)
  File "/pgadmin4/pgadmin/browser/server_groups/servers/databases/__init__.py", line 197, in wrapped
    return f(self, *args, **kwargs)
  File "/pgadmin4/pgadmin/browser/server_groups/servers/databases/__init__.py", line 305, in nodes
    res = self.get_nodes(gid, sid)
  File "/pgadmin4/pgadmin/browser/server_groups/servers/databases/__init__.py", line 267, in get_nodes
    db_restrictions=db_disp_res
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/pgadmin4/pgadmin/utils/versioned_template_loader.py", line 15, in get_source
    specified_version_number, exists = parse_version(template)
  File "/pgadmin4/pgadmin/utils/versioned_template_loader.py", line 49, in parse_version
    return int(version), True
ValueError: invalid literal for int() with base 10: 'None'@

Sometime, there is a CSRF exception from pod logs. Please let us know how can we mitigate this?
@Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 221, in csrf_protect
    self.protect()
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 252, in protect
    self._error_response(e.args[0])
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 295, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
::ffff:10.200.254.252 - - [12/Jul/2019:04:42:14 +0000] "GET /dashboard/dashboard_stats/4/27835?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 150 "https://qa-schema.securiti.xyz/browser/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
2019-07-12 04:42:14,187: ERROR    flask.app:    400 Bad Request: The CSRF session token is missing.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 249, in protect
    validate_csrf(self._get_csrf_token())
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 87, in validate_csrf
    raise ValidationError('The CSRF session token is missing.')
wtforms.validators.ValidationError: The CSRF session token is missing.@

**Comment by dpage** [comment]
Issue closed on Redmine.
