### ISSUE TITLE
pgadmin extremly unstable after upgrading to latest.we using it for more then 6 months withou issue.now just hangs (RM #4865)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3084]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4865***
*Originally created by **niteen kole** at 2019-10-21 17:22:13 UTC.*

upgraded to latest container based running on redhat

TimeoutError: [Errno 110] Operation timed out
[2019-10-21 15:27:45 +0000] [84] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 274, in handle
    req = six.next(conn.parser)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.7/ssl.py", line 1056, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.7/ssl.py", line 931, in read
    return self._sslobj.read(len)
TimeoutError: [Errno 110] Operation timed out
::ffff:205.206.15.84 - - [21/Oct/2019:15:27:45 +0000] "GET /dashboard/dashboard_stats/27/16471?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 200 255 "https://pgadmin.cglcloud.ca/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
[2019-10-21 15:27:45 +0000] [84] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 274, in handle
    req = six.next(conn.parser)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/message.py", line 181, in __init__

**Comment by dpage** [comment]
Issue closed on Redmine.
