### ISSUE TITLE
Running "python /usr/lib/python2.7/site-packages/pgadmin4-web/setup.py" gives error "ImportError: /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PQconninfo" (RM #4870)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3088]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4870***
*Originally created by **Warwick Sickling** at 2019-10-23 23:20:24 UTC.*

Hello,

I am trying to configure pgAdmin4 using setup.py, but getting this error when I try:

[root@akl0mg294 pgadmin4]# python /usr/lib/python2.7/site-packages/pgadmin4-web/setup.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/setup.py", line 413, in <module>
    setup_db()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/setup.py", line 347, in setup_db
    app = create_app()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/__init__.py", line 400, in create_app
    driver.init_app(app)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/utils/driver/psycopg2/__init__.py", line 20, in <module>
    import psycopg2
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PQconninfo
[root@akl0mg294 pgadmin4]#

I get the same error if I rerun the command.  The first time I ran it, I was asked for an email address and password but subsequent attempts bypass the request for this information.

Version of pgAdmin installed: pgadmin4.x86_64 4.13-1.rhel7
Installed using yum rather than compiling myself.
OS Version: Red Hat Enterprise Linux Server release 7.5 (Maipo)
Installing in SERVER mode.
Python version: Python 2.7.5
Output from pip freeze:
/var/lib/pgadmin4 # pip freeze
alembic==0.9.8
ansible==2.3.3.0
asn1crypto==0.24.0
awscli==1.15.64
Babel==0.9.6
backports.csv==1.0.5
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
Beaker==1.5.4
blinker==1.3
boto==2.48.0
boto3==1.7.55
botocore==1.10.55
cffi==1.6.0
chardet==2.2.1
click==6.6
colorama==0.3.9
configobj==4.7.2
cryptography==2.2.2
decorator==3.4.0
docutils==0.14
enum34==1.0.4
ethtool==0.8
Flask==0.11.1
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Migrate==2.0.3
Flask-Paranoid==0.1.0
Flask-Principal==0.4.0
Flask-Script==2.0.6
Flask-Security==1.7.5
Flask-SQLAlchemy==2.1
Flask-WTF==0.12
functools32==3.2.3.post2
futures==3.2.0
html5lib==1.0b3
idna==2.7
importlib==1.0.4
iniparse==0.4
ipaddress==1.0.16
isodate==0.5.0
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.5.1
linecache2==1.0.0
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
Mako==1.0.7
MarkupSafe==0.11
paramiko==2.4.1
passlib==1.6.2
Paste==1.7.5.1
perf==0.1
ply==3.4
psycopg2==2.7.4
ptolemy==1.0.0
pulp-agent==2.8.7.20
pulp-common==2.8.7.20
pulp-rpm-common==2.8.7
pulp-rpm-handlers==2.8.7
pyasn1==0.4.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyinotify==0.9.4
pyliblzma==0.5.3
PyNaCl==1.2.1
pyOpenSSL==0.13.1
pyparsing==1.5.6
pyrsistent==0.11.13
python-dateutil==1.5
python-dmidecode==3.10.13
python-editor==1.0.3
python-linux-procfs==0.4.9
python-mimeparse==1.5.1
python-qpid-proton==0.26.0
pytz==2014.10
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.13
requests==2.6.0
rsa==3.4.2
s3transfer==0.1.13
schedutils==0.4
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
speaklater==1.3
SQLAlchemy==1.0.14
subscription-manager==1.20.11
Tempita==0.5.1
urlgrabber==3.10
urllib3==1.10.2
Werkzeug==0.9.6
WTForms==2.0.2
xmltodict==0.11.0
yq==2.7.1
yum-metadata-parser==1.1.4
/var/lib/pgadmin4 #

**Comment by dpage** [comment]
Issue closed on Redmine.
