### ISSUE TITLE
Servers export not working (RM #4897)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3099]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4897***
*Originally created by **Lennar Kallas** at 2019-11-05 11:01:33 UTC.*

Windows 10 Pro
Desktop Runtime

Trying to export servers does not work in CMD:

python "C:\Program Files (x86)\pgAdmin 4\v4\web\setup.py" --dump-servers "C:\output_file.json"

Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\setup.py", line 17, in <module>
    from pgadmin.model import db, User, Version, ServerGroup, Server, \
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\__init__.py", line 19, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ImportError: No module named flask

**Comment by dpage** [comment]
Issue closed on Redmine.
