### ISSUE TITLE
Upgrade to version v4.15 pgAdmin4 failing to start - ReverseProxied (RM #4978)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3156]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4978***
*Originally created by **Graham Sedman** at 2019-11-27 21:09:09 UTC.*

*Below is the output of the error and before updating from v4.14 application was working.  Both Apache error log and running list the error around ReverseProxied.*

2019-11-27 21:03:11,354: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/pgadmin4/web/pgAdmin4.py", line 95, in __call__
    return self.app(environ, start_response)
AttributeError: 'ReverseProxied' object has no attribute 'app'

**Comment by dpage** [comment]
Issue closed on Redmine.
