### ISSUE TITLE
Docker container fails to start (RM #4999)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3172]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4999***
*Originally created by **ES Hicks** at 2019-12-09 18:50:58 UTC.*

Trying to launch a container-based instance of pgadmin4 with the following env vars:

env:
- name: PGADMIN_DEFAULT_EMAIL
  value: "my@email.com"
- name: PGADMIN_DEFAULT_PASSWORD
  value: "a-super-secret-password"
- name: PGADMIN_LISTEN_ADDRESS
  value: "0.0.0.0"
- name: PGADMIN_LISTEN_PORT
  value: "8080"

But I get the following failure at startup:

$ kubectl logs -f pgadmin-678f486878-twqb8
[2019-12-09 18:46:14 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-12-09 18:46:14 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2019-12-09 18:46:14 +0000] [1] [INFO] Using worker: threads
[2019-12-09 18:46:14 +0000] [83] [INFO] Booting worker with pid: 83
[2019-12-09 18:46:20 +0000] [83] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 144, in <module>
    server_port = int(port)
ValueError: invalid literal for int() with base 10: 'tcp://10.96.68.122:8080'
[2019-12-09 18:46:20 +0000] [83] [INFO] Worker exiting (pid: 83)
[2019-12-09 18:46:20 +0000] [1] [INFO] Shutting down: Master
[2019-12-09 18:46:20 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by dpage** [comment]
Issue closed on Redmine.
