### ISSUE TITLE
Stop working after upgrade to 4.12 in Debian 10.2 (RM #5002)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3175]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5002***
*Originally created by **dex terity** at 2019-12-10 10:12:25 UTC.*

Worked alright previous version, but stopped working after apt-get upgrade

Apache error log:
[Tue Dec 10 21:09:02.879734 2019] [mpm_event:notice] [pid 29903:tid 140554818929792] AH00489: Apache/2.4.38 (Debian) mod_wsgi/4.6.5 Python/2.7 configured -- resuming normal operations
[Tue Dec 10 21:09:02.880078 2019] [core:notice] [pid 29903:tid 140554818929792] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 10 21:09:14.117051 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242] mod_wsgi (pid=29904): Failed to exec Python script file '/usr/share/pgadmin4/web/pgAdmin4.wsgi'.
[Tue Dec 10 21:09:14.117124 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242] mod_wsgi (pid=29904): Exception occurred processing WSGI script '/usr/share/pgadmin4/web/pgAdmin4.wsgi'.
[Tue Dec 10 21:09:14.117173 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242] Traceback (most recent call last):
[Tue Dec 10 21:09:14.117225 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242]   File "/usr/share/pgadmin4/web/pgAdmin4.wsgi", line 25, in <module>
[Tue Dec 10 21:09:14.117366 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242]     import config[Tue Dec 10 21:09:14.117413 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242]   File "/usr/share/pgadmin4/web/config.py", line 30, in <module>
[Tue Dec 10 21:09:14.117657 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242]     from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
[Tue Dec 10 21:09:14.117686 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242]   File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 19, in <module>
[Tue Dec 10 21:09:14.118023 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242]     from flask import Flask, abort, request, current_app, session, url_for
[Tue Dec 10 21:09:14.118073 2019] [wsgi:error] [pid 29904:tid 140554713892608] [remote 192.168.1.100:62242] ImportError: No module named flask

**Comment by dpage** [comment]
Issue closed on Redmine.
