### ISSUE TITLE
Query Tool won't connect, forever spinning the Loading Screen (RM #5011)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3182]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5011***
*Originally created by **Raphael Dumas** at 2019-12-12 16:13:30 UTC.*

I've had this issue since about 4.12. I can use the explorer window fine, but when I try to open the Query Tool I'm stuck on the Loading Spinning Wheel.

The only output in the log is:

<pre><code class="text">
2019-12-12 10:35:45,914: ERROR	flask.app:	Exception when checking for update
Traceback (most recent call last):
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 956, in send
    self.connect()
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\browser\__init__.py", line 554, in index
    response = urlreq.urlopen(url, data, 5)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
</code></pre>

I think this could be because our computers access the internet through a proxy.
In Chrome I do have an error show up in the console

<pre><code class="javascript">
sqleditor.js?ver=41500:1 Uncaught TypeError: Cannot read property '$container' of undefined
    at Object.renderNotificationsGrid (sqleditor.js?ver=41500:1)
    at n.render (sqleditor.js?ver=41500:1)
    at K.start (sqleditor.js?ver=41500:1)
    at 6916768?is_query_tool=true&sgid=2&sid=5&server_type=pg&did=139984501:473
    at Object.execCb (require.min.js?ver=41500:38)
    at Z.check (require.min.js?ver=41500:27)
    at Z.<anonymous> (require.min.js?ver=41500:32)
    at require.min.js?ver=41500:17
    at require.min.js?ver=41500:32
    at v (require.min.js?ver=41500:16)
</code></pre>

I'm not sure how to test in a different browser.

**Comment by dpage** [comment]
Issue closed on Redmine.
