### ISSUE TITLE
pgAdmin Process Watcher not displaying popup window (RM #5012)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3183]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5012***
*Originally created by **Harry Clarke** at 2019-12-12 20:00:17 UTC.*

Running pgAdmin version 4.16 in Firefox under Microsoft Windows 10 = 64 bit

When executing commands such as Restore/Backup/Maintenance the pop-up window does not display. PgAdmin reports the job has been started, and the process can be seen running in the Dashboard. Examination of the pgAdmin Log shows when executing Maintenance

2019-12-12 19:48:17,884: ERROR	flask.app:	a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\misc\bgprocess\processes.py", line 589, in list
    IS_PY2 and hasattr(p.desc, 'encode') else loads(p.desc)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\misc\bgprocess\__init__.py", line 61, in index
    return make_response(response=BatchProcess.list())
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\misc\bgprocess\processes.py", line 595, in list
    IS_PY2 and hasattr(p.desc, 'encode') else loads(p.desc)
TypeError: a bytes-like object is required, not 'str'

History
1) PostgreSQL uninstalled from PC
2) postgreSQL version 12 (latest) and PostGIS installed
3) pgAdmin version 4.16 installed
4) Restored Globals iand database using Restore in pgAdmin - no popup window appeared
5) Checked running processes until restore was complete
6) Checked that database had restored OK by reading a spatial views in QGIS
7) restarted computer
8) reset layout in pgAdmin, and checked settings
9) Executed Maintenance to see if popup window would work (didn't)

**Comment by dpage** [comment]
Issue closed on Redmine.
