### ISSUE TITLE
Big gile log (RM #5014)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3185]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5014***
*Originally created by **Piotr Wlodarczyk** at 2019-12-13 23:55:45 UTC.*

Hi,

after install version 4.16 log files has started grow up (up to 4 GB in 6 hours). I found, that in log they are a lot of repeated logs, FE:

<pre>
2019-04-04 20:34:11,151: ERROR  pgadmin:        connection already closed
Traceback (most recent call last):
  File "D:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "D:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\tools\sqleditor\__init__.py", line 1513, in query_tool_status
    conn.check_notifies(True)
  File "D:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\utils\driver\psycopg2\connection.py", line 1828, in check_notifies
    self.conn.poll()
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
