### ISSUE TITLE
Container 4.16 not starting (RM #5015)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3186]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5015***
*Originally created by **John admin** at 2019-12-14 07:49:13 UTC.*

Hello

We are using the *:latest* container which stopped working with the update to *:4.16*.

When fixing the version to *:4.15* the container will start, otherwise this error occurs:

<pre>
[2019-12-14 07:39:08 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-12-14 07:39:08 +0000] [1] [INFO] Listening at: http://[::]:8080 (1)
[2019-12-14 07:39:08 +0000] [1] [INFO] Using worker: threads
[2019-12-14 07:39:08 +0000] [20] [INFO] Booting worker with pid: 20
[2019-12-14 07:39:09 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
[2019-12-14 07:39:09 +0000] [20] [INFO] Worker exiting (pid: 20)
WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
[2019-12-14 07:39:09 +0000] [1] [INFO] Shutting down: Master
[2019-12-14 07:39:09 +0000] [1] [INFO] Reason: Worker failed to boot.
</pre>

We are using Docker *19.03.2* and this is what the *docker-compose.yml* looks like:

<pre><code class="yaml">
version: '3.7'

services:
  app:
    image: dpage/pgadmin4:latest
    volumes:
      - ./data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=john.doe@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=p@$$w0rT
      - PGADMIN_LISTEN_PORT=8080
    networks:
      - default
    ports:
      - 8080:8080
    restart: on-failure
</code></pre>

I think it will only be a problem on an existing *4.15* installation / configuration.

Hope anyone can help me with this.

**Comment by dpage** [comment]
Issue closed on Redmine.
