### ISSUE TITLE
After upgrade image docker container not start (RM #5016)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3187]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5016***
*Originally created by **Samuele Zanon** at 2019-12-16 09:37:51 UTC.*

I run pgadmin 4 with docker compose. After upgrade to last image pgadmin4 not start with this log:

<pre>
pgadmin4_1  | WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
pgadmin4_1  | Traceback (most recent call last):
pgadmin4_1  |   File "run_pgadmin.py", line 4, in <module>
pgadmin4_1  |     from pgAdmin4 import app
pgadmin4_1  |   File "/pgadmin4/pgAdmin4.py", line 109, in <module>
pgadmin4_1  |     app = create_app()
pgadmin4_1  |   File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
pgadmin4_1  |     create_app_data_directory(config)
pgadmin4_1  |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
pgadmin4_1  |     _create_directory_if_not_exists(config.SESSION_DB_PATH)
pgadmin4_1  |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
pgadmin4_1  |     os.mkdir(_path)
pgadmin4_1  | PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [1] [INFO] Starting gunicorn 19.9.0
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [1] [INFO] Using worker: threads
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [19] [INFO] Booting worker with pid: 19
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [19] [ERROR] Exception in worker process
pgadmin4_1  | Traceback (most recent call last):
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
pgadmin4_1  |     worker.init_process()
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
pgadmin4_1  |     super(ThreadWorker, self).init_process()
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
pgadmin4_1  |     self.load_wsgi()
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
pgadmin4_1  |     self.wsgi = self.app.wsgi()
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
pgadmin4_1  |     self.callable = self.load()
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
pgadmin4_1  |     return self.load_wsgiapp()
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
pgadmin4_1  |     return util.import_app(self.app_uri)
pgadmin4_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
pgadmin4_1  |     __import__(module)
pgadmin4_1  |   File "/pgadmin4/run_pgadmin.py", line 4, in <module>
pgadmin4_1  |     from pgAdmin4 import app
pgadmin4_1  |   File "/pgadmin4/pgAdmin4.py", line 109, in <module>
pgadmin4_1  |     app = create_app()
pgadmin4_1  |   File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
pgadmin4_1  |     create_app_data_directory(config)
pgadmin4_1  |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
pgadmin4_1  |     _create_directory_if_not_exists(config.SESSION_DB_PATH)
pgadmin4_1  |   File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
pgadmin4_1  |     os.mkdir(_path)
pgadmin4_1  | PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [19] [INFO] Worker exiting (pid: 19)
pgadmin4_1  | WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [1] [INFO] Shutting down: Master
pgadmin4_1  | [2019-12-16 09:35:46 +0000] [1] [INFO] Reason: Worker failed to boot.
</pre>

I have also deleted session folder and changed permissions to my user but I get the same error

**Comment by dpage** [comment]
Issue closed on Redmine.
