### ISSUE TITLE
Error retrieving data from server  INTERNAL SERVER ERROR  (RM #5057)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3214]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5057***
*Originally created by **Eduardo Alvarado** at 2020-01-02 22:13:40 UTC.*

I have this issue with my database, doesn't work with my localhost configuration (postgres 12) but for my development db server is working without problems (postgres 11) .
Probably is because of the postgres version, also i use DataGrip and everything is ok. I saw the bug on postgresql community reports but they say that's a bug from the external application (PgAdmin)
here is the link: https://www.postgresql.org/message-id/CAKFQuwasSu4AMWan5_EJzpSE14WCc%2B4cm4%2BJ6%3DHwzBZdxsSx_w%40mail.gmail.com

The pgadmin logs show me this:

----------------------------------------------------------------------------------------------------------------

2020-01-02 15:50:25,504: ERROR	pgadmin:	string indices must be integers
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 259, in dispatch_request
    return method(*args, **kwargs)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/utils.py", line 154, in wrap
    return f(*args, **kwargs)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/__init__.py", line 1263, in dependents
    return BaseTableView.get_table_dependents(self, tid)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/utils.py", line 723, in get_table_dependents
    self.conn, tid
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 439, in get_dependents
    dependents = self.__fetch_dependency(conn, query)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 490, in __fetch_dependency
    for row in result['rows']:
TypeError: string indices must be integers

----------------------------------------------------------------------------------------------------------------

**Comment by dpage** [comment]
Issue closed on Redmine.
