### ISSUE TITLE
pgadmin4 server broken with shutdown server (RM #5069)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3225]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5069***
*Originally created by **Fahar Abbas** at 2020-01-07 11:49:28 UTC.*

Build:
pgadmin4 4.17:

1. Install pgadmin4 runtime
2. Shutdown pgadmin4 server
3. pgadmin4 server going to wait state:

Following log dis
2020-01-07 03:28:48,076: ERROR	flask.app:	Not running with the Werkzeug Server
Traceback (most recent call last):
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/misc/__init__.py", line 161, in shutdown
    raise RuntimeError('Not running with the Werkzeug Server')
RuntimeError: Not running with the Werkzeug Server
faharabbas15@fahars-Mac ~ %

**Comment by dpage** [comment]
Issue closed on Redmine.
