### ISSUE TITLE
 invalid literal for int() with base 10: 'None' (RM #5070)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3226]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5070***
*Originally created by **Naga Raj** at 2020-01-07 18:26:47 UTC.*

Throwing an error " invalid literal for int() with base 10: 'None'" while trying to connect DB in latest version pgAdmin 

Version
4.16

2020-01-07 10:00:29,870: ERROR flask.app: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request

rv = self.dispatch_request()

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view

return self.dispatch_request(*args, **kwargs)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 311, in dispatch_request

return method(*args, **kwargs)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/__init__.py", line 976, in connect_status

recovery_state(conn, manager.version)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/__init__.py", line 53, in recovery_state

"connect/sql/#{0}#/check_recovery.sql".format(postgres_version))

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template

return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template

return self.get_template(template_name_or_list, parent, globals)

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template

return self._load_template(name, self.make_globals(globals))

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template

template = self.loader.load(self, name, globals)

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load

source, filename, uptodate = self.get_source(environment, name)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/versioned_template_loader.py", line 15, in get_source

specified_version_number, exists = parse_version(template)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/versioned_template_loader.py", line 49, in parse_version

return int(version), True

ValueError: invalid literal for int() with base 10: 'None'

2020-01-07 10:00:29,960: ERROR flask.app: invalid literal for int() with base 10: 'None'

Traceback (most recent call last):

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request

rv = self.dispatch_request()

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view

return self.dispatch_request(*args, **kwargs)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/utils.py", line 311, in dispatch_request

return method(*args, **kwargs)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/__init__.py", line 1160, in connect

recovery_state(conn, manager.version)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/__init__.py", line 53, in recovery_state

"connect/sql/#{0}#/check_recovery.sql".format(postgres_version))

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template

return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template

return self.get_template(template_name_or_list, parent, globals)

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template

return self._load_template(name, self.make_globals(globals))

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template

template = self.loader.load(self, name, globals)

File "/Applications/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load

source, filename, uptodate = self.get_source(environment, name)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/versioned_template_loader.py", line 15, in get_source

specified_version_number, exists = parse_version(template)

File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/versioned_template_loader.py", line 49, in parse_version

return int(version), True

ValueError: invalid literal for int() with base 10: 'None'

**Comment by dpage** [comment]
Issue closed on Redmine.
