### ISSUE TITLE
PGadmin V4.17 - Can not create select, update scripts for table “Error message” error fetching SQl for script: 'attname' (RM #5129)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3272]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5129***
*Originally created by **Kevin Andriessens** at 2020-01-28 13:49:30 UTC.*

I am running Pgadmin V4.17. 
When I try to create a select or update sql statement for a table (with the right click on table Scripts), I got an Error window with the text "Error message" and with the caption text :Error fetching SQL for script 'attname'. 
The error appears on all PG databases.

<pre><code class="text">
Version          4.17
Copyright        Copyright (C) 2013 - 2020, The pgAdmin Development Team
Python Version   3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
Flask Version    1.0.2
Application Mode Desktop
Current User     pgadmin4@pgadmin.org
</code></pre>

<pre><code class="text">
ERROR flask.app: 'attname' Traceback (most recent call last): File "C:/app/pgAdmin4/v4/venv/Lib/site-packages\flask\app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "C:/app/pgAdmin4/v4/venv/Lib/site-packages\flask\app.py", line 1799, in dispatch_request return self.view_functionsrule.endpoint File "C:/app/pgAdmin4/v4/venv/Lib/site-packages\flask\views.py", line 88, in view return self.dispatch_request(*args, **kwargs) File "C:\app\pgAdmin4\v4\web\pgadmin\browser\utils.py", line 311, in dispatch_request return method(*args, **kwargs) File "C:\app\pgAdmin4\v4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables\utils.py", line 141, in wrap return f(*args, **kwargs) File "C:\app\pgAdmin4\v4\web\pgadmin\browser\server_groups\servers\databases\schemas\tables__init__.py", line 1310, in select_sql columns.append(self.qtIdent(self.conn, c['attname'])) KeyError: 'attname'*
</code></pre>

When creating the select statement myself, it works fine.

**Comment by dpage** [comment]
Issue closed on Redmine.
