### ISSUE TITLE
container image in docker.io/dpage/pgadmin4 fails to run starting with 4.16 tag (RM #5152)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3290]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5152***
*Originally created by **Basil Eric Rabi** at 2020-02-05 15:16:24 UTC.*

The image docker.io/dpage/pgadmin4:4.15 works great for me. However, staring with docker.io/dpage/pgadmin4:4.16 up to docker.io/dpage/pgadmin4:latest (2020-02-05 23:15), the following is shown:

WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
Traceback (most recent call last):
  File "run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
[2020-02-05 15:07:25 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-02-05 15:07:25 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2020-02-05 15:07:25 +0000] [1] [INFO] Using worker: threads
[2020-02-05 15:07:25 +0000] [15] [INFO] Booting worker with pid: 15
[2020-02-05 15:07:26 +0000] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 244, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
[2020-02-05 15:07:26 +0000] [15] [INFO] Worker exiting (pid: 15)
WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
[2020-02-05 15:07:26 +0000] [1] [INFO] Shutting down: Master
[2020-02-05 15:07:26 +0000] [1] [INFO] Reason: Worker failed to boot.

I'm using podman in fedora 31, not docker.

**Comment by dpage** [comment]
Issue closed on Redmine.
