### ISSUE TITLE
Unable to launch pgadmin4 due  to older Flask-SQLAlchemy module (RM #5214)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3337]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5214***
*Originally created by **Fahar Abbas** at 2020-02-24 09:17:07 UTC.*

Platform:
Windows 64

commit 29c236c33d05d07b1d8bce78f60a98cae684a676

C:\Projects\pgadmin4\web>python pgAdmin4.py
Traceback (most recent call last):
 File "pgAdmin4.py", line 40, in <module>
  import config
 File "C:\Projects\pgadmin4\web\config.py", line 30, in <module>
  from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
 File "C:\Projects\pgadmin4\web\pgadmin\__init__.py", line 31, in <module>
  from pgadmin.model import db, Role, Server, ServerGroup, \
 File "C:\Projects\pgadmin4\web\pgadmin\model\__init__.py", line 22, in <module>
  from flask_sqlalchemy import SQLAlchemy
 File "C:\Projects\venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 39, in <module>
  _timer = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by dpage** [comment]
Issue closed on Redmine.
