### ISSUE TITLE
pgAdmin4 does not start with Python2 (RM #5279)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3375]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5279***
*Originally created by **Murtuza Zabuawala** at 2020-03-20 07:17:28 UTC.*

After latest pull pgAdmin4 does not start when used with Python2 due to below error

(venv2_pem) murtuza@ubuntu:~/projects/pgadmin4/web (master)$ python pgAdmin4.py 
Traceback (most recent call last):
  File "pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/__init__.py", line 610, in create_app
    app.register_blueprint(module)
  File "/home/murtuza/projects/venv2_pem/local/lib/python2.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/murtuza/projects/venv2_pem/local/lib/python2.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/utils/__init__.py", line 70, in register
    app.register_blueprint(module)
  File "/home/murtuza/projects/venv2_pem/local/lib/python2.7/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/murtuza/projects/venv2_pem/local/lib/python2.7/site-packages/flask/app.py", line 1116, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/utils/__init__.py", line 63, in register
    self.submodules = list(app.find_submodules(self.import_name))
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/__init__.py", line 73, in find_submodules
    module = import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 31, in <module>
    from pgadmin.tools.schema_diff.node_registry import SchemaDiffRegistry
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/tools/schema_diff/__init__.py", line 571
SyntaxError: Non-ASCII character '\xc2' in file /home/murtuza/projects/pgadmin4/web/pgadmin/tools/schema_diff/__init__.py on line 571, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by dpage** [comment]
Issue closed on Redmine.
