### ISSUE TITLE
Problem with export connection from PGADMIN v4.20 (RM #5346)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3431]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5346***
*Originally created by **Daro Chm** at 2020-04-02 13:26:25 UTC.*

Platform Windows
Python 3.8.2
pip install -r requirements.txt 
python setup.py --dump-servers serwer.json --user pgadmin4@pgadmin.org

Traceback (most recent call last):
  File "setup.py", line 409, in <module>
    dump_servers(args)
  File "setup.py", line 63, in dump_servers
    app = create_app()
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\__init__.py", line 608, in create_app
    for module in app.find_submodules('pgadmin'):
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\__init__.py", line 73, in find_submodules
    module = import_module(module_name)
  File "C:\Users\dchmura\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\pgAdmin 4\v4\web\pgadmin\browser\__init__.py", line 32, in <module>
    from flask_security.views import _security, _commit, default_render_json, _ctx
ImportError: cannot import name 'default_render_json' from 'flask_security.views' (C:\Users\....\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_security\views.py)

**Comment by dpage** [comment]
Issue closed on Redmine.
