### ISSUE TITLE
Docker image fails with "cannot import name '_render_json' from 'flask_security.views'" (RM #5355)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3439]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5355***
*Originally created by **Bardi Harborow** at 2020-04-06 01:32:03 UTC.*

The Docker image fails from 4.19 forwards with the following error. 4.18 works as expected.

<pre><code class="text">
$ docker run --rm --name postgres-admin --mount type=tmpfs,destination=/tmp/,tmpfs-mode=1700 --tmpfs /var/log/pgadmin/:rw,mode=1700,uid=5050,gid=5050 --mount type=bind,source=/etc/container/postgres-admin/,destination=/pgadmin4/ dpage/pgadmin4:4.19
NOTE: Configuring authentication for SERVER mode.

Traceback (most recent call last):
  File "run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 608, in create_app
    for module in app.find_submodules('pgadmin'):
  File "/pgadmin4/pgadmin/__init__.py", line 73, in find_submodules
    module = import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/pgadmin4/pgadmin/browser/__init__.py", line 32, in <module>
    from flask_security.views import _security, _commit, _render_json, _ctx
ImportError: cannot import name '_render_json' from 'flask_security.views' (/usr/local/lib/python3.7/site-packages/flask_security/views.py)
[2020-04-06 01:23:12 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-04-06 01:23:12 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2020-04-06 01:23:12 +0000] [1] [INFO] Using worker: threads
[2020-04-06 01:23:12 +0000] [81] [INFO] Booting worker with pid: 81
[2020-04-06 01:23:12 +0000] [81] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 608, in create_app
    for module in app.find_submodules('pgadmin'):
  File "/pgadmin4/pgadmin/__init__.py", line 73, in find_submodules
    module = import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/pgadmin4/pgadmin/browser/__init__.py", line 32, in <module>
    from flask_security.views import _security, _commit, _render_json, _ctx
ImportError: cannot import name '_render_json' from 'flask_security.views' (/usr/local/lib/python3.7/site-packages/flask_security/views.py)
</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
