### ISSUE TITLE
User can not launch pgadmin4 on Snapshot builds on MAC OS X only (RM #5386)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3457]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5386***
*Originally created by **Fahar Abbas** at 2020-04-13 08:04:09 UTC.*

Build:
13-April-2020:

1. Launch pgadmin4 on MAC OS X.
2. Error displayed

Traceback (most recent call last):
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/__init__.py", line 401, in create_app
    authenticate.init_app(app)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/authenticate/__init__.py", line 154, in init_app
    AuthSourceRegistry.load_auth_sources()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/authenticate/registry.py", line 65, in load_auth_sources
    module = import_module(module_name)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/authenticate/ldap.py", line 14, in <module>
    from ldap3 import Connection, Server, Tls, ALL, ALL_ATTRIBUTES
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/ldap3/core/connection.py", line 38, in <module>
    from ..extend import ExtendedOperationsRoot
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/ldap3/extend/__init__.py", line 29, in <module>
    from .microsoft.dirSync import DirSync
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/ldap3/extend/microsoft/dirSync.py", line 27, in <module>
    from ...protocol.microsoft import dir_sync_control, extended_dn_control, show_deleted_control
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages/ldap3/protocol/microsoft.py", line 26, in <module>
    import ctypes
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/ctypes/__init__.py", line 551, in <module>
    _reset_cache()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError

**Comment by dpage** [comment]
Issue closed on Redmine.
