### ISSUE TITLE
Progress windows not visible (RM #5394)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3461]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5394***
*Originally created by **Ralf Kraudelt** at 2020-04-14 11:15:51 UTC.*

Hi,

I use CentOS 7.7.1908 and pgAdmin4 4.20, installed from official repositories. The progress windows of restore/backup/maintenance are not visible anymore since pgAdmin4 4.19 (switch to Python 3?). See the last two images here: https://www.pgadmin.org/docs/pgadmin4/4.20/backup_dialog.html
I did a fresh install, it's not an updated earlier version of pgAdmin4. I only use the preferences database from 4.18.

Apache error log says:
<pre>
2020-04-14 12:37:06,867: ERROR  flask.app:      a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/misc/bgprocess/processes.py", line 608, in list
    IS_PY2 and hasattr(p.desc, 'encode') else loads(p.desc)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/misc/bgprocess/__init__.py", line 61, in index
    return make_response(response=BatchProcess.list())
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/misc/bgprocess/processes.py", line 614, in list
    IS_PY2 and hasattr(p.desc, 'encode') else loads(p.desc)
TypeError: a bytes-like object is required, not 'str'
</pre>

The error message is the same for all operations restore/backup/maintenance.

Regards,
Ralf

**Comment by dpage** [comment]
Issue closed on Redmine.
