### ISSUE TITLE
Export Error (RM #5407)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3473]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5407***
*Originally created by **Michael Benjamin** at 2020-04-16 15:40:31 UTC.*

In pgadmin 4.19 (Mac OS Catalina 10.15.4) I get the following error when I try to export the a table file to csv: "expected str, bytes or os.PathLike object, not NoneType". 

Here is the log output:

2020-04-07 15:08:44,503: ERROR flask.app: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
File "/Library/PostgreSQL/12/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/import_export/__init__.py", line 323, in create_import_export_job
p.start()
File "/Library/PostgreSQL/12/pgAdmin 4.app/Contents/Resources/web/pgadmin/misc/bgprocess/processes.py", line 406, in start
preexec_fn=preexec_function, env=env
File "/Library/PostgreSQL/12/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/subprocess.py", line 775, in __init__
restore_signals, start_new_session)
File "/Library/PostgreSQL/12/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/subprocess.py", line 1433, in _execute_child
env_list.append(k + b'=' + os.fsencode(v))
File "/Library/PostgreSQL/12/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/os.py", line 809, in fsencode
filename = fspath(filename) # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

I uninstalled and reinstalled pgadmin and still got the same error.

**Comment by dpage** [comment]
Issue closed on Redmine.
