### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2._psycopg' on startup (RM #5408)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3474]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5408***
*Originally created by **Richard Ayotte** at 2020-04-16 16:04:35 UTC.*

Installed pgadmin4 (4.18-1.pgdg+1) from the apt repo on a Debian Sid system

Running the app logs the following error:

Traceback (most recent call last):
  File "/usr/share/pgadmin4/web/pgAdmin4.py", line 109, in <module>
    app = create_app()
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 400, in create_app
    driver.init_app(app)
  File "/usr/share/pgadmin4/web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/usr/share/pgadmin4/web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/pgadmin4/web/pgadmin/utils/driver/psycopg2/__init__.py", line 19, in <module>
    import psycopg2
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'

**Comment by dpage** [comment]
Issue closed on Redmine.
