### ISSUE TITLE
[LDAP configuration settings] pgadmin4.21 LDAP authentication problems (RM #5487)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3544]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5487***
*Originally created by **Maciej Słota** at 2020-05-06 12:18:09 UTC.*

Hello, I'm trying to create LDAP authentication (OpenLDAP) to access pgadmin4. Installation on CentOS 7 using yum. In config_distro.py (changed values, structure the same):

LDAP_BASE_DN = 'ou=example,dc=xxx,dc=yyy'
LDAP_USERNAME_ATTRIBUTE = 'uid'
LDAP_SEARCH_FILTER = '(&(uid=*)(accountStatus=active))'

Provided uid starts with lowercase letter, followed by comibnation of numbers and letter, something like: a9c00123

When using wrong password for example everything is fine - pgadmin4.log gives information about invalid credentials, message about LDAP Bind error appears on web interface. However, when using good login/password combination following error occurs:

2020-05-06 07:42:10,526: ERROR  flask.app:      attribute type not present
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/authenticate/__init__.py", line 54, in login
    status, msg = auth_obj.authenticate()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/authenticate/__init__.py", line 117, in authenticate
    status, msg = source.authenticate(self.form)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/authenticate/ldap.py", line 49, in authenticate
    status, user_email = self.search_ldap_user()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/authenticate/ldap.py", line 170, in search_ldap_user
    attributes=ALL_ATTRIBUTES
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 735, in search
    search_base = safe_dn(search_base)
  File "/usr/lib/python3.6/site-packages/ldap3/utils/dn.py", line 351, in safe_dn
    for component in parse_dn(dn, escape=True):
  File "/usr/lib/python3.6/site-packages/ldap3/utils/dn.py", line 315, in parse_dn
    if not _validate_attribute_type(attribute_type):
  File "/usr/lib/python3.6/site-packages/ldap3/utils/dn.py", line 172, in _validate_attribute_type
    raise LDAPInvalidDnError('attribute type not present')
ldap3.core.exceptions.LDAPInvalidDnError: attribute type not present
(END)

After commenting lines 171 and 172 in /usr/lib/python3.6/site-packages/ldap3/utils/dn.py it goes further and in the end: IndexError: string index out of range

I was trying to modify search_filters, use search_scope/search_base_dn, but in the end nothing worked.
Any help?

**Comment by dpage** [comment]
Issue closed on Redmine.
