### ISSUE TITLE
Any help getting " 400 Bad Request: The CSRF tokens do not match" (RM #5513)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3566]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5513***
*Originally created by **niteen kole** at 2020-05-12 18:58:29 UTC.*

Latest pgadmin.

PGADMIN4 is behind Azure application gateway and backend running on AKS.

2020-05-12 18:55:38,552: ERROR  flask.app:      400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 256, in protect
    validate_csrf(self._get_csrf_token())
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 106, in validate_csrf
    raise ValidationError('The CSRF tokens do not match.')
wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 224, in csrf_protect
    self.protect()
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 259, in protect
    self._error_response(e.args[0])
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/csrf.py", line 302, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.

**Comment by dpage** [comment]
Issue closed on Redmine.
