### ISSUE TITLE
pgadmin4 error after installation (RM #5524)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3576]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5524***
*Originally created by **Dmitry Dmitry** at 2020-05-14 10:42:40 UTC.*

I have installed pgadmin4 on Ubuntu 16.04

After installation I try to access pgadmin4 webpage via webbrowser or simply curl:
 curl 127.0.0.1:5050

and get folowing:
{"data":null,"success":0,"errormsg":"'Request' object has no attribute 'is_json'","result":null,"info":""}

More detailed errors while running 

python3.5 /usr/share/pgadmin4/web/pgAdmin4.py

Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2020-05-14 13:22:21,663: ERROR  pgadmin:        'Request' object has no attribute 'is_json'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/lib/python3/dist-packages/flask_principal.py", line 477, in _on_before_request
    identity = loader()
  File "/usr/lib/python3/dist-packages/flask_security/core.py", line 515, in _identity_loader
    if not isinstance(current_user._get_current_object(), AnonymousUserMixin):
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/lib/python3/dist-packages/flask_login/login_manager.py", line 313, in _load_user
    return self._load_from_request(request)
  File "/usr/lib/python3/dist-packages/flask_login/login_manager.py", line 370, in _load_from_request
    user = self.request_callback(request)
  File "/usr/lib/python3/dist-packages/flask_security/core.py", line 475, in _request_loader
    if request.is_json:
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_json'
2020-05-14 13:22:36,033: ERROR  pgadmin:        'Request' object has no attribute 'is_json'

**Comment by dpage** [comment]
Issue closed on Redmine.
