### ISSUE TITLE
4.22 Bad Request The CSRF tokens do not match. if PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False (RM #5570)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3611]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5570***
*Originally created by **Богдан Помазан** at 2020-05-30 17:23:41 UTC.*

After switching to 4.22, this error began to appear after authorization

<pre>
172.68.245.13 - - [30/May/2020:17:15:38 +0000] "POST /settings/store HTTP/1.1" 400 145 "https://pgadmin4.pomazan.xyz/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"

172.68.244.114 - - [30/May/2020:17:15:38 +0000] "GET /preferences/get_all HTTP/1.1" 400 145 "https://pgadmin4.pomazan.xyz/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"

2020-05-30 17:15:39,426: ERROR	flask.app:	400 Bad Request: The CSRF tokens do not match.

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 256, in protect

    validate_csrf(self._get_csrf_token())

  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 106, in validate_csrf

    raise ValidationError('The CSRF tokens do not match.')

wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1811, in full_dispatch_request

    rv = self.preprocess_request()

  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2087, in preprocess_request

    rv = func()

  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 224, in csrf_protect

    self.protect()

  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 259, in protect

    self._error_response(e.args[0])

  File "/usr/local/lib/python3.8/site-packages/flask_wtf/csrf.py", line 302, in _error_response

    raise CSRFError(reason)

flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.

172.68.245.13 - - [30/May/2020:17:15:39 +0000] "GET /misc/bgprocess/?_=1590858937273 HTTP/1.1" 400 145 "https://pgadmin4.pomazan.xyz/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"

/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used

  return io.open(fd, *args, **kwargs)

[2020-05-30 17:16:28 +0000] [1] [INFO] Handling signal: term
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
