### ISSUE TITLE
ERROR: Attempting to Install the pgAdmin 4 Web Interface on CentOS 7 (RM #5589)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3627]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5589***
*Originally created by **Freddie Burgess** at 2020-06-06 01:14:46 UTC.*

[root@pgdb-0]# uname -a
Linux pgdb-0 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@pgdb-0]# python /usr/lib/python3.6/site-packages/pgadmin4-web/setup.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/setup.py", line 409, in <module>
    setup_db()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/setup.py", line 343, in setup_db
    app = create_app()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/__init__.py", line 397, in create_app
    driver.init_app(app)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/utils/driver/psycopg2/__init__.py", line 27, in <module>
    from .connection import Connection
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/utils/driver/psycopg2/connection.py", line 38, in <module>
    from pgadmin.utils import csv
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/utils/csv.py", line 651, in <module>
    register_dialect("excel", excel)
  File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/utils/csv.py", line 486, in register_dialect
    raise TypeError('"name" must be a string')
TypeError: "name" must be a string

**Comment by dpage** [comment]
Issue closed on Redmine.
