### ISSUE TITLE
pgadmin4-apache2 on Debian 10 x64 can not update and install!!! (RM #5611)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3645]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5611***
*Originally created by **Navid Taheri** at 2020-06-17 03:30:36 UTC.*

I get error everytime I'll update and install pgadmin4-apache2 on my laptop.

<pre><code class="python">
Setting up pgadmin4-apache2 (4.21-1.pgdg100+1) ...
Traceback (most recent call last):
  File "setup.py", line 413, in <module>
    setup_db()
  File "setup.py", line 347, in setup_db
    app = create_app()
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 604, in create_app
    for module in app.find_submodules('pgadmin'):
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 73, in find_submodules
    module = import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/pgadmin4/web/pgadmin/browser/__init__.py", line 32, in <module>
    from flask_security.views import _security, _commit, default_render_json, _ctx
ImportError: cannot import name 'default_render_json' from 'flask_security.views' (/usr/local/lib/python3.7/dist-packages/flask_security/views.py)
dpkg: error processing package pgadmin4-apache2 (--configure):
 installed pgadmin4-apache2 package post-installation script subprocess returned error exit status 1

</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
