### ISSUE TITLE
pgadmin4 on Azure AKS unstable (RM #5659)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3686]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5659***
*Originally created by **niteen kole** at 2020-07-07 23:48:54 UTC.*

We have pgadmin4 on Azure AKS,kind of unstable pod runs for sometime and then becomes unresponsive.

below error we see in logs.
[2020-07-07 23:35:24 +0000] [90] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 274, in handle
    req = six.next(conn.parser)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
OSError: [Errno 0] Error
^C

**Comment by dpage** [comment]
Issue closed on Redmine.
