### ISSUE TITLE
Schema diff: Getting error while fetching schemas (RM #5673)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3696]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5673***
*Originally created by **Murtuza Zabuawala** at 2020-07-14 14:28:31 UTC.*

Please refer trace & screenshot.

<pre><code class="python">
(venv3_pg) murtuza@ubuntu:~/projects/pgadmin4/web (master)$ python pgAdmin4.py 
Starting pgAdmin 4. Please navigate to http://0.0.0.0:5051 in your browser.
 * Serving Flask app "pgadmin" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-07-14 07:17:56,975: ERROR	flask.app:	Connection (id #None) lost for the server (#2) on database (acceptance_test_db20821)
Traceback (most recent call last):
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/tools/schema_diff/__init__.py", line 414, in schemas
    response = view.nodes(gid=server.servergroup_id, sid=sid, did=did)
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/__init__.py", line 156, in wrap
    return f(*args, **kwargs)
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/schemas/__init__.py", line 446, in nodes
    status, rset = self.conn.execute_2darray(SQL)
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 1071, in execute_2darray
    status, cur = self.__cursor()
  File "/home/murtuza/projects/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 536, in __cursor
    None if self.conn_id[0:3] == u'DB:' else self.conn_id[5:]
pgadmin.utils.exception.ConnectionLost: Connection (id #None) lost for the server (#2) on database (acceptance_test_db20821)

</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
