### ISSUE TITLE
after login we get "malformed pbkdf2_sha512 hash (checksum must be exactly 64 bytes)" as json result page  (RM #5738)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3740]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5738***
*Originally created by **Ignacio J. Ortega Lopera** at 2020-08-12 14:45:04 UTC.*

After try a correct or incorrect password we only get a json page , with that result  "malformed pbkdf2_sha512 hash (checksum must be exactly 64 bytes)" , stack trace from error_log below

Traceback (most recent call last):
[Wed Aug 12 09:37:33.339593 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1813, in full_dispatch_request
[Wed Aug 12 09:37:33.339595 2020] [:error] [pid 129]     rv = self.dispatch_request()
[Wed Aug 12 09:37:33.339598 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask/app.py", line 1799, in dispatch_request
[Wed Aug 12 09:37:33.339601 2020] [:error] [pid 129]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Aug 12 09:37:33.339604 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_security/decorators.py", line 230, in wrapper
[Wed Aug 12 09:37:33.339606 2020] [:error] [pid 129]     return f(*args, **kwargs)
[Wed Aug 12 09:37:33.339609 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_security/views.py", line 77, in login
[Wed Aug 12 09:37:33.339611 2020] [:error] [pid 129]     if form.validate_on_submit():
[Wed Aug 12 09:37:33.339614 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_wtf/form.py", line 101, in validate_on_submit
[Wed Aug 12 09:37:33.339616 2020] [:error] [pid 129]     return self.is_submitted() and self.validate()
[Wed Aug 12 09:37:33.339619 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_security/forms.py", line 241, in validate
[Wed Aug 12 09:37:33.339622 2020] [:error] [pid 129]     if not verify_and_update_password(self.password.data, self.user):
[Wed Aug 12 09:37:33.339626 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/flask_security/utils.py", line 156, in verify_and_update_password
[Wed Aug 12 09:37:33.339630 2020] [:error] [pid 129]     verified = _pwd_context.verify(get_hmac(password), user.password)
[Wed Aug 12 09:37:33.339634 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/context.py", line 2342, in verify
[Wed Aug 12 09:37:33.339638 2020] [:error] [pid 129]     return record.verify(secret, hash, **kwds)
[Wed Aug 12 09:37:33.339642 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/utils/handlers.py", line 757, in verify
[Wed Aug 12 09:37:33.339646 2020] [:error] [pid 129]     self = cls.from_string(hash, **context)
[Wed Aug 12 09:37:33.339649 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/handlers/pbkdf2.py", line 69, in from_string
[Wed Aug 12 09:37:33.339654 2020] [:error] [pid 129]     return cls(rounds=rounds, salt=salt, checksum=chk)
[Wed Aug 12 09:37:33.339658 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/utils/handlers.py", line 1761, in __init__
[Wed Aug 12 09:37:33.339662 2020] [:error] [pid 129]     super(HasRounds, self).__init__(**kwds)
[Wed Aug 12 09:37:33.339678 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/utils/handlers.py", line 1376, in __init__
[Wed Aug 12 09:37:33.339683 2020] [:error] [pid 129]     super(HasSalt, self).__init__(**kwds)
[Wed Aug 12 09:37:33.339686 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/utils/handlers.py", line 593, in __init__
[Wed Aug 12 09:37:33.339690 2020] [:error] [pid 129]     self.checksum = self._norm_checksum(checksum)
[Wed Aug 12 09:37:33.339694 2020] [:error] [pid 129]   File "/usr/lib/python2.7/site-packages/pgadmin4-web/passlib/utils/handlers.py", line 623, in _norm_checksum
[Wed Aug 12 09:37:33.339698 2020] [:error] [pid 129]     raise exc.ChecksumSizeError(self, raw=raw)
[Wed Aug 12 09:37:33.339701 2020] [:error] [pid 129] ValueError: malformed pbkdf2_sha512 hash (checksum must be exactly 64 bytes)

**Comment by dpage** [comment]
Issue closed on Redmine.
