### ISSUE TITLE
Python error after installed pgadmin4 on CentOS 7 (RM #5766)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3763]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5766***
*Originally created by **Евгений Куница** at 2020-08-23 05:56:34 UTC.*

Installed PGAdmin4 by this guide: https://www.pgadmin.org/download/pgadmin-4-rpm/
After installing, after log in to control panel, added database. When open database give error:
!https://screen.hoster.by/iWCo4_ZF.png!

Out pgadmin log:
2020-08-23 08:42:55,700: ERROR  flask.app:      Failed to execute query (execute_dict) for the server #1- DB:onlyoffice (Query-id: 4747508):
Error Message:ОШИБКА:  отношение "pg_event_trigger" не существует
LINE 56: LEFT JOIN pg_event_trigger evt ON evt.oid=dep.objid
                   ^

2020-08-23 08:42:55,702: ERROR  flask.app:      ОШИБКА:  отношение "pg_event_trigger" не существует
LINE 56: LEFT JOIN pg_event_trigger evt ON evt.oid=dep.objid

2020-08-23 08:42:55,703: ERROR  flask.app:      string indices must be integers
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 202, in wrapped
    return f(self, *args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 1172, in dependents
    self.conn.connected() else []
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 536, in get_dependents
    dependents = self.__fetch_dependency(conn, query)
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 601, in __fetch_dependency
    for row in result['rows']:
TypeError: string indices must be integers

2020-08-23 08:42:55,711: ERROR  flask.app:      Failed to execute query (execute_dict) for the server #1- DB:onlyoffice (Query-id: 8487748):
Error Message:ОШИБКА:  отношение "pg_event_trigger" не существует
LINE 56: LEFT JOIN pg_event_trigger evt ON evt.oid=dep.refobjid

2020-08-23 08:42:55,711: ERROR  flask.app:      ОШИБКА:  отношение "pg_event_trigger" не существует
LINE 56: LEFT JOIN pg_event_trigger evt ON evt.oid=dep.refobjid
                   ^

2020-08-23 08:42:55,711: ERROR  flask.app:      string indices must be integers
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 202, in wrapped
    return f(self, *args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/databases/__init__.py", line 1190, in dependencies
    self.conn.connected() else []
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 482, in get_dependencies
    conn, query, show_system_objects, is_schema_diff)
  File "/usr/pgadmin4/web/pgadmin/browser/utils.py", line 601, in __fetch_dependency
    for row in result['rows']:
TypeError: string indices must be integers

**Comment by dpage** [comment]
Issue closed on Redmine.
