### ISSUE TITLE
pgadmin4 container crashing on OpenShift 3 since version 4.23 (RM #5785)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3781]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5785***
*Originally created by **Aldjinn Dscherid** at 2020-08-28 08:40:01 UTC.*

Hi,
since version 4.23, the Docker container is crashing on OpenShift.

It looks like the problem is caused by getpass.getuser() in line 53 of /pgadmin4/pgadmin/setup/data_directory.py

    # Try to set the permissions on the directory, but don't complain
    # if we can't. This may be the case on a mounted directory, e.g. in
    # OpenShift. We'll still secure the config database anyway.
    if os.name != 'nt':
        try:
            os.chmod(os.path.dirname(config.SQLITE_PATH), 0o700)
        except Exception as e:
            # The flask app isn't setup yet, so we can't use the logger
            print('WARNING: Failed to set ACL on the directory containing the '
                  'configuration database:\n           {}'.format(e))
            print("HINT   : You may need to manually set the permissions on\n"
                  "         {} to allow {} to write to it.".
                  format(os.path.dirname(config.SQLITE_PATH),
                         getpass.getuser()))

Full stacktrace:

/entrypoint.sh: line 8: can't create /pgadmin4/config_distro.py: Permission denied
sudo: you do not exist in the passwd database
[2020-08-28 08:21:22 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-08-28 08:21:22 +0000] [1] [INFO] Listening at: http://[::]:8080 (1)
[2020-08-28 08:21:22 +0000] [1] [INFO] Using worker: threads
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-08-28 08:21:22 +0000] [20] [INFO] Booting worker with pid: 20
[2020-08-28 08:21:22 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 45, in create_app_data_directory
    os.chmod(os.path.dirname(config.SQLITE_PATH), 0o700)
PermissionError: [Errno 1] Operation not permitted: '/var/lib/pgadmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 247, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 53, in create_app_data_directory
    getpass.getuser()))
  File "/usr/local/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1001130000'
[2020-08-28 08:21:22 +0000] [20] [INFO] Worker exiting (pid: 20)
WARNING: Failed to set ACL on the directory containing the configuration database:
           [Errno 1] Operation not permitted: '/var/lib/pgadmin'
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-08-28 08:21:22 +0000] [1] [INFO] Shutting down: Master
[2020-08-28 08:21:22 +0000] [1] [INFO] Reason: Worker failed to boot.

Kind regards,
Aldjinn

**Comment by dpage** [comment]
Issue closed on Redmine.
