### ISSUE TITLE
App crashing at startup du to typo in sshtunnel.py (RM #5850)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3837]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5850***
*Originally created by **Martin Tovmassian** at 2020-09-18 13:53:58 UTC.*

Environment:
- pgAdmin4 (as Python package)
- Python version: 3.9.0a6
- System: Ubuntu 20.04

Issue:
- When I'm launching pgAdmin4 via the _pgadmin4_ command app is crashing with this traceback:
<pre><code class="python">
Traceback (most recent call last):
  File "/home/martin/pgadmin4/bin/pgadmin4", line 6, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/__init__.py", line 419, in create_app
    driver.init_app(app)
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    import_module(module_name)
  File "/home/martin/.pyenv/versions/3.9.0a6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 30, in <module>
    from .server_manager import ServerManager
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/server_manager.py", line 32, in <module>
    from sshtunnel import SSHTunnelForwarder, BaseSSHTunnelForwarderError
  File "/home/martin/pgadmin4/lib/python3.9/site-packages/sshtunnel.py", line 1535
    self.ssh_host_key if self.ssh_host_key else'not checked',
                                              ^
SyntaxError: invalid string prefix

</code></pre>
- Indeed in the https://github.com/pahaz/sshtunnel/blob/master/sshtunnel.py file line 1535 a space is missing between the _else_ keyword and the quote.
- Everything works fine afer editing this typo

**Comment by dpage** [comment]
Issue closed on Redmine.
