### ISSUE TITLE
4.26 docker version getting "ERROR] Socket error processing request. .....TimeoutError: [Errno 110] Operation timed out" and then hangs (RM #5870)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3853]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5870***
*Originally created by **niteen kole** at 2020-09-25 13:39:01 UTC.*

Version
4.26
Copyright
Copyright (C) 2013 - 2020, The pgAdmin Development Team
Python Version
3.8.5 (default, Aug 4 2020, 04:20:04) [GCC 9.2.0]
Flask Version
1.0.2
Application Mode
Server

was working fine for months and suddenly stopped working.
Works fine when we restart and then stops/hangs.

below are the logs.
OSError: [Errno 0] Error
[2020-09-25 13:29:27 +0000] [89] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 274, in handle
    req = six.next(conn.parser)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
TimeoutError: [Errno 110] Operation timed out

running on ubuntu
Linux pgadmin-prod 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dpage** [comment]
Issue closed on Redmine.
