### ISSUE TITLE
plz help....An error occurred initialising the pgAdmin 4 server:  Failed to launch the application server, server thread exiting. (RM #5873)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3855]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5873***
*Originally created by **nipun kumar** at 2020-09-29 07:16:59 UTC.*

Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 58, in <module>
    from http.server import BaseHTTPRequestHandler
  File "/usr/pgadmin4/venv/lib/python3.6/http/server.py", line 90, in <module>
    import email.utils
  File "/usr/pgadmin4/venv/lib/python3.6/email/utils.py", line 40, in <module>
    from email.charset import Charset
ModuleNotFoundError: No module named 'email.charset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 35, in <module>
    import config
  File "/usr/pgadmin4/web/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 19, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/werkzeug/__init__.py", line 15, in <module>
    from .serving import run_simple
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 61, in <module>
    import SocketServer as socketserver
ModuleNotFoundError: No module named 'SocketServer'

**Comment by dpage** [comment]
Issue closed on Redmine.
