### ISSUE TITLE
invalid literal for int() with base 10: '-' (RM #5882)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3861]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5882***
*Originally created by **Antal Rutz** at 2020-10-02 17:37:39 UTC.*

When trying to click on a Materialized View I've got the following error:
<pre>

2020-10-02 19:24:57,860: ERROR	flask.app:	invalid literal for int() with base 10: '-'
Traceback (most recent call last):
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/utils.py", line 313, in dispatch_request
    return method(*args, **kwargs)
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/databases/schemas/views/__init__.py", line 250, in wrap
    return f(*args, **kwargs)
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/databases/schemas/views/__init__.py", line 1514, in dependencies
    dependencies_result = self.get_dependencies(self.conn, vid)
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/utils.py", line 484, in get_dependencies
    dependencies = self.__fetch_dependency(
  File "/home/arutz/virtualenv/pgadmin4/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/utils.py", line 639, in __fetch_dependency
    if int(type_str[1]) > 0:
ValueError: invalid literal for int() with base 10: '-'
</pre>

I figured out that in a SELECT where pg_depend table ie queried the _refobjsubid_ field is '-7' and that's why the int() fails on the second char of type_str.
I have two materialized views but the other doesn't have that problem. Could it be a Postgres bug? I tried to drop and recreate the view, the problem still  persists.
*
PgAdmin 4.26
Postgresql 9.6.19*

**Comment by dpage** [comment]
Issue closed on Redmine.
