### ISSUE TITLE
'ServerManager' object has no attribute 'user_info' (RM #5883)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3862]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5883***
*Originally created by **Ruairidh MacLeod** at 2020-10-04 13:42:12 UTC.*

Hi,

I'm seeing the above error when trying to connect to a local database with a test user. I can connect to the same database with the postgres user without any issue, so I'm thinking this may be an issue with permissions?

I'm running both the postgres database and pgadmin through docker (dpage/pgadmin4:4.26). The full stack trace is:

<pre>
pgadmin    | Traceback (most recent call last):
pgadmin    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
pgadmin    |     rv = self.dispatch_request()
pgadmin    |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request                                                   
pgadmin    |     return self.view_functions[rule.endpoint](**req.view_args)
pgadmin    |   File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 88, in view
pgadmin    |     return self.dispatch_request(*args, **kwargs)
pgadmin    |   File "/pgadmin4/pgadmin/browser/utils.py", line 313, in dispatch_request
pgadmin    |     return method(*args, **kwargs)
pgadmin    |   File "/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 1457, in connect
pgadmin    |     'user': manager.user_info,
pgadmin    | AttributeError: 'ServerManager' object has no attribute 'user_info'
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
