### ISSUE TITLE
Unable to connect to server with logged ldap user (RM #5898)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3873]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5898***
*Originally created by **Marcelo Rômulo Fernandes** at 2020-10-08 23:46:18 UTC.*

Hi,

I cannot save a server using pgadmin4 gui when the logged user is ldap one. It works when I log the admin user.
I'm using pgadmin4 version 4.26 with server mode inside dpage/pgadmin4:latest docker image.
The attached picture shows the error when I press the "ok" button.

I see the following log error when I do it:

<pre>
172.20.0.2 - - [08/Oct/2020:19:46:24 +0000] "POST /browser/server/connect/2/1 HTTP/1.0" 401 1800 "https://pgadmin4.devops.ifrn.edu.br/browser/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
2020-10-08 19:46:30,452: ERROR  flask.app:      free variable 'username' referenced before assignment in enclosing scope
Traceback (most recent call last):
  File "/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 1377, in connect
    status, errmsg = conn.connect(
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 292, in connect
    sslcert=get_complete_file_path(manager.sslcert),
  File "/pgadmin4/pgadmin/utils/__init__.py", line 256, in get_complete_file_path
    storage_dir = get_storage_directory()
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/pgadmin4/pgadmin/utils/paths.py", line 48, in get_storage_directory
    username = _preprocess_username(current_user.username.split('@')[0])
  File "/pgadmin4/pgadmin/utils/paths.py", line 40, in _preprocess_username
    ret_un = 'pga_user_' + username
NameError: free variable 'username' referenced before assignment in enclosing scope
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
