### ISSUE TITLE
Failed to launch the application server, server thread exiting (RM #5902)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3877]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5902***
*Originally created by **Muhammad Bashir Al-Noimi** at 2020-10-11 12:28:12 UTC.*

After installing installing pgAdmin4 using Postgresql repository I get this error:

<pre>
An error occurred initialising the pgAdmin 4 server:Failed to launch the application server, server thread exiting.
</pre>

I tried to run it from the terminal but I get a different error message:

<pre>
$ sudo python3 /usr/share/pgadmin4/web/pgAdmin4.py
[sudo] password for mbnoimi:             
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: duplicate column name: commentThe above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "/usr/share/pgadmin4/web/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/usr/share/pgadmin4/web/pgadmin/__init__.py", line 351, in create_app
    db_upgrade(app)
  File "/usr/share/pgadmin4/web/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/usr/lib/python3/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python3/dist-packages/alembic/command.py", line 279, in upgrade
    script.run_env()
  File "/usr/lib/python3/dist-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3/dist-packages/alembic/util/compat.py", line 174, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/pgadmin4/web/pgadmin/setup/../../migrations/env.py", line 93, in <module>
    run_migrations_online()
  File "/usr/share/pgadmin4/web/pgadmin/setup/../../migrations/env.py", line 86, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python3/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python3/dist-packages/alembic/runtime/migration.py", line 365, in run_migrations
    step.migration_fn(**kw)
  File "/usr/share/pgadmin4/web/migrations/versions/09d53fca90c7_.py", line 40, in upgrade
    db.engine.execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2182, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 976, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1143, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: comment
[SQL: ALTER TABLE server ADD COLUMN comment TEXT(1024)]
(Background on this error at: http://sqlalche.me/e/e3q8)
</pre>

**Some additional logs:**

<pre>
$ cat ~/.config/pgadmin/pgadmin4.conf 
cat: /home/mbnoimi/.config/pgadmin/pgadmin4.conf: No such file or directory

$ cat ~/.profile
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

export GTK_IM_MODULE=ibus
export PATH="$HOME/.local/bin:$PATH"

$ python3 --version
Python 3.8.5

$ python --version
Python 2.7.18
</pre>

*NOTES*
* I already know that there are some similar opened issues but this one a little bit different so I opened it separateness.
* I installed pgAdmin4 (4.25) from the official Postgresql's repository as following:
<pre>
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt update
sudo apt install -y postgresql pgadmin4
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
