### ISSUE TITLE
Incorrect Flask-BabelEx version in requirements for pgAdmin 4.28 (RM #5997)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3950]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5997***
*Originally created by **Dennis Gomer** at 2020-11-12 15:59:00 UTC.*

It looks like the required Flask-BabelEx version didn't get bumped in the requirements for 4.28.

Reproduction:
<pre>
pip3 install flask-babelex==0.9.3
pip3 install pgadmin4 #won't upgrade flask-babelex
pgadmin4
</pre>
Which will fail with this error:
<pre>
Traceback (most recent call last):
  File "/usr/local/bin/pgadmin4", line 7, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgAdmin4.py", line 35, in <module>
    import config
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/__init__.py", line 23, in <module>
    from flask_babelex import Babel, gettext
  File "/usr/local/lib/python3.6/dist-packages/flask_babelex/__init__.py", line 23, in <module>
    from werkzeug import ImmutableDict
ImportError: cannot import name 'ImmutableDict'
</pre>
Upgrading flask-babelex fixes the error:
<pre>
pip3 install --upgrade flask-babelex # gets 0.9.4
pgadmin4
</pre>
which returns the expected setup prompt. You wouldn't see this in clean installs but it will cause issues for upgrades.

**Comment by dpage** [comment]
Issue closed on Redmine.
