### ISSUE TITLE
unable to load web interface after upgrading from 4.26 to 4.28 (RM #6020)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3969]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6020***
*Originally created by **Matt Beary** at 2020-11-18 15:57:08 UTC.*

After updating from 4.26 to 4.28 via Chocolatey on Windows 10:

* on Firefox 83.0 (64-bit), pgAdmin4 just spins at the loading message and doesn't get anywhere.  There are no failed network calls, and I've attached the console output
* on Chrome 87.0.4280.66 (Official Build) (64-bit), I get a 401 error with the body:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>401 Unauthorized</title>
<h1>Unauthorized</h1>
<p>The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.</p>
```

The pgAdmin4 startup log has some garbage being printed to the end, which changes every time I reload it.  The text before that is:
```
2020-11-18 09:32:33: Checking for system tray...
2020-11-18 09:32:33: Starting pgAdmin4 server...
2020-11-18 09:32:33: Creating server object, port:62788, key:520b4ba4-dd2c-433b-baea-08033ec5e3bb, logfile:C:/Users/Matt/AppData/Local/pgadmin4.d41d8cd98f00b204e9800998ecf8427e.log
2020-11-18 09:32:33: Python Path: C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages;C:/Program Files/pgAdmin 4/v4/venv/DLLs;C:/Program Files/pgAdmin 4/v4/venv/Lib
2020-11-18 09:32:33: Python Home: C:/Program Files/pgAdmin 4/v4/venv
2020-11-18 09:32:33: Initializing Python...
2020-11-18 09:32:33: Python initialized.
2020-11-18 09:32:33: Adding new additional path elements
2020-11-18 09:32:33: Redirecting stderr...
2020-11-18 09:32:33: stderr redirected successfully.
2020-11-18 09:32:33: Initializing server...
2020-11-18 09:32:33: Webapp Path: C:/Program Files/pgAdmin 4/v4/web/pgAdmin4.py
2020-11-18 09:32:33: Server initialized, starting server thread...
2020-11-18 09:32:33: Open the application code and run it.
2020-11-18 09:32:33: Set the port number, key and force SERVER_MODE off
2020-11-18 09:32:33: PyRun_SimpleFile launching application server...
2020-11-18 09:32:34: Application Server URL: http://127.0.0.1:62788/?key=520b4ba4-dd2c-433b-baea-08033ec5e3bb
2020-11-18 09:32:34: The server should be up. Attempting to connect and get a response.
2020-11-18 09:32:38: Attempt to connect one more time in case of a long network timeout while looping
2020-11-18 09:32:38: Everything works fine, successfully started pgAdmin4.
```

Nothing is printed to the server log when trying to use Firefox.  Each connection attempt with Chrome gives:
```
2020-11-18 09:51:26,979: ERROR	flask.app:	401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
Traceback (most recent call last):
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Program Files\pgAdmin 4\v4\web\pgadmin\__init__.py", line 676, in before_request
    abort(401)
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\werkzeug\exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\werkzeug\exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.
```

**Comment by dpage** [comment]
Issue closed on Redmine.
