### ISSUE TITLE
"ImportError: DLL load failed while importing _bcrypt: The specified module could not be found"  Message displayed when launch pgadmin4 4.29 on Windows  (RM #6072)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4006]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6072***
*Originally created by **Fahar Abbas** at 2020-12-08 05:36:23 UTC.*

Steps
https://developer.pgadmin.org/builds/2020-12-07-1/

1. Download and install pgadmin4 
2. Error displayed while launching pgadmin4

Traceback (most recent call last):
  File "C:/Program Files/pgAdmin 4/v4/web/pgAdmin4.py", line 86, in <module>
    exec(open(file_quote(setup_py), 'r').read())
  File "<string>", line 449, in <module>
  File "<string>", line 372, in setup_db
  File "C:\Program Files\pgAdmin 4\v4\web\pgadmin\__init__.py", line 430, in create_app
    driver.init_app(app)
  File "C:\Program Files\pgAdmin 4\v4\web\pgadmin\utils\driver\__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "C:\Program Files\pgAdmin 4\v4\web\pgadmin\utils\driver\registry.py", line 88, in load_drivers
    import_module(module_name)
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Program Files\pgAdmin 4\v4\web\pgadmin\utils\driver\psycopg2\__init__.py", line 30, in <module>
    from .server_manager import ServerManager
  File "C:\Program Files\pgAdmin 4\v4\web\pgadmin\utils\driver\psycopg2\server_manager.py", line 32, in <module>
    from sshtunnel import SSHTunnelForwarder, BaseSSHTunnelForwarderError
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\sshtunnel.py", line 25, in <module>
    import paramiko
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\paramiko\transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\paramiko\dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\paramiko\pkey.py", line 31, in <module>
    import bcrypt
  File "C:/Program Files/pgAdmin 4/v4/venv/Lib/site-packages\bcrypt\__init__.py", line 25, in <module>
    from . import _bcrypt
ImportError: DLL load failed while importing _bcrypt: The specified module could not be found.

**Comment by dpage** [comment]
Issue closed on Redmine.
