### ISSUE TITLE
PgAdmin 4 v4.29 (Windows, 64bit) gives Http500 Internal server error (Stacktrace available, AttributeError: 'datetime.timedelta' object has no attribute 'tm_wday') (RM #6173)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4092]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6173***
*Originally created by **Philipp Freyer** at 2021-01-26 10:05:38 UTC.*

This prevents the usage of PgAdmin since this error is returned when launching the PgAdmin UI on http://127.0.0.1:50831/browser/

Log with stacktrace is attached. (Posdsibly twice, the UI is showing an error message when attaching)
Relevant extract:
<pre><code class="python">
2021-01-26 10:12:42,603: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 1858, in process_response
    self.save_session(ctx.session, response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\flask\app.py", line 924, in save_session
    return self.session_interface.save_session(self, session, response)
  File "C:\Program Files (x86)\pgAdmin 4\v3\web\pgadmin\utils\session.py", line 329, in save_session
    expires=cookie_exp, httponly=True, domain=domain
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\wrappers.py", line 1116, in set_cookie
    samesite=samesite
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\http.py", line 1064, in dump_cookie
    expires = cookie_date(expires)
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\http.py", line 786, in cookie_date
    return _dump_date(expires, '-')
  File "C:\Program Files (x86)\pgAdmin 4\v3\venv\Lib\site-packages\werkzeug\http.py", line 766, in _dump_date
    ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')[d.tm_wday],
AttributeError: 'datetime.timedelta' object has no attribute 'tm_wday'
</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
