### ISSUE TITLE
pgAdmin: Syntax error for APP_NAME in docker (RM #6184)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4102]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6184***
*Originally created by **Pedro Voorwinden** at 2021-01-28 08:21:47 UTC.*

I am running into the following error when running a pgAdmin instance locally in Docker, and it causes my docker container to keep restarting over and over:
<pre>
Traceback (most recent call last):
File "/pgadmin4/setup.py", line 31 in <module>
from pgadmin import create_app
File "/pgadmin4/pgadmin/__init__.py", line 26 in <module>
from pgadmin.utils.session import create_session_interface, pga_unauthorised
File "/pgadmin4/pgadmin/utils/session.py", line 26, in <module>
import config
File "/pgadmin4/config.py", line 627, in <module>
from config_distro import *
File "/pgadmin4/config_distro.py", line 5
APP_NAME = Jump into the Brave databases
^
SyntaxError: invalid syntax
</pre>

My docker-compose file:
<pre>
# Database Administration web ui
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - userservice_db
            - quotationservice_db
            - customerservice_db
            - projectservice_db
        restart: always
        ports:
            - '8000:80'
        env_file:
            - variables.pgadmin.env
        volumes:
            - './pgadmin.servers.json:/pgadmin4/servers.json'
</pre>

and my variables.pgadmin.env file:
<pre>
PGADMIN_DEFAULT_EMAIL=admin@email.nl
PGADMIN_DEFAULT_PASSWORD=test
PGADMIN_CONFIG_APP_NAME='Jump into the Brave databases'
</pre>

The 'Getting started' documentation says the following:
>Add the PGADMIN_CONFIG_ prefix to any variable name from config.py and give the value in the format ‘string value’ for strings, True/False for booleans or 123 for numbers. 

The APP_NAME is an existing variable in the config.py file so this should work, and it also works on our test server, with an older version of pgAdmin. I however don't see any release notes that say this changed.

Is this a bug or am I doing something wrong?

**Comment by dpage** [comment]
Issue closed on Redmine.
