### ISSUE TITLE
pip install -U pgadmin4 to 5.0 blocked due to a gssapi download problems (RM #6268)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4174]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6268***
*Originally created by **Bastiaan Wakkie** at 2021-02-25 13:27:24 UTC.*

If I use pip install -U pgadmin4 all is downloading fine accept the gssapi gives errors as pip cannot find any package

-Requirement already satisfied: pgadmin4 in ./lib/python3.8/site-packages (4.30)
Collecting pgadmin4
  Downloading pgadmin4-5.0-py3-none-any.whl (97.3 MB)
     |████████████████████████████████| 97.3 MB 33 kB/s
Requirement already satisfied: sqlparse==0.* in ./lib/python3.8/site-packages (from pgadmin4) (0.3.1)
Requirement already satisfied: sshtunnel==0.* in ./lib/python3.8/site-packages (from pgadmin4) (0.1.5)
Collecting cheroot==8.*
  Downloading cheroot-8.5.2-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 3.2 MB/s
Requirement already satisfied: Flask-BabelEx==0.* in ./lib/python3.8/site-packages (from pgadmin4) (0.9.4)
Collecting gssapi==1.6.*
  Downloading gssapi-1.6.12.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 11.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: /data/.envs/pgadmin/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ahl7m0u5/gssapi_7be2f31c8619482fb2b9d3fa18db64ab/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ahl7m0u5/gssapi_7be2f31c8619482fb2b9d3fa18db64ab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b9668r95
         cwd: /tmp/pip-install-ahl7m0u5/gssapi_7be2f31c8619482fb2b9d3fa18db64ab/
    Complete output (13 lines):
    /bin/sh: 1: krb5-config: not found
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ahl7m0u5/gssapi_7be2f31c8619482fb2b9d3fa18db64ab/setup.py", line 109, in <module>
        link_args = shlex.split(get_output(f"{kc} --libs gssapi"))
      File "/tmp/pip-install-ahl7m0u5/gssapi_7be2f31c8619482fb2b9d3fa18db64ab/setup.py", line 34, in get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c2/77/7cba9c5945d4d42d54ed1fb2a0bd8095d629548743198fa47ed6c1167846/gssapi-1.6.12.tar.gz#sha256=16ed3b5d7fc37683be27f34a2a65062cb11d815d019bb2e89ffeb395576e51c8 (from https://pypi.org/simple/gssapi/) (requires-python:>=3.6.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading gssapi-1.6.11.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 12.0 MB/s- --

... and this continues till version 1.6.0

the rest is downloaded just fine.

**Comment by dpage** [comment]
Issue closed on Redmine.
