### ISSUE TITLE
v5 fails to start on Big Sur; picks wrong image for _cffi_backend.cpython-39-darwin.so (RM #6269)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4175]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6269***
*Originally created by **Peter Buckner** at 2021-02-25 15:39:58 UTC.*

deleted previous v4.x pgadmin, download and install v5. After about one minute starting up, it reports Fatal Error:

<pre><code>
Python Path: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3"
Runtime Config File: "/Users/pbuck/Library/Preferences/pgadmin/runtime_config.json"
pgAdmin Config File: "/Applications/pgAdmin 4.app/Contents/Resources/web/config.py"
Webapp Path: "/Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
pgAdmin Command: "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 /Applications/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py"
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/app.nw/../web/pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/__init__.py", line 431, in create_app

    driver.init_app(app)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    import_module(module_name)
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/__init__.py", line 30, in <module>
    from .server_manager import ServerManager
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/driver/psycopg2/server_manager.py", line 32, in <module>

    from sshtunnel import SSHTunnelForwarder, BaseSSHTunnelForwarderError
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sshtunnel.py", line 25, in <module>
    import paramiko
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paramiko/transport.py", line 89, in <module>

    from paramiko.dsskey import DSSKey
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bcrypt/__init__.py", line 25, in <module>

    from . import _bcrypt  # type: ignore
ImportError: dlopen(/Users/pbuck/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/pbuck/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so: code signature in (/Users/pbuck/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
</code></pre>

Note: pgAdmin 4 application does contain a copy of _cffi_backedn.cpython-39.darwin.so (under Contents/Frameworks/Python.framework/Versions/39/lib/python3.9/site-packages) so why pgadmin cannot load it, I don't know -- it appears to attempt to load an older version from under my /Users/pbuck/Library/Python/3.9.../site-packages/_cffi_backend.cpython-39-darwin.so, which is a different version (I guess -- it's file size is different from the one shipped with pgAdmin.

If I RENAME "my" copy, pgAdmin loads without problem

**Comment by dpage** [comment]
Issue closed on Redmine.
