### ISSUE TITLE
Internal server error displayed on web browser with latest git pull (RM #1448)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#418]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1448***
*Originally created by **Fahar Abbas** at 2016-07-11 05:45:21 UTC.*

Tested Platform:

Ubuntu 32/64 bit

Commit ID:
-----------
61698b7b4db3eea39a034c7ff0f90d0c710ffcb8

Browser:
Firefox 46.0.1

Internal server error displayed on web browser instead of pgAdmin4. It's seems a new regression.

Here is the output in terminal:
--------------------------------
python pgAdmin4.py 
Starting pgAdmin 4. Please navigate to http://localhost:5050 in your browser.
2016-07-10 22:39:42,040: ERROR	pgadmin:	Exception on /browser/ [GET]
Traceback (most recent call last):
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 256, in save_session
    self.manager.put(session)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 133, in put
    self.parent.put(session)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 203, in put
    session.sign(self.secret)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 59, in sign
    self.randval = ''.join(random.sample(string.lowercase+string.digits, 20))
AttributeError: module 'string' has no attribute 'lowercase'
2016-07-10 22:39:42,148: ERROR	pgadmin:	Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 256, in save_session
    self.manager.put(session)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 133, in put
    self.parent.put(session)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 203, in put
    session.sign(self.secret)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/utils/session.py", line 59, in sign
    self.randval = ''.join(random.sample(string.lowercase+string.digits, 20))
AttributeError: module 'string' has no attribute 'lowercase'

**Comment by dpage** [comment]
Issue closed on Redmine.
