### ISSUE TITLE
User is not able to launch pgadmin4 through Runtime and web mode (RM #6446)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4317]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6446***
*Originally created by **Fahar Abbas** at 2021-05-12 07:23:30 UTC.*

Platform:
Centos 7, 8
Fedora 33, 34
Snapshot Build:

https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2021-05-12/yum/

Steps
1. follow instructions of yum till end
2. Launch pgadmin4 through Runtime and web mode
3. Following error displayed:

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/fahar/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - IMSETTINGS_INTEGRATE_DESKTOP: yes
  - SHELL: /bin/bash
  - XDG_CONFIG_DIRS: /etc/xdg
  - XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
  - HISTCONTROL: ignoredups
  - XDG_MENU_PREFIX: xfce-
  - HISTSIZE: 1000
  - HOSTNAME: fedora
  - SSH_AUTH_SOCK: /tmp/ssh-mU2H032cHFEO/agent.993
  - XMODIFIERS: @im=none
  - DESKTOP_SESSION: xfce
  - SSH_AGENT_PID: 1151
  - EDITOR: /usr/bin/nano
  - XDG_SEAT: seat0
  - PWD: /home/fahar
  - XDG_SESSION_DESKTOP: xfce
  - LOGNAME: fahar
  - XDG_SESSION_TYPE: x11
  - XAUTHORITY: /run/lightdm/fahar/xauthority
  - XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/fahar
  - HOME: /home/fahar
  - SSH_ASKPASS: /usr/libexec/openssh/gnome-ssh-askpass
  - LANG: en_US.utf8
  - XDG_CURRENT_DESKTOP: XFCE
  - XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
  - IMSETTINGS_MODULE: none
  - XDG_SESSION_CLASS: user
  - TERM: dumb
  - LESSOPEN: ||/usr/bin/lesspipe.sh %s
  - USER: fahar
  - SHLVL: 0
  - QT_IM_MODULE: xim
  - XDG_VTNR: 1
  - XDG_SESSION_ID: 2
  - XDG_RUNTIME_DIR: /run/user/1000
  - XDG_DATA_DIRS: /home/fahar/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/usr/share
  - PATH: /home/fahar/.local/bin:/home/fahar/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
  - GDMSESSION: xfce
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - MAIL: /var/spool/mail/fahar
  - SESSION_MANAGER: local/unix:@/tmp/.ICE-unix/993,unix/unix:/tmp/.ICE-unix/993
  - PANEL_GDK_CORE_DEVICE_EVENTS: 0
  - DISPLAY: :0.0
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 33233
  - PGADMIN_INT_KEY: d22d2357-48b4-4d56-9a4f-e7e044b5db1e
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

NOTE: Configuring authentication for DESKTOP mode.

Traceback (most recent call last):

  File "/usr/pgadmin4/web/pgAdmin4.py", line 91, in <module>

    exec(open(file_quote(setup_py), 'r').read())

  File "<string>", line 507, in <module>

  File "<string>", line 379, in setup_db

  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 351, in create_app

    db_upgrade(app)

  File "/usr/pgadmin4/web/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade

    flask_migrate.upgrade(migration_folder)

  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask_migrate/__init__.py", line 96, in wrapped

    f(*args, **kwargs)

  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask_migrate/__init__.py", line 271, in upgrade

    command.upgrade(config, revision, sql=sql, tag=tag)

  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/alembic/command.py", line 294, in upgrade

    script.run_env()

  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/alembic/script/base.py", line 490, in run_env

    util.load_python_file(self.dir, "env.py")

  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file

    module = load_module_py(module_id, path)

  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py

    spec.loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 790, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/usr/pgadmin4/web/pgadmin/setup/../../migrations/env.py", line 93, in <module>

    run_migrations_online()

  File "/usr/pgadmin4/web/pgadmin/setup/../../migrations/env.py", line 86, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/usr/pgadmin4/web/migrations/versions/fdc58d9bd449_.py", line 122, in upgrade
    Security(current_app, user_datastore, register_blueprint=False)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask_security/core.py", line 1062, in __init__
    self._state = self.init_app(
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask_security/core.py", line 1102, in init_app
    self._state = state = _get_state(app, datastore, **kwargs)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask_security/core.py", line 608, in _get_state
    remember_token_serializer=_get_serializer(app, "remember"),
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/flask_security/core.py", line 593, in _get_serializer
    return URLSafeTimedSerializer(secret_key=secret_key, salt=salt)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/itsdangerous/serializer.py", line 104, in __init__
    self.secret_keys: _t.List[bytes] = _make_keys_list(secret_key)
  File "/usr/pgadmin4/venv/lib64/python3.9/site-packages/itsdangerous/signer.py", line 64, in _make_keys_list

    return [want_bytes(s) for s in secret_key]

TypeError: 'NoneType' object is not iterable

**Comment by dpage** [comment]
Issue closed on Redmine.
