### ISSUE TITLE
Can't use pgAdmin 4 (RM #6451)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4321]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6451***
*Originally created by **Louis-Francois Lapointe** at 2021-05-14 17:02:51 UTC.*

A) Install postgreSQL
B) Delete the folder C:\Users\lflapointe\AppData\Roaming\pgadmin
C) Run pgAdmin
D) Observe the following call trace in python:
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe"
Runtime Config File:
"C:\Users\lflapointe\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\lflapointe\AppData\Roaming
  - BOOST_ROOT: C:\Program Files\Boost
  - CARBON_MEM_DISABLE: 1
  - ChocolateyInstall: C:\ProgramData\chocolatey
  - ChocolateyLastPathUpdate: 132324868876994753
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_7392_AYLVKGPDTQNBNUOZ
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CLASSPATH: C:\Program Files\OpenNI\Bin64\org.OpenNI.jar
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: LAPTOP-9U6GQU1I
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - configsetroot: C:\WINDOWS\ConfigSetRoot
  - CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
  - CUDA_PATH_V10_0: C:\Program Files\NVIDIA GPU Computing
Toolkit\CUDA\v10.0
  - D3DGEARPATH: c:\program files\d3dgear
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - EIGEN_ROOT: C:\Program Files (x86)\Eigen
  - FLANN_ROOT: C:\Program Files\flann
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\lflapointe
  - KMP_DUPLICATE_LIB_OK: TRUE
  - LOCALAPPDATA: C:\Users\lflapointe\AppData\Local
  - LOGONSERVER: \\SERVER1
  - MYNTEYES_SDK_ROOT:
C:\Users\lflapointe\AppData\Roaming\Slightech\MYNTEYES\SDK\2.4.2
  - NUMBER_OF_PROCESSORS: 12
  - NVCUDASAMPLES10_0_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA
Samples\v10.0
  - NVCUDASAMPLES_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA
Samples\v10.0
  - NVTOOLSEXT_PATH: C:\Program Files\NVIDIA Corporation\NvToolsExt\
  - OneDrive: C:\Users\lflapointe\OneDrive
  - OPENCV_DIR:
C:\Users\lflapointe\source\repos\opencv-master\opencv-master\out\build
  - OPEN_NI_BIN64: C:\Program Files\OpenNI\Bin64
  - OPEN_NI_INCLUDE: C:\Program Files\OpenNI\Include
  - OPEN_NI_INSTALL_PATH64: C:\Program Files\OpenNI\
  - OPEN_NI_LIB64: C:\Program Files\OpenNI\Lib64
  - OS: Windows_NT
  - Path:
C:\Users\lflapointe\AppData\Roaming\Slightech\MYNTEYES\SDK\2.4.2\bin;C:\Users\lflapointe\AppData\Roaming\Slightech\MYNTEYES\SDK\2.4.2\3rdparty\opencv\build\x64\vc15\bin;C:\Program
Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\ZED SDK\dependencies\freeglut_2.8\x64;C:\Program Files (x86)\ZED SDK\dependencies\glew-1.12.0\x64;C:\Program Files (x86)\ZED SDK\dependencies\opencv_3.1.0\x64\vc14\bin;C:\Program Files (x86)\ZED SDK\bin;C:\Program Files\OpenNI\Bin64;C:\Program Files (x86)\GnuWin32\bin;C:\ProgramData\chocolatey\bin;C:\Program
Files\Git\cmd;C:\Program Files (x86)\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
Files\CMake\bin;C:\Program Files (x86)\Nordic Semiconductor\nrf-command-line-tools\bin\;c:\program
files\d3dgear;c:\program files\d3dgear;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\GNU Arm Embedded Toolchain\9 2020-q2-update\bin;C:\Users\lflapointe\AppData\Local\Microsoft\WindowsApps;C:\Users\lflapointe\source\repos\opencv-master\opencv-master\out\build\x64-Debug\bin;C:\Program
Files (x86)\mynteye\bin;C:\Program
Files\OpenNI\Bin64;C:\Users\lflapointe\source\repos\SmartHip\Firmware\common\armgcc\win32\bin;C:\Users\lflapointe\.dotnet\tools;C:\Users\lflapointe\AppData\Local\Microsoft\WindowsApps;C:\Users\lflapointe\.dotnet\tools;C:\Program
Files (x86)\Nordic Semiconductor\nrf-command-line-tools\bin;;C:\Program
Files\JetBrains\PyCharm Community Edition 2021.1.1\bin;
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PCL_ROOT: C:\Program Files\PCL 1.6.0
  - PGADMIN_INT_KEY: ab273c3c-b1fd-4588-8a60-9f8d2ba2e04c
  - PGADMIN_INT_PORT: 56287
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 9e0a
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program
Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program
Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
  - PUBLIC: C:\Users\Public
  - PyCharm Community Edition: C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.1\bin;
  - QHULL_ROOT: C:\Program Files\qhull
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\LFLAPO~1\AppData\Local\Temp
  - TMP: C:\Users\LFLAPO~1\AppData\Local\Temp
  - USERDNSDOMAIN: LINKORTHOPAEDICS.LOCAL
  - USERDOMAIN: LINK
  - USERDOMAIN_ROAMINGPROFILE: LINK
  - USERNAME: lflapointe
  - USERPROFILE: C:\Users\lflapointe
  - VTK_DIR: C:\Program Files\VTK 5.8.0\lib\vtk-5.8
  - windir: C:\WINDOWS
  - ZED_SDK_ROOT_DIR: C:\Program Files (x86)\ZED SDK
--------------------------------------------------------

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\__init__.py", line 347, in create_app
    if not os.path.exists(SQLITE_PATH) or get_version() == -1:
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\db_version.py", line 19, in get_version
    return version.value
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by dpage** [comment]
Issue closed on Redmine.
