### ISSUE TITLE
Can't use pgAdmin 4 no2 (RM #6452)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4322]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6452***
*Originally created by **Louis-Francois Lapointe** at 2021-05-14 17:03:38 UTC.*

A) Install PostgreSQL
B) Delete pgadmin folder in roaming
C) Execute pgAdmin 4
D) Observe the call stack in python:

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe"
Runtime Config File:
"C:\Users\lflapointe\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\lflapointe\AppData\Roaming
  - BOOST_ROOT: C:\Program Files\Boost
  - CARBON_MEM_DISABLE: 1
  - ChocolateyInstall: C:\ProgramData\chocolatey
  - ChocolateyLastPathUpdate: 132324868876994753
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_6832_AFEZAWEIRCFNTQWC
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CLASSPATH: C:\Program Files\OpenNI\Bin64\org.OpenNI.jar
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: LAPTOP-9U6GQU1I
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - configsetroot: C:\WINDOWS\ConfigSetRoot
  - CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
  - CUDA_PATH_V10_0: C:\Program Files\NVIDIA GPU Computing
Toolkit\CUDA\v10.0
  - D3DGEARPATH: c:\program files\d3dgear
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - EIGEN_ROOT: C:\Program Files (x86)\Eigen
  - FLANN_ROOT: C:\Program Files\flann
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\lflapointe
  - KMP_DUPLICATE_LIB_OK: TRUE
  - LOCALAPPDATA: C:\Users\lflapointe\AppData\Local
  - LOGONSERVER: \\SERVER1
  - MYNTEYES_SDK_ROOT:
C:\Users\lflapointe\AppData\Roaming\Slightech\MYNTEYES\SDK\2.4.2
  - NUMBER_OF_PROCESSORS: 12
  - NVCUDASAMPLES10_0_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA
Samples\v10.0
  - NVCUDASAMPLES_ROOT: C:\ProgramData\NVIDIA Corporation\CUDA
Samples\v10.0
  - NVTOOLSEXT_PATH: C:\Program Files\NVIDIA Corporation\NvToolsExt\
  - OneDrive: C:\Users\lflapointe\OneDrive
  - OPENCV_DIR:
C:\Users\lflapointe\source\repos\opencv-master\opencv-master\out\build
  - OPEN_NI_BIN64: C:\Program Files\OpenNI\Bin64
  - OPEN_NI_INCLUDE: C:\Program Files\OpenNI\Include
  - OPEN_NI_INSTALL_PATH64: C:\Program Files\OpenNI\
  - OPEN_NI_LIB64: C:\Program Files\OpenNI\Lib64
  - OS: Windows_NT
  - Path:
C:\Users\lflapointe\AppData\Roaming\Slightech\MYNTEYES\SDK\2.4.2\bin;C:\Users\lflapointe\AppData\Roaming\Slightech\MYNTEYES\SDK\2.4.2\3rdparty\opencv\build\x64\vc15\bin;C:\Program
Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\ZED SDK\dependencies\freeglut_2.8\x64;C:\Program Files (x86)\ZED SDK\dependencies\glew-1.12.0\x64;C:\Program Files (x86)\ZED SDK\dependencies\opencv_3.1.0\x64\vc14\bin;C:\Program Files (x86)\ZED SDK\bin;C:\Program Files\OpenNI\Bin64;C:\Program Files (x86)\GnuWin32\bin;C:\ProgramData\chocolatey\bin;C:\Program
Files\Git\cmd;C:\Program Files (x86)\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
Files\CMake\bin;C:\Program Files (x86)\Nordic Semiconductor\nrf-command-line-tools\bin\;c:\program
files\d3dgear;c:\program files\d3dgear;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\GNU Arm Embedded Toolchain\9 2020-q2-update\bin;C:\Users\lflapointe\AppData\Local\Microsoft\WindowsApps;C:\Users\lflapointe\source\repos\opencv-master\opencv-master\out\build\x64-Debug\bin;C:\Program
Files (x86)\mynteye\bin;C:\Program
Files\OpenNI\Bin64;C:\Users\lflapointe\source\repos\SmartHip\Firmware\common\armgcc\win32\bin;C:\Users\lflapointe\.dotnet\tools;C:\Users\lflapointe\AppData\Local\Microsoft\WindowsApps;C:\Users\lflapointe\.dotnet\tools;C:\Program
Files (x86)\Nordic Semiconductor\nrf-command-line-tools\bin;;C:\Program
Files\JetBrains\PyCharm Community Edition 2021.1.1\bin;
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PCL_ROOT: C:\Program Files\PCL 1.6.0
  - PGADMIN_INT_KEY: b12a21af-23c9-4324-9749-be4e401bbfdc
  - PGADMIN_INT_PORT: 56550
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 9e0a
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program
Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program
Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
  - PUBLIC: C:\Users\Public
  - PyCharm Community Edition: C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.1\bin;
  - QHULL_ROOT: C:\Program Files\qhull
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\LFLAPO~1\AppData\Local\Temp
  - TMP: C:\Users\LFLAPO~1\AppData\Local\Temp
  - USERDNSDOMAIN: LINKORTHOPAEDICS.LOCAL
  - USERDOMAIN: LINK
  - USERDOMAIN_ROAMINGPROFILE: LINK
  - USERNAME: lflapointe
  - USERPROFILE: C:\Users\lflapointe
  - VTK_DIR: C:\Program Files\VTK 5.8.0\lib\vtk-5.8
  - windir: C:\WINDOWS
  - ZED_SDK_ROOT_DIR: C:\Program Files (x86)\ZED SDK
--------------------------------------------------------

NOTE: Configuring authentication for DESKTOP mode.

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py", line 91, in <module>
    exec(open(file_quote(setup_py), 'r').read())
  File "<string>", line 506, in <module>
  File "<string>", line 378, in setup_db
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\__init__.py", line 351, in create_app
    db_upgrade(app)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_migrate\__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_migrate\__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\command.py", line 294, in upgrade
    script.run_env()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\util\compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 93, in <module>
    run_migrations_online()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 86, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\runtime\environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\runtime\migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\migrations\versions\fdc58d9bd449_.py", line 122, in upgrade
    Security(current_app, user_datastore, register_blueprint=False)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_security\core.py", line 1062, in __init__
    self._state = self.init_app(
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_security\core.py", line 1102, in init_app
    self._state = state = _get_state(app, datastore, **kwargs)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_security\core.py", line 608, in _get_state
    remember_token_serializer=_get_serializer(app, "remember"),
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_security\core.py", line 593, in _get_serializer
    return URLSafeTimedSerializer(secret_key=secret_key, salt=salt)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\itsdangerous\serializer.py", line 104, in __init__
    self.secret_keys: _t.List[bytes] = _make_keys_list(secret_key)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\itsdangerous\signer.py", line 64, in _make_keys_list
    return [want_bytes(s) for s in secret_key]
TypeError: 'NoneType' object is not iterable

**Comment by dpage** [comment]
Issue closed on Redmine.
