### ISSUE TITLE
the pgAdmin4 server could not be contacted (RM #6459)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4328]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6459***
*Originally created by **N. S** at 2021-05-18 05:44:25 UTC.*

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\12\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\DELL\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\PostgreSQL\12\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\PostgreSQL\12\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\12\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\12\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - AGSDESKTOPJAVA: C:\Program Files (x86)\ArcGIS\Desktop10.4\
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\DELL\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_7244_OCPHRBDXBITQPBYE
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: DESKTOP-EQFI961
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\DELL
  - LOCALAPPDATA: C:\Users\DELL\AppData\Local
  - LOGONSERVER: \\DESKTOP-EQFI961
  - MOZ_PLUGIN_PATH: C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
  - NUMBER_OF_PROCESSORS: 4
  - OneDrive: C:\Users\DELL\OneDrive - Bina Nusantara University
  - OneDriveCommercial: C:\Users\DELL\OneDrive - Bina Nusantara University
  - OS: Windows_NT
  - Path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Roaming\npm;C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\DELL\AppData\Roaming\Composer\vendor\bin;C:\Users\DELL\AppData\Local\GitHubDesktop\bin;C:\Program Files\PostgreSQL\bin;C:\Program Files\PostgreSQL\12\bin;
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 3439b2e2-54a4-4b98-978f-6e1167f105a8
  - PGADMIN_INT_PORT: 51928
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: AMD64 Family 21 Model 96 Stepping 1, AuthenticAMD
  - PROCESSOR_LEVEL: 21
  - PROCESSOR_REVISION: 6001
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\DELL\AppData\Local\Temp
  - TMP: C:\Users\DELL\AppData\Local\Temp
  - USERDOMAIN: DESKTOP-EQFI961
  - USERDOMAIN_ROAMINGPROFILE: DESKTOP-EQFI961
  - USERNAME: DELL
  - USERPROFILE: C:\Users\DELL
  - VS100COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
  - windir: C:\WINDOWS
--------------------------------------------------------

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\12\pgAdmin 4\web\pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "C:\Program Files\PostgreSQL\12\pgAdmin 4\web\pgadmin\__init__.py", line 347, in create_app
    if not os.path.exists(SQLITE_PATH) or get_version() == -1:
  File "C:\Program Files\PostgreSQL\12\pgAdmin 4\web\pgadmin\setup\db_version.py", line 19, in get_version
    return version.value
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by dpage** [comment]
Issue closed on Redmine.
