### ISSUE TITLE
Pgadmin  (RM #6484)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4344]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6484***
*Originally created by **Mrunalini Rajan** at 2021-05-25 23:24:48 UTC.*

I am not able to bring up pgadmin
The pgAdmin 4 server could not be contacted
"pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\rajanm\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\rajanm\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_13880_ROIWFYTBDMWKHVGD
  - CHROME_RESTART: NW.js|Whoa! NW.js has crashed. Relaunch now?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: SFOR90NSL4E
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
  - FPS_BROWSER_USER_PROFILE_STRING: Default
  - HDBADONET: C:\Program Files\sap\hdbclient\ado.net\
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\rajanm
  - INFA_TRUSTSTORE: C:\Informatica\10.1.0\clients\shared\security
  - LOCALAPPDATA: C:\Users\rajanm\AppData\Local
  - LOGONSERVER: \\USSCLPDWCADDC11
  - NUMBER_OF_PROCESSORS: 4
  - OneDrive: C:\Users\rajanm\OneDrive - autodesk
  - OneDriveCommercial: C:\Users\rajanm\OneDrive - autodesk
  - OS: Windows_NT
  - Path: C:\Informatica\10.1.0\clients\tools\datadirect;C:\app\oracle_32\product\11.2.0\client_1\bin;C:\app\ora_client\product\11.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Users\rajanm\AppData\Local\Microsoft\WindowsApps;C:\Users\rajanm\AppData\Local\GitHubDesktop\bin
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 0aae7353-09c3-48f0-85e3-b7e2b7d9f13d
  - PGADMIN_INT_PORT: 51314
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 8e09
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\rajanm\AppData\Local\Temp\1
  - TMP: C:\Users\rajanm\AppData\Local\Temp\1
  - UATDATA: C:\WINDOWS\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
  - UIPATH_LANGUAGE: en
  - USERDNSDOMAIN: ADS.AUTODESK.COM
  - USERDOMAIN: ADS
  - USERDOMAIN_ROAMINGPROFILE: ADS
  - USERNAME: rajanm
  - USERPROFILE: C:\Users\rajanm
  - windir: C:\WINDOWS
  - __COMPAT_LAYER: DetectorsMessageBoxErrors
--------------------------------------------------------

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\__init__.py", line 347, in create_app
    if not os.path.exists(SQLITE_PATH) or get_version() == -1:
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\db_version.py", line 19, in get_version
    return version.value
AttributeError: 'NoneType' object has no attribute 'value'

postgresql-13.3-2-windows-x64.exe"

**Comment by dpage** [comment]
Issue closed on Redmine.
