### ISSUE TITLE
Fatal error: The pgAdmin 4 server could not be contacted: (RM #6499)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4358]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6499***
*Originally created by **Markus Meyer** at 2021-05-28 08:43:58 UTC.*

I cant start pgAdmin4 because there is always this error. I already added some paths to as system variables and I cleared the Roaming folder as it is recommended in some stackoverflow threads.

Full error message:

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\meyer\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\meyer\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_15956_JGBSXQHOVSTVUBHE
  - CHROME_RESTART: NW.js|NW.js ist abgestürzt. Jetzt neu starten?|LEFT_TO_RIGHT
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: DESKTOP-PUSFR0U
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\meyer
  - LOCALAPPDATA: C:\Users\meyer\AppData\Local
  - LOGONSERVER: \\DESKTOP-PUSFR0U
  - NUMBER_OF_PROCESSORS: 4
  - OneDrive: C:\Users\meyer\OneDrive
  - OneDriveConsumer: C:\Users\meyer\OneDrive
  - OnlineServices: Online Services
  - OS: Windows_NT
  - Path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\R2019a\bin;C:\Program Files\MATLAB\R2017b\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MATLAB\R2020a\bin;C:\Program Files\dotnet\;D:\Program Files\Git\cmd;D:\Programme\NodeJs\;C:\Program Files\PostgreSQL\13\bin;C:\Program Files\PostgreSQL\13\pgAdmin 4\bin;C:\Users\meyer\AppData\Local\Programs\Python\Python39;C:\Users\meyer\AppData\Local\Programs\Python\Python39\Scripts;C:\Program Files\PostgreSQL\13\pgAdmin 4\python;C:\Users\meyer\AppData\Local\Microsoft\WindowsApps;C:\Users\meyer\AppData\Local\GitHubDesktop\bin;C:\Users\meyer\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\meyer\AppData\Roaming\npm;C:\Users\meyer\AppData\Roaming\pgadmin\pgadmin4.db
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 0069081f-41e7-4171-a9c6-e7ee7843d692
  - PGADMIN_INT_PORT: 49953
  - PGADMIN_SERVER_MODE: OFF
  - platformcode: 6J
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 5e03
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
  - PUBLIC: C:\Users\Public
  - RegionCode: EMEA
  - SQLITE_PATH: C:\Program Files\PostgreSQL\13\bin
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\meyer\AppData\Local\Temp
  - TMP: C:\Users\meyer\AppData\Local\Temp
  - USERDOMAIN: DESKTOP-PUSFR0U
  - USERDOMAIN_ROAMINGPROFILE: DESKTOP-PUSFR0U
  - USERNAME: meyer
  - USERPROFILE: C:\Users\meyer
  - windir: C:\WINDOWS
  - __COMPAT_LAYER: Installer
--------------------------------------------------------

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\impl.py", line 241, in _do_get
    return self._create_connection()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgAdmin4.py", line 91, in <module>
    exec(open(file_quote(setup_py), 'r').read())
  File "<string>", line 506, in <module>
  File "<string>", line 378, in setup_db
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\__init__.py", line 351, in create_app
    db_upgrade(app)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_migrate\__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\flask_migrate\__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\command.py", line 294, in upgrade
    script.run_env()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\alembic\util\compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 93, in <module>
    run_migrations_online()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 78, in run_migrations_online
    connection = engine.connect()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 104, in __init__
    else engine.raw_connection()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\impl.py", line 241, in _do_get
    return self._create_connection()
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Program Files\PostgreSQL\13\pgAdmin 4\python\lib\site-packages\sqlalchemy\engine\default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by dpage** [comment]
Issue closed on Redmine.
