### ISSUE TITLE
pgAdmin server mode does not open after password reset (RM #6513)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4369]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6513***
*Originally created by **Aditya Toshniwal** at 2021-06-04 10:49:08 UTC.*

Hi,

In the server mode, I clicked on forgot password and got the password reset link. But, once I reset the password using the link, pgAdmin does not open.
It throws the following error in backend.

Traceback (most recent call last):
  File "/Users/adityatoshniwal/venv/pypg37/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/adityatoshniwal/venv/pypg37/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/adityatoshniwal/venv/pypg37/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/adityatoshniwal/projects/pgadmin4/web/pgadmin/browser/__init__.py", line 749, in index
    auth_source = session['_auth_source_manager_obj'][
  File "/Users/adityatoshniwal/venv/pypg37/lib/python3.7/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: '_auth_source_manager_obj'

**Comment by dpage** [comment]
Issue closed on Redmine.
