### ISSUE TITLE
pgadmin4 Docker instance exited with invalid syntax (RM #6534)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4385]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6534***
*Originally created by **Fahar Abbas** at 2021-06-15 12:43:31 UTC.*

Candidate build:

Steps

1. docker pull dpage/pgadmin4:2021-06-15-1
2. docker run -p 80:80 \ -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" \ -e "PGADMIN_DEFAULT_PASSWORD=SuperSecret" \ -d dpage/pgadmin4:2021-06-15-1
3.docker logs cdd4fe03e032
Traceback (most recent call last):
  File "run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 39, in <module>
    import config
  File "/pgadmin4/config.py", line 665, in <module>
    from config_distro import *
  File "/pgadmin4/config_distro.py", line 6
    'pg-12': '/usr/local/pgsql-12'
           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pgadmin4/config.py", line 665, in <module>
    from config_distro import *
  File "/pgadmin4/config_distro.py", line 6
    'pg-12': '/usr/local/pgsql-12'
           ^
SyntaxError: invalid syntax
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: argument -t/--timeout: expected one argument

**Comment by dpage** [comment]
Issue closed on Redmine.
