### ISSUE TITLE
5.4 throws exception: TypeError: 'NoneType' object is not subscriptable (RM #6580)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4426]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6580***
*Originally created by **Kok How Teh** at 2021-07-03 08:53:01 UTC.*

2021-07-03 08:49:27,260: ERROR  pgadmin:        'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/pgadmin4/pgadmin/__init__.py", line 679, in current_user_cleanup
    mdl.on_logout(user)
  File "/pgadmin4/pgadmin/tools/datagrid/__init__.py", line 91, in on_logout
    close_query_tool_session(trans_id)
  File "/pgadmin4/pgadmin/tools/datagrid/__init__.py", line 614, in close_query_tool_session
    conn.cancel_transaction(cmd_obj.conn_id, cmd_obj.did)
  File "/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py", line 1710, in cancel_transaction
    password = decrypt(password, crypt_key)\
  File "/pgadmin4/pgadmin/utils/crypto.py", line 59, in decrypt
    cipher = Cipher(AES(pad(key)), CFB8(iv), default_backend())
  File "/pgadmin4/pgadmin/utils/crypto.py", line 71, in pad
    key = key[:32]
TypeError: 'NoneType' object is not subscriptable

**Comment by dpage** [comment]
Issue closed on Redmine.
