### ISSUE TITLE
Unable to login with Auth  when LDAP & OAuth configured as login sources (RM #6594)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4437]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6594***
*Originally created by **Yogesh Mahajan** at 2021-07-09 04:21:20 UTC.*

1.COnfigure pgAdmin to login with OAuth & LDAP both.
2.Try to login with OAuth.
3.Erroor shown on browser - 

<pre>
[Thu Jul 08 13:00:13.635465 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041] 2021-07-08 13:00:13,632: ERROR\tpgadmin:\tError connecting to the LDAP server: password is mandatory in simple bind
[Thu Jul 08 13:00:13.635603 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041] Traceback (most recent call last):
[Thu Jul 08 13:00:13.635616 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/web/pgadmin/authenticate/ldap.py", line 116, in connect
[Thu Jul 08 13:00:13.635627 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     self.conn = Connection(server,
[Thu Jul 08 13:00:13.635636 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/ldap3/core/connection.py", line 363, in __init__
[Thu Jul 08 13:00:13.635646 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     self._do_auto_bind()
[Thu Jul 08 13:00:13.635655 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/ldap3/core/connection.py", line 389, in _do_auto_bind
[Thu Jul 08 13:00:13.635664 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     self.bind(read_server_info=True)
[Thu Jul 08 13:00:13.635673 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/ldap3/core/connection.py", line 604, in bind
[Thu Jul 08 13:00:13.635683 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     request = bind_operation(self.version, self.authentication, self.user, self.password, auto_encode=self.auto_encode)
[Thu Jul 08 13:00:13.635693 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/ldap3/operation/bind.py", line 59, in bind_operation
[Thu Jul 08 13:00:13.635703 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     raise LDAPPasswordIsMandatoryError('password is mandatory in simple bind')
[Thu Jul 08 13:00:13.635719 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041] ldap3.core.exceptions.LDAPPasswordIsMandatoryError: password is mandatory in simple bind
[Thu Jul 08 13:00:13.637700 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041] mod_wsgi (pid=2261): Exception occurred processing WSGI script '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Thu Jul 08 13:00:13.641590 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041] Traceback (most recent call last):
[Thu Jul 08 13:00:13.641798 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
[Thu Jul 08 13:00:13.641830 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     return self.wsgi_app(environ, start_response)
[Thu Jul 08 13:00:13.641856 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/web/pgAdmin4.py", line 77, in __call__
[Thu Jul 08 13:00:13.641867 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     return self.app(environ, start_response)
[Thu Jul 08 13:00:13.641886 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
[Thu Jul 08 13:00:13.641903 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     return self.app(environ, start_response)
[Thu Jul 08 13:00:13.641923 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __call__
[Thu Jul 08 13:00:13.641934 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     return super(_SocketIOMiddleware, self).__call__(environ,
[Thu Jul 08 13:00:13.641952 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/engineio/middleware.py", line 71, in __call__
[Thu Jul 08 13:00:13.641962 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     return self.wsgi_app(environ, start_response)
[Thu Jul 08 13:00:13.641980 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
[Thu Jul 08 13:00:13.641990 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     response = self.handle_exception(e)
[Thu Jul 08 13:00:13.642008 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
[Thu Jul 08 13:00:13.642017 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     reraise(exc_type, exc_value, tb)
[Thu Jul 08 13:00:13.642035 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[Thu Jul 08 13:00:13.642045 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     raise value
[Thu Jul 08 13:00:13.642063 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
[Thu Jul 08 13:00:13.642073 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     response = self.full_dispatch_request()
[Thu Jul 08 13:00:13.642090 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
[Thu Jul 08 13:00:13.642100 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     return self.finalize_request(rv)
[Thu Jul 08 13:00:13.642147 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
[Thu Jul 08 13:00:13.642161 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     response = self.process_response(response)
[Thu Jul 08 13:00:13.642180 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 2269, in process_response
[Thu Jul 08 13:00:13.642201 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     self.session_interface.save_session(self, ctx.session, response)
[Thu Jul 08 13:00:13.642222 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/web/pgadmin/utils/session.py", line 307, in save_session
[Thu Jul 08 13:00:13.642232 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     self.manager.put(session)
[Thu Jul 08 13:00:13.642250 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/web/pgadmin/utils/session.py", line 166, in put
[Thu Jul 08 13:00:13.642260 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     self.parent.put(session)
[Thu Jul 08 13:00:13.642278 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]   File "/usr/pgadmin4/web/pgadmin/utils/session.py", line 270, in put
[Thu Jul 08 13:00:13.642297 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041]     dump(
[Thu Jul 08 13:00:13.642333 2021] [wsgi:error] [pid 2261:tid 140003578107648] [remote 172.24.66.26:54041] _pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
