### ISSUE TITLE
Unable to add server in Kerbores Authentication Mode (RM #6596)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4438]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6596***
*Originally created by **Yogesh Mahajan** at 2021-07-09 12:15:00 UTC.*

Unable to add server in Kerbores Mode

<pre>
ubuntu@pgadmin4server-kerbores:~$ cat /etc/pgadmin/config_system.py 
SERVER_MODE=True
AUTHENTICATION_SOURCES = ['kerberos','internal']
KERBEROS_AUTO_CREATE_USER = True
KRB_APP_HOST_NAME = 'test.pgadmin.org'
KRB_KTNAME = '/home/ubuntu/pgadmin.keytab'
</pre>

Error - 
<pre>
2021-07-09 10:53:01,014: ERROR	pgadmin:	'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/pgadmin4/web/pgadmin/browser/__init__.py", line 1065, in set_master_password
    set_masterpass_check_text(crypt_key)
  File "/usr/pgadmin4/web/pgadmin/utils/master_password.py", line 73, in set_masterpass_check_text
    masterpass_check = encrypt(MASTERPASS_CHECK_TEXT, password)
  File "/usr/pgadmin4/web/pgadmin/utils/crypto.py", line 35, in encrypt
    cipher = Cipher(AES(pad(key)), CFB8(iv), default_backend())
  File "/usr/pgadmin4/web/pgadmin/utils/crypto.py", line 71, in pad
    key = key[:32]
TypeError: 'NoneType' object is not subscriptable
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
