### ISSUE TITLE
Dashboard Server Activity Sessions Rendering Issue (RM #6650)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4476]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6650***
*Originally created by **Guy Browne** at 2021-07-28 23:54:40 UTC.*

Intermittent rendering issue for Sessions in the Server Activity section of the Dashboard tab.  Happens only at the Databases (instance) level but not for the individual databases.

Only way to clear it is to remove server and re-add but this is only successful for a period of time.  Happens when accessing PG 10, 11 and 12 database instances.

2021-07-29 09:33:29,222: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.
2021-07-29 09:33:50,914: ERROR	pgadmin:	float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\pgAdmin 4\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\pgAdmin 4\python\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\web\pgadmin\dashboard\__init__.py", line 247, in wrap
    return f(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\web\pgadmin\dashboard\__init__.py", line 425, in activity
    return get_data(sid, did, 'activity.sql', True)
  File "C:\Program Files\pgAdmin 4\web\pgadmin\dashboard\__init__.py", line 340, in get_data
    get_long_running_query_status(res['rows'])
  File "C:\Program Files\pgAdmin 4\web\pgadmin\dashboard\__init__.py", line 372, in get_long_running_query_status
    active_since = float(row['active_since'])
TypeError: float() argument must be a string or a number, not 'NoneType'

!
!Screenshot%202021-07-29-004.png!
!Screenshot%202021-07-29-003.png!
!

**Comment by dpage** [comment]
Issue closed on Redmine.
