### ISSUE TITLE
pgadmin 4 return error no attribute '_asdict' when connnect the postgresql (RM #6663)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4489]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6663***
*Originally created by **John Gaia** at 2021-08-05 04:30:57 UTC.*

1，in the server Linux version 5.12.4(REDHAT9.3)
    pgadmin server can work normal, but its not work normal with psycopg2 == 2.8.6
    
2, when i connect the postgresql, page return fail with error info: 'psycopg2.extensions.Column' object has no attribute '_asdict'

3，pgadmin4 service log:

SELECT 'tps_stats' AS chart_name, pg_catalog.row_to_json(t) AS chart_data
FROM (SELECT
   (SELECT sum(xact_commit) + sum(xact_rollback) FROM pg_catalog.pg_stat_database) AS "Transactions",
   (SELECT sum(xact_commit) FROM pg_catalog.pg_stat_database) AS "Commits",
   (SELECT sum(xact_rollback) FROM pg_catalog.pg_stat_database) AS "Rollbacks"
) t
UNION ALL
SELECT 'ti_stats' AS chart_name, pg_catalog.row_to_json(t) AS chart_data
FROM (SELECT
   (SELECT sum(tup_inserted) FROM pg_catalog.pg_stat_database) AS "Inserts",
   (SELECT sum(tup_updated) FROM pg_catalog.pg_stat_database) AS "Updates",
   (SELECT sum(tup_deleted) FROM pg_catalog.pg_stat_database) AS "Deletes"
) t
UNION ALL
SELECT 'to_stats' AS chart_name, pg_catalog.row_to_json(t) AS chart_data
FROM (SELECT
   (SELECT sum(tup_fetched) FROM pg_catalog.pg_stat_database) AS "Fetched",
   (SELECT sum(tup_returned) FROM pg_catalog.pg_stat_database) AS "Returned"
) t
UNION ALL
SELECT 'bio_stats' AS chart_name, pg_catalog.row_to_json(t) AS chart_data
FROM (SELECT
   (SELECT sum(blks_read) FROM pg_catalog.pg_stat_database) AS "Reads",
   (SELECT sum(blks_hit) FROM pg_catalog.pg_stat_database) AS "Hits"
) t

2021-08-05 12:15:48,236: ERROR  pgadmin:        'psycopg2.extensions.Column' object has no attribute '_asdict'
Traceback (most recent call last):
  File "/data/app/loader/ctvenv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/app/loader/ctvenv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/app/loader/ctvenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/data/app/loader/clients/clientpg/clientpg/web/pgadmin/dashboard/__init__.py", line 247, in wrap
    return f(*args, **kwargs)
  File "/data/app/loader/clients/clientpg/clientpg/web/pgadmin/dashboard/__init__.py", line 400, in dashboard_stats
    status, res = g.conn.execute_dict(sql)
  File "/data/app/loader/clients/clientpg/clientpg/web/pgadmin/utils/driver/psycopg2/connection.py", line 1312, in execute_dict
    columns = cur.description and [
  File "/data/app/loader/clients/clientpg/clientpg/web/pgadmin/utils/driver/psycopg2/connection.py", line 1313, in <listcomp>
    desc.to_dict() for desc in cur.ordered_description()
  File "/data/app/loader/clients/clientpg/clientpg/web/pgadmin/utils/driver/psycopg2/cursor.py", line 109, in to_dict
    ores = OrderedDict(self.orig_col._asdict())
AttributeError: 'psycopg2.extensions.Column' object has no attribute '_asdict'

**Comment by dpage** [comment]
Issue closed on Redmine.
