### ISSUE TITLE
Saved Passwords on Shared Servers Broken for Non-Admins (RM #6680)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4502]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6680***
*Originally created by **Jawala Birdi** at 2021-08-12 18:43:19 UTC.*

Clean install. Add a shared server as admin.
Login as an unprivileged user, set server Username under Properties > Connection. 
Try to connect - works. 

Disconnect Server (or logout) then (re)Connect Server, and encounter error : 

> not enough values to unpack (expected 3, got 2)

/var/log/pgadmin/pgadmin4.log says : 

<pre>
2021-08-12 18:29:47,801: ERROR  pgadmin:        'utf-8' codec can't decode byte 0xea in position 2: invalid continuation byte
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 245, in _decode_password
    password = password.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 2: invalid continuation byte
2021-08-12 18:29:47,801: ERROR  pgadmin:        not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 1404, in connect
    server_types=ServerType.types()
  File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 298, in connect
    password, crypt_key)
ValueError: not enough values to unpack (expected 3, got 2)
</pre>

<pre>
Version
5.6

Application Mode
Server

Browser
Firefox 90.0

Operating System
Linux-4.19.0-9-amd64-x86_64-with-debian-10.10
</pre>

NOTE that fetching saved passwords seem to work fine for the admin user (can disconnect, reconnect no problem).

**Comment by dpage** [comment]
Issue closed on Redmine.
