### ISSUE TITLE
Log in error after clean install in Kubernetes (RM #6705)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4522]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6705***
*Originally created by **Sebastian Büchler** at 2021-08-23 08:24:15 UTC.*

After following this tutorial (https://www.enterprisedb.com/blog/how-deploy-pgadmin-kubernetes) in order to deploy a pgAdmin4 instance in Kubernetes I get the following error in the log if I log in:
<pre><code class="python">
[ERROR] Error handling request
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 326, in handle_request
    resp.write_file(respiter)
  File "/venv/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
    if not self.sendfile(respiter):
  File "/venv/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
    self.sock.sendfile(respiter.filelike, count=nbytes)
  File "/usr/lib/python3.8/socket.py", line 482, in sendfile
    return self._sendfile_use_sendfile(file, offset, count)
  File "/usr/lib/python3.8/socket.py", line 346, in _sendfile_use_sendfile
    self._check_sendfile_params(file, offset, count)
  File "/usr/lib/python3.8/socket.py", line 460, in _check_sendfile_params
    raise ValueError(
ValueError: count must be a positive integer (got 0)
</code></pre>
My configuration through the ConfigMap (same as in the linked written tutorial) does also not seem to be applied, since the servers are not showing up in the left column of the initial view.
The used docker image is: https://hub.docker.com/r/dpage/pgadmin4/ with tag 5.6

Any idea why this error gets logged on a fresh deployment?

**Comment by dpage** [comment]
Issue closed on Redmine.
