### ISSUE TITLE
Error setting up server mode: sudo /usr/pgadmin4/bin/setup-web.sh (RM #6753)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4554]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6753***
*Originally created by **B2 Beh** at 2021-09-17 10:46:06 UTC.*

VM not connected to the web (downloaded rpm files to the VM manually)
Platform: CentOS Linux 7

Installation steps:
===================
cd /etc/yum.repos.d/
yum clean all
yum repolist
cat /etc/redhat-release 
rpm -ivh pgadmin4-server-4.30-1.el7.x86_64.rpm
cat /usr/pgadmin4/bin/setup-web.sh --->(not found)
rpm -ivh pgadmin4-desktop-4.30-1.el7.x86_64.rpm
rpm -ivh pgadmin4-web-4.30-1.el7.noarch.rpm

sudo /usr/pgadmin4/bin/setup-web.sh

Output: of (sudo /usr/pgadmin4/bin/setup-web.sh)
================================================
sudo /usr/pgadmin4/bin/setup-web.sh
Setting up pgAdmin 4 in web mode on a Redhat platform...
Creating configuration database...
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

Email address: 
Password:
Retype password:
Password must be at least 6 characters. Please try again.
Password:
Retype password:

Traceback (most recent call last):
  File "/usr/pgadmin4/web/setup.py", line 449, in <module>
    setup_db()
  File "/usr/pgadmin4/web/setup.py", line 372, in setup_db
    app = create_app()
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 431, in create_app
    driver.init_app(app)
  File "/usr/pgadmin4/web/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/usr/pgadmin4/web/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    import_module(module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg2/__init__.py", line 21, in <module>
    import psycopg2
  File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
	
ImportError: /usr/pgadmin4/venv/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PQconninfo
Error setting up server mode. Please examine the output above.

**Comment by dpage** [comment]
Issue closed on Redmine.
