### ISSUE TITLE
oauth2 + internal authentication failure when order is changed in config file (RM #6832)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4620]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6832***
*Originally created by **gregoireW w** at 2021-09-29 18:55:14 UTC.*

When I try to use @AUTHENTICATION_SOURCES = ['internal', 'oauth2']@ I can login with internal login/password but oauth2 will not work (loop on redirect to '/')  and finaly I end up with logs indicating session cannot be written to a file.

<pre><code class="python">
2021-09-29 20:45:57,754: INFO	werkzeug:	127.0.0.1 - - [29/Sep/2021 20:45:57] "GET /static/favicon.ico?ver=50700 HTTP/1.1" 200 -
2021-09-29 20:46:25,383: DEBUG	pgadmin:	Authentication initiated via source: oauth2
2021-09-29 20:46:25,385: INFO	werkzeug:	127.0.0.1 - - [29/Sep/2021 20:46:25] "POST /authenticate/login HTTP/1.1" 500 -
2021-09-29 20:46:25,389: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/workspace_python/pgadmin4/web/pgAdmin4.py", line 77, in __call__
    return self.app(environ, start_response)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/opt/workspace_python/pgadmin4/venv/lib/python3.9/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/opt/workspace_python/pgadmin4/web/pgadmin/utils/session.py", line 307, in save_session
    self.manager.put(session)
  File "/opt/workspace_python/pgadmin4/web/pgadmin/utils/session.py", line 166, in put
    self.parent.put(session)
  File "/opt/workspace_python/pgadmin4/web/pgadmin/utils/session.py", line 270, in put
    dump(
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed
</code>
</pre>

If I try to use @AUTHENTICATION_SOURCES = ['oauth2']@ this is ok and funny thing, If I exchange internal and oauth2 like: @AUTHENTICATION_SOURCES = ['oauth2', 'internal']@ it seems to work much better.

If I knew how redmine work, I would have reopened https://redmine.postgresql.org/issues/6594  but not sure it can be done so I created this new one.

**Comment by dpage** [comment]
Issue closed on Redmine.
