### ISSUE TITLE
pgAdmin 4 server could not be contacted  (RM #6854)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4640]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6854***
*Originally created by **tazoo tazoo** at 2021-10-01 19:59:23 UTC.*

Hello, 
I found this bug after installing on a Windows 10 laptop postgreSQL 14 and pgAdmin 4 v5.7 through the official site's installer. I searched for this problem and I have found the same question on stackoverflow.com (here the link https://stackoverflow.com/questions/68862998/the-pgadmin-4-server-could-not-be-contacted-fatal-error), but there isn't a real solution proposed. As they write on the stackotherflow post, on my Windows Registry there is an interface that contains a key "DhcpDomain" with the value ".home". If I delete or change this value, pgAdmin starts without any problem, but the value is resetted to ".home" after a new connection to the same wi-fi network and pgAdmin doesn't start again.

Here the traceback after the crash of pgAdmin:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\web\pgAdmin4.py", line 39, in <module>
    import config
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\web\config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\web\pgadmin\__init__.py", line 24, in <module>
    from flask_socketio import SocketIO
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\flask_socketio\__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\socketio\__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\socketio\zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\eventlet\support\greendns.py", line 401, in <module>
    resolver = ResolverProxy(hosts_resolver=HostsResolver())
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\eventlet\support\greendns.py", line 315, in __init__
    self.clear()
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\eventlet\support\greendns.py", line 318, in clear
    self._resolver = dns.resolver.Resolver(filename=self._filename)
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\dns\resolver.py", line 543, in __init__
    self.read_registry()
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\dns\resolver.py", line 720, in read_registry
    self._config_win32_fromkey(key, False)
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\dns\resolver.py", line 674, in _config_win32_fromkey
    self._config_win32_domain(dom)
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\dns\resolver.py", line 639, in _config_win32_domain
    self.domain = dns.name.from_text(str(domain))
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\dns\name.py", line 889, in from_text
    return from_unicode(text, origin, idna_codec)
  File "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\lib\site-packages\dns\name.py", line 852, in from_unicode
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.

**Comment by dpage** [comment]
Issue closed on Redmine.
