### ISSUE TITLE
Missing backup/restore progress dialogs on pgAdmin 4 6.0 (RM #6911)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4689]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6911***
*Originally created by **Beau Moore** at 2021-10-14 22:53:19 UTC.*

When I use the backup or restore options in pgAdmin 4 6.0 no progress indicator or status dialog pops with progress success or failure.

I should see this dialog: !https://www.pgadmin.org/static/docs/pgadmin4-dev/docs/en_US/_build/html/_images/restore_messages.png!

In the app frontend for pgAdmin log I see this error:
<pre>
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/bmoore/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - CLUTTER_IM_MODULE: xim
  - COMPIZ_CONFIG_PROFILE: ubuntu
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1071/bus
  - DEFAULTS_PATH: /usr/share/gconf/unity.default.path
  - DERBY_HOME: /usr/lib/jvm/java-8-oracle/db
  - DESKTOP_SESSION: unity
  - DISPLAY: :0
  - GDMSESSION: unity
  - GDM_LANG: en_US
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SESSION_XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
  - GPG_AGENT_INFO: /run/user/1071/gnupg/S.gpg-agent:0:1
  - GTK_CSD: 0
  - GTK_IM_MODULE: ibus
  - GTK_MODULES: gail:atk-bridge:unity-gtk-module
  - HOME: /home/bmoore
  - IM_CONFIG_PHASE: 2
  - J2REDIR: /usr/lib/jvm/java-8-oracle/jre
  - J2SDKDIR: /usr/lib/jvm/java-8-oracle
  - JAVA_HOME: /usr/lib/jvm/java-8-oracle
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US
  - LD_PRELOAD: libgtk3-nocsd.so.0
  - LOGNAME: bmoore
  - MANDATORY_PATH: /usr/share/gconf/unity.mandatory.path
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bmoore/.dotnet/tools:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
  - PWD: /home/bmoore
  - QT4_IM_MODULE: xim
  - QT_ACCESSIBILITY: 1
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/bmoore:@/tmp/.ICE-unix/11957,unix/bmoore:/tmp/.ICE-unix/11957
  - SHELL: /bin/bash
  - SHLVL: 1
  - SSH_AGENT_LAUNCHER: gnome-keyring
  - SSH_AUTH_SOCK: /run/user/1071/keyring/ssh
  - S_COLORS: auto
  - TEXTDOMAIN: im-config
  - TEXTDOMAINDIR: /usr/share/locale/
  - UNITY_DEFAULT_PROFILE: unity
  - UNITY_HAS_3D_SUPPORT: true
  - USER: bmoore
  - XAUTHORITY: /home/bmoore/.Xauthority
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-unity:/etc/xdg
  - XDG_CURRENT_DESKTOP: Unity:Unity7:ubuntu
  - XDG_DATA_DIRS: /usr/share/unity:/usr/local/share:/usr/share:/var/lib/snapd/desktop
  - XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/bmoore
  - XDG_MENU_PREFIX: gnome-
  - XDG_RUNTIME_DIR: /run/user/1071
  - XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
  - XDG_SESSION_DESKTOP: unity
  - XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
  - XDG_SESSION_TYPE: x11
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/dbus-update-activation-environment
  - MANAGERPID: 11617
  - INVOCATION_ID: cf6f48a57f8449df9d433f52e6686f38
  - JOURNAL_STREAM: 9:50727
  - COMPIZ_BIN_PATH: /usr/bin/
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 2720
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 38637
  - PGADMIN_INT_KEY: 48d02de6-d92f-4329-a485-103df0653b61
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

2021-10-14 18:29:52,179: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.

 * Serving Flask app "pgadmin" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

Application Server URL: http://127.0.0.1:38637/?key=48d02de6-d92f-4329-a485-103df0653b61
2021-10-14 18:29:56,634: ERROR	pgadmin:	'BackupMessage' object has no attribute 'args_str'
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/__init__.py", line 61, in index
    return make_response(response=BatchProcess.list())
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/processes.py", line 662, in list
    _check_process_desc(p)
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/processes.py", line 625, in _check_process_desc
    details = desc.details(p.command, args)
  File "/usr/pgadmin4/web/pgadmin/tools/backup/__init__.py", line 182, in details
    self.args_str.format(
AttributeError: 'BackupMessage' object has no attribute 'args_str'
</pre>

If I access PGAdmin directly in a browser I see these messages in the Chrome debugger:

<pre>
18:35:41.962 app.bundle.js:1 TypeError: n.init is not a function
    at t (app.bundle.js:1)
    at Object.<anonymous> (app.bundle.js:1)
    at Object.63586 (app.bundle.js:1)
    at u (app.bundle.js:1)
    at a (app.bundle.js:1)
    at Function.u.x (app.bundle.js:1)
    at app.bundle.js:1
    at app.bundle.js:1
    at Object.execCb (require.min.js?ver=60000:9)
    at i.check (require.min.js?ver=60000:9)
t @ app.bundle.js:1
18:35:41.962 app.bundle.js:1 TypeError: n.init is not a function
    at t (app.bundle.js:1)
    at Object.<anonymous> (app.bundle.js:1)
    at Object.63586 (app.bundle.js:1)
    at u (app.bundle.js:1)
    at a (app.bundle.js:1)
    at Function.u.x (app.bundle.js:1)
    at app.bundle.js:1
    at app.bundle.js:1
    at Object.execCb (require.min.js?ver=60000:9)
    at i.check (require.min.js?ver=60000:9)
t @ app.bundle.js:1
18:35:43.002 :38637/misc/bgprocess/?_=1634250941504:1 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
18:35:43.003 app.bundle.js:1 Arguments(3)
(anonymous) @ app.bundle.js:1
18:36:01.639 vendor.main.js?ver=60000:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ vendor.main.js?ver=60000:2
18:36:04.480 127.0.0.1/:1 Autofocus processing was blocked because a document already has a focused element.
18:36:04.521 :38637/static/js/generated/img/load-root.gif?ver=60000:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
18:36:51.419 :38637/misc/bgprocess/?_=1634250941505:1 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
18:36:51.420 app.bundle.js:1 Arguments(3)
(anonymous) @ app.bundle.js:1
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
