### ISSUE TITLE
Getting "TypeError: not enough arguments for format string" error message on terminal after latest git pull (RM #1509)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#473]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1509***
*Originally created by **Fahar Abbas** at 2016-07-26 05:38:00 UTC.*

Tested Plaform:
Ubuntu Linux 32 and Linux 64

Python version:
3.5 and 3.4

commit ID:

commit 790b28fb61df43aa8373b652b184bd14669b0abc

Tested Browser:
FireFox 46.0.1

Getting "TypeError: not enough arguments for format string" error message on terminal and loading of pgAdmin4 is in continuous loop after latest git pull.

python pgAdmin4.py 
Starting pgAdmin 4. Please navigate to http://localhost:5050 in your browser.
2016-07-25 22:31:49,075: ERROR	pgadmin:	Exception on /browser/js/messages.js [GET]
Traceback (most recent call last):
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/__init__.py", line 543, in messages_js
    render_template('browser/js/messages.js', _=gettext),
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/fahar/venv/lib/python3.5/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fahar/venv/lib/python3.5/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/templates/browser/js/messages.js", line 19, in <module>
    'MUST_GR_EQ' : "{{ _("'%s' must be greater than or equal to %d.")|safe }}",
  File "/home/fahar/venv/lib/python3.5/site-packages/flask_babel/__init__.py", line 461, in gettext
    return t.ugettext(string) % variables
TypeError: not enough arguments for format string
2016-07-25 22:31:49,101: ERROR	pgadmin:	Exception on /browser/js/node.js [GET]
Traceback (most recent call last):
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/__init__.py", line 535, in node_js
    _=gettext
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/fahar/venv/lib/python3.5/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fahar/venv/lib/python3.5/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/templates/browser/js/node.js", line 457, in <module>
    var msg = '{{ _('Are you sure want to stop editing the properties of %s "%s"?') }}';
  File "/home/fahar/venv/lib/python3.5/site-packages/flask_babel/__init__.py", line 461, in gettext
    return t.ugettext(string) % variables
TypeError: not enough arguments for format string

**Comment by dpage** [comment]
Issue closed on Redmine.
