### ISSUE TITLE
On demand rows throws error if any cell edit saved (RM #7005)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4765]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7005***
*Originally created by **Aditya Toshniwal** at 2021-11-16 12:14:04 UTC.*

I have set ON_DEMAND_RECORD_COUNT = 100 in my pgadmin config. When I edit any row cell and save it, and then scroll to get more rows, there is error in backend.

2021-11-16 17:41:30,094: ERROR	pgadmin:	object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/adityatoshniwal/venv/pypg38/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/adityatoshniwal/venv/pypg38/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/adityatoshniwal/venv/pypg38/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/adityatoshniwal/projects/pgadmin4_copy/web/pgadmin/tools/sqleditor/__init__.py", line 563, in fetch
    res_len = len(result)
TypeError: object of type 'NoneType' has no len()

**Comment by dpage** [comment]
Issue closed on Redmine.
