### ISSUE TITLE
With Python 3.10 eventlet==0.31.0 breaking the application (RM #7006)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4766]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7006***
*Originally created by **Rahul Shirsat** at 2021-11-17 08:28:51 UTC.*

When trying with Python 3.10 with eventlet 0.31.0, it breaks with -

<pre><code class="python">
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
</code></pre>

Above issue is fixed in the https://github.com/eventlet/eventlet/pull/715.

Work around was done trying with eventlet master dependency - 

 - https://github.com/eventlet/eventlet/archive/master.zip

And then with -

 - git+git://github.com/eventlet/eventlet.git@15d3c24

With the latest commit id 15d3c24 pgAdmin wheel is failing.

Approaches to solve -

1. Need to find a way to apply commit id appropriately for pgadmin wheel to generate successfully.
2. Directly use the latest release version of eventlet (not yet released)

**Comment by dpage** [comment]
Issue closed on Redmine.
