### ISSUE TITLE
TypeError: unhashable type: 'list' displayed If user Click on About (RM #7048)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4798]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7048***
*Originally created by **Fahar Abbas** at 2021-12-02 07:38:10 UTC.*

Snapshot Build:
--------------
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2021-12-02/

Commit ID:
commit 0f9b9b9dcfd2470df2ecd5619663276cdd5da039

Steps

1. Launch pgadmin4 
2. Click on Help
3. Click on About
Error Message displayed

Traceback (most recent call last):
  File "/Users/faharabbasmac1014/Projects/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/faharabbasmac1014/Projects/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/faharabbasmac1014/Projects/venv/lib/python3.9/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/faharabbasmac1014/Projects/pgadmin4/web/pgadmin/about/__init__.py", line 105, in index
    setting, gettext(getattr(config, setting)))
  File "/Users/faharabbasmac1014/Projects/venv/lib/python3.9/site-packages/flask_babel/__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/Users/faharabbasmac1014/Projects/venv/lib/python3.9/site-packages/flask_babel/__init__.py", line 587, in gettext
    s = t.ugettext(string)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/gettext.py", line 498, in gettext
    tmsg = self._catalog.get(message, missing)
TypeError: unhashable type: 'list'

**Comment by dpage** [comment]
Issue closed on Redmine.
