### ISSUE TITLE
pgAdmin throws internal server error for OAuth2 after some random idle time (RM #7059)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4807]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7059***
*Originally created by **Sebastian Siebert** at 2021-12-06 08:40:59 UTC.*

Hello pgAdmin 4 team,

we've a problem on implementing our Keycloak-SSO for pgadmin4.

Our infrastructure:

Kubernetes-cluster v1.20.6

Docker v20.10.6

Keycloak v8.0.2

pgadmin4 v6.2

After irregular time intervals pgadmin runs into an "internal server"-error and does not work anymore for some reason.
After restarting the container pgadmin is working fine again till the next randomly occurring of this error.

Can someone give me an hint on what could be the reason or how I could proceed with debugging here?
the additional configuration
config_local.py

<pre><code class="python">
# -*- coding: utf-8 -*-

##########################################################################
# OAuth 2.0 Configuration
##########################################################################

AUTHENTICATION_SOURCES = ['oauth2', 'internal']
OAUTH2_AUTO_CREATE_USER = True
OAUTH2_CONFIG = [{
'OAUTH2_NAME': 'sso',
'OAUTH2_DISPLAY_NAME': 'SSO',
'OAUTH2_CLIENT_ID': 'pgadmin',
'OAUTH2_CLIENT_SECRET': 'xxx',
'OAUTH2_TOKEN_URL': 'https://xxx',
'OAUTH2_AUTHORIZATION_URL': 'https://xxx',
'OAUTH2_API_BASE_URL': 'xxx',
'OAUTH2_USERINFO_ENDPOINT': 'xxx',
'OAUTH2_BUTTON_COLOR': '#3253a8',
}
]
##########################################################################
# Master password required
##########################################################################

MASTER_PASSWORD_REQUIRED = False

##########################################################################
# Ldap auto create user
##########################################################################

LDAP_AUTO_CREATE_USER = False

</code></pre>

the error log

<pre>

127.0.0.1 - - [30/Nov/2021:09:14:26 +0000] "DELETE /datagrid/close/7260576 HTTP/1.1" 200 74 "/datagrid/panel/7260576?is_query_tool=false&cmd_type=3&obj_type=table&obj_id=16400&sgid=6&sid=6&did=16385&server_type=pg" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
[2021-11-30 09:40:59 +0000] [89] [ERROR] Error handling request /authenticate/login 
Traceback (most recent call last): 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle 
    keepalive = self.handle_request(req, conn) 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request 
    respiter = self.wsgi(environ, resp.start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/pgadmin4/pgAdmin4.py", line 77, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__ 
    return super(_SocketIOMiddleware, self).__call__(environ, 
  File "/venv/lib/python3.9/site-packages/engineio/middleware.py", line 74, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app 
    response = self.handle_exception(e) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception 
    reraise(exc_type, exc_value, tb) 
  File "/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise 
    raise value 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request 
    return self.finalize_request(rv) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1970, in finalize_request 
    response = self.process_response(response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2269, in process_response 
    self.session_interface.save_session(self, ctx.session, response) 
  File "/pgadmin4/pgadmin/utils/session.py", line 307, in save_session 
    self.manager.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 166, in put 
    self.parent.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put 
    dump( 
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed 
::ffff:10.42.5.0 - - [30/Nov/2021:09:40:59 +0000] "POST /authenticate/login HTTP/1.1" 500 0 "-" "-" 
127.0.0.1 - - [30/Nov/2021:09:41:00 +0000] "GET /favicon.ico HTTP/1.1" 302 265 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
[2021-11-30 09:41:14 +0000] [89] [ERROR] Error handling request /authenticate/login 
Traceback (most recent call last): 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle 
    keepalive = self.handle_request(req, conn) 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request 
    respiter = self.wsgi(environ, resp.start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/pgadmin4/pgAdmin4.py", line 77, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__ 
    return super(_SocketIOMiddleware, self).__call__(environ, 
  File "/venv/lib/python3.9/site-packages/engineio/middleware.py", line 74, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app 
    response = self.handle_exception(e) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception 
    reraise(exc_type, exc_value, tb) 
  File "/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise 
    raise value 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request 
    return self.finalize_request(rv) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1970, in finalize_request 
    response = self.process_response(response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2269, in process_response 
    self.session_interface.save_session(self, ctx.session, response) 
  File "/pgadmin4/pgadmin/utils/session.py", line 307, in save_session 
    self.manager.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 166, in put 
    self.parent.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put 
    dump( 
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed 
::ffff:10.42.5.0 - - [30/Nov/2021:09:41:14 +0000] "POST /authenticate/login HTTP/1.1" 500 0 "-" "-" 
127.0.0.1 - - [30/Nov/2021:09:41:14 +0000] "GET /favicon.ico HTTP/1.1" 302 265 "/authenticate/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
127.0.0.1 - - [30/Nov/2021:09:41:19 +0000] "GET /favicon.ico?ver=60200 HTTP/1.1" 302 265 "/login?next=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
127.0.0.1 - - [30/Nov/2021:09:41:19 +0000] "GET /favicon.ico?ver=60200 HTTP/1.1" 302 265 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
[2021-11-30 09:41:21 +0000] [89] [ERROR] Error handling request /authenticate/login 
Traceback (most recent call last): 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle 
    keepalive = self.handle_request(req, conn) 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request 
    respiter = self.wsgi(environ, resp.start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/pgadmin4/pgAdmin4.py", line 77, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__ 
    return super(_SocketIOMiddleware, self).__call__(environ, 
  File "/venv/lib/python3.9/site-packages/engineio/middleware.py", line 74, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app 
    response = self.handle_exception(e) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception 
    reraise(exc_type, exc_value, tb) 
  File "/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise 
    raise value 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request 
    return self.finalize_request(rv) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1970, in finalize_request 
    response = self.process_response(response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2269, in process_response 
    self.session_interface.save_session(self, ctx.session, response) 
  File "/pgadmin4/pgadmin/utils/session.py", line 307, in save_session 
    self.manager.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 166, in put 
    self.parent.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put 
    dump( 
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed 
::ffff:10.42.5.0 - - [30/Nov/2021:09:41:21 +0000] "POST /authenticate/login HTTP/1.1" 500 0 "-" "-" 
127.0.0.1 - - [30/Nov/2021:09:53:43 +0000] "GET / HTTP/1.1" 302 237 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
127.0.0.1 - - [30/Nov/2021:09:53:48 +0000] "GET /static/favicon.ico?ver=60200 HTTP/1.1" 200 0 "/login?next=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 
[2021-11-30 09:53:49 +0000] [89] [ERROR] Error handling request /authenticate/login 
Traceback (most recent call last): 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle 
    keepalive = self.handle_request(req, conn) 
  File "/venv/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request 
    respiter = self.wsgi(environ, resp.start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/pgadmin4/pgAdmin4.py", line 77, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__ 
    return self.app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 43, in __call__ 
    return super(_SocketIOMiddleware, self).__call__(environ, 
  File "/venv/lib/python3.9/site-packages/engineio/middleware.py", line 74, in __call__ 
    return self.wsgi_app(environ, start_response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app 
    response = self.handle_exception(e) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception 
    reraise(exc_type, exc_value, tb) 
  File "/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise 
    raise value 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app 
    response = self.full_dispatch_request() 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request 
    return self.finalize_request(rv) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1970, in finalize_request 
    response = self.process_response(response) 
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 2269, in process_response 
    self.session_interface.save_session(self, ctx.session, response) 
  File "/pgadmin4/pgadmin/utils/session.py", line 307, in save_session 
    self.manager.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 166, in put 
    self.parent.put(session) 
  File "/pgadmin4/pgadmin/utils/session.py", line 270, in put 
    dump( 
_pickle.PicklingError: Can't pickle <class 'wtforms.form.Meta'>: attribute lookup Meta on wtforms.form failed 
::ffff:10.42.5.0 - - [30/Nov/2021:09:53:49 +0000] "POST /authenticate/login HTTP/1.1" 500 0 "-" "-" 
127.0.0.1 - - [30/Nov/2021:09:53:49 +0000] "GET /favicon.ico HTTP/1.1" 302 265 "/authenticate/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
