### ISSUE TITLE
Issue in Restore dialog (RM #7151)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4879]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7151***
*Originally created by **Nikhil Mohite** at 2022-02-03 10:26:59 UTC.*

Steps:
# Open restore dialog, select file.
# Disconnect server / remove server
# Click on the Restore button.
# Getting following issue 
<pre><code class="python">
Traceback (most recent call last):
  File "/Users/test_env_pg/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/test_env_pg/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/test_env_pg/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/pgadmin4/web/pgadmin/tools/restore/__init__.py", line 401, in create_restore_job
    is_error, errmsg, driver, manager, conn, \
ValueError: not enough values to unpack (expected 7, got 6)

</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
