### ISSUE TITLE
Missing backup/restore dialog on pgAdmin 4 6.5 (RM #7201)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4918]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7201***
*Originally created by **Beau Moore** at 2022-02-25 00:04:06 UTC.*

Using pgAdmin 4 6.5, no backup dialog or errors appear when initiating a back of a remote or local database.
The following appears int he Server log from the File | Runtime | View Log dialog.

I reported a similar issue about 4months ago here in Bug #6911 pgAdmin 4 6.0. However, I missed the emails asking for more details.

The comment to #6911 recomended trying with 4 6.5. The result of that is that no dialog or toast message now appear.

<pre>
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/bmoore/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - J2SDKDIR: /usr/lib/jvm/java-8-oracle
  - USER: bmoore
  - LANGUAGE: en_US
  - TEXTDOMAIN: im-config
  - XDG_SEAT: seat0
  - XDG_SESSION_TYPE: x11
  - SSH_AGENT_PID: 10935
  - J2REDIR: /usr/lib/jvm/java-8-oracle/jre
  - SHLVL: 0
  - QT4_IM_MODULE: xim
  - HOME: /home/bmoore
  - DESKTOP_SESSION: ubuntu
  - GTK_MODULES: gail:atk-bridge
  - XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1071/bus
  - MANDATORY_PATH: /usr/share/gconf/ubuntu.mandatory.path
  - IM_CONFIG_PHASE: 2
  - LOGNAME: bmoore
  - GTK_IM_MODULE: ibus
  - DEFAULTS_PATH: /usr/share/gconf/ubuntu.default.path
  - XDG_SESSION_ID: c2
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bmoore/.dotnet/tools:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
  - GDM_LANG: en_US
  - DERBY_HOME: /usr/lib/jvm/java-8-oracle/db
  - S_COLORS: auto
  - XDG_RUNTIME_DIR: /run/user/1071
  - XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
  - DISPLAY: :0
  - LANG: en_US.UTF-8
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XDG_SESSION_DESKTOP: ubuntu
  - XMODIFIERS: @im=ibus
  - XAUTHORITY: /home/bmoore/.Xauthority
  - XDG_GREETER_DATA_DIR: /var/lib/lightdm-data/bmoore
  - SSH_AUTH_SOCK: /run/user/1071/keyring/ssh
  - SHELL: /bin/bash
  - QT_ACCESSIBILITY: 1
  - GDMSESSION: ubuntu
  - TEXTDOMAINDIR: /usr/share/locale/
  - GPG_AGENT_INFO: /run/user/1071/gnupg/S.gpg-agent:0:1
  - XDG_VTNR: 7
  - QT_IM_MODULE: ibus
  - JAVA_HOME: /usr/lib/jvm/java-8-oracle
  - PWD: /home/bmoore
  - CLUTTER_IM_MODULE: xim
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - XDG_MENU_PREFIX: gnome-
  - SESSION_MANAGER: local/bmoore:@/tmp/.ICE-unix/10732,unix/bmoore:/tmp/.ICE-unix/10732
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 4144
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 45675
  - PGADMIN_INT_KEY: d0632c45-d781-4857-a0b3-4f81916d6099
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

2022-02-24 18:51:30,614: WARNING	werkzeug:	WebSocket transport not available. Install simple-websocket for improved performance.

 * Serving Flask app 'pgadmin' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

Application Server URL: http://127.0.0.1:45675/?key=d0632c45-d781-4857-a0b3-4f81916d6099
2022-02-24 18:51:34,126: ERROR	pgadmin:	'BackupMessage' object has no attribute 'args_str'
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/__init__.py", line 61, in index
    return make_response(response=BatchProcess.list())
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/processes.py", line 667, in list
    _check_process_desc(p)
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/processes.py", line 630, in _check_process_desc
    details = desc.details(p.command, args)
  File "/usr/pgadmin4/web/pgadmin/tools/backup/__init__.py", line 182, in details
    self.args_str.format(
AttributeError: 'BackupMessage' object has no attribute 'args_str'

2022-02-24 18:52:40,633: ERROR	pgadmin:	'BackupMessage' object has no attribute 'args_str'
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/pgadmin4/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/__init__.py", line 61, in index
    return make_response(response=BatchProcess.list())
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/processes.py", line 667, in list
    _check_process_desc(p)
  File "/usr/pgadmin4/web/pgadmin/misc/bgprocess/processes.py", line 630, in _check_process_desc
    details = desc.details(p.command, args)
  File "/usr/pgadmin4/web/pgadmin/tools/backup/__init__.py", line 182, in details
    self.args_str.format(
AttributeError: 'BackupMessage' object has no attribute 'args_str'
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
