### ISSUE TITLE
errors in log file (RM #7241)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4952]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7241***
*Originally created by **Ayad Mohamed** at 2022-03-14 11:02:00 UTC.*

Hi 
Is there an explination for these errors in the log file?
OS is ubuntu 20.0.4 pgadmin is 6.6
------------------------------------------

2022-03-11 13:47:50,209: ERROR  pgadmin:        400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
2022-03-11 13:47:50,225: ERROR  pgadmin:        400 Bad Request: The CSRF tokens do not match.
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
    raise ValidationError("The CSRF tokens do not match.")
wtforms.validators.ValidationError: The CSRF tokens do not match.

**Comment by dpage** [comment]
Issue closed on Redmine.
