### ISSUE TITLE
Unable to launch pgAdmin with python 3.10 & 3.9 (RM #7269)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4971]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7269***
*Originally created by **Yogesh Mahajan** at 2022-03-25 05:28:04 UTC.*

On launch getting error - 
<pre>
Traceback (most recent call last):
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/TestEnv/pgadmin4/web/pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/TestEnv/pgadmin4/web/pgadmin/__init__.py", line 233, in create_app
    app.jinja_env.trim_blocks = True
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/flask/helpers.py", line 777, in __get__
    return super().__get__(obj, type=type)
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/werkzeug/utils.py", line 97, in __get__
    value = self.fget(obj)  # type: ignore
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/flask/app.py", line 602, in jinja_env
    return self.create_jinja_environment()
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/flask/app.py", line 694, in create_jinja_environment
    rv = self.jinja_environment(self, **options)
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/flask/templating.py", line 42, in __init__
    BaseEnvironment.__init__(self, **options)
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/Users/yogeshmahajan/CodingGround/pgAdmin/DevEnv/Venv3104/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
