### ISSUE TITLE
'user_management.index' error while loggin in pgadmin4 (RM #7346)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5038]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7346***
*Originally created by **Virginia Vianna** at 2022-04-28 13:50:36 UTC.*

After starting *pgadmin4* from command line in *OpenSuse Tumbleweed* (Version "20220426") which was *recently updated* , I get the following error in Firefox browser:

<pre><code class="javascript">
success	0
errormsg	"'user_management.index'"
info	""
result	null
data	null
</code></pre>

and in command line I get the following: 

<pre><code class="python">
2022-04-28 10:38:23,671: ERROR	pgadmin:	'user_management.index'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 304, in inner
    return mfa_enabled(
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 169, in mfa_enabled
    return execute_if_enabled()
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 301, in if_else_func_inner
    return _func(first, second)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 243, in mfa_session_authenticated
    else unauthenticated()
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 301, in if_else_func_inner
    return _func(first, second)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 219, in mfa_user_registered
    not_registered()
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 301, in if_else_func_inner
    return _func(first, second)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 194, in mfa_user_force_registration_required
    not_register()
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/authenticate/mfa/utils.py", line 297, in execute_func
    return wrapped(*args, **kwargs)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/__init__.py", line 755, in index
    response = Response(render_template(
  File "/usr/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/browser/templates/browser/index.html", line 6, in top-level template code
    {% import 'browser/macros/static_user_icon.macro' as IMG with context %}
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/templates/base.html", line 55, in top-level template code
    'pgadmin.user_management.current_user': "{{ url_for('user_management.index') }}" + "current_user",
  File "/usr/lib/python3.8/site-packages/flask/helpers.py", line 309, in url_for
    appctx.app.inject_url_defaults(endpoint, values)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1816, in inject_url_defaults
    func(endpoint, values)
  File "/home/virginia/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/__init__.py", line 841, in add_internal_version
    urls = [url for url in app.url_map.iter_rules(endpoint)]
  File "/usr/lib/python3.8/site-packages/werkzeug/routing.py", line 1538, in iter_rules
    return iter(self._rules_by_endpoint[endpoint])
KeyError: 'user_management.index'
</code></pre>

I previously install and reinstalled pgadmin4 from [[https://software.opensuse.org/package/pgadmin4]]. Same error occurs before and after.

Pardon my ignorance, but I don't know elsewhere I can report this.
Thank you!

**Comment by dpage** [comment]
Issue closed on Redmine.
