### ISSUE TITLE
Exception display if select Font size less then 1 for SQL text (RM #1567)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#507]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1567***
*Originally created by **Fahar Abbas** at 2016-08-18 12:22:16 UTC.*

Tested Platform:
Windows 2012 server 64(Python 2.7.11)
MAC 10.9(Python 3.5)

Commit ID:
----------
commit 48a50ce20be3e6ebdacd0a9632b76ca6aba7cc1d

(venv) C:\Projects\pgadmin4\web>python pgAdmin4.py
Starting pgAdmin 4. Please navigate to http://localhost:5050 in your browser.
2016-08-18 18:15:06,456: ERROR  pgadmin:        Exception on /preferences/prefer
ences/60 [PUT]
Traceback (most recent call last):
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1988, in wsgi_app

    response = self.full_dispatch_request()
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1641, in full_dis
patch_request
    rv = self.handle_user_exception(e)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1544, in handle_u
ser_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1639, in full_dis
patch_request
    rv = self.dispatch_request()
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1625, in dispatch
_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\venv\lib\site-packages\flask_login.py", line 792, in decorat
ed_view
    return func(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\preferences\__init__.py", line 154, in
save
    res, msg = Preferences.save(data['mid'], data['cid'], data['id'], data['valu
e'])
  File "C:\Projects\pgadmin4\web\pgadmin\utils\preferences.py", line 535, in sav
e
    current_app.logger.exeception(e)
AttributeError: 'DebugLogger' object has no attribute 'exeception'

How I tested:
1. Launch pgAdmin4
2. Go into preferences
3. select font size 0.9 instead of  1
4. Execption displayed in terminal
5. and If user check the value this is still display 1 instead of change value

**Comment by dpage** [comment]
Issue closed on Redmine.
