### ISSUE TITLE
ERROR\tpgadmin:\t400 Bad Request: The CSRF session token is missing (RM #7390)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5074]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7390***
*Originally created by **Jan Birk** at 2022-05-17 11:30:53 UTC.*

Hi

Pgadmin 6.7 on a ubuntu server behind an F5 (SSL terminate).

I can see the issue has been disused before but no solution. We have a lot "The CSRF session token is missing" in the error.log file in our web installation. Here at midday we are seeing (from midnight)

root@pgadmin-2:/var/log/apache2# grep "Bad Request: The CSRF session token is missing" error.log | wc -l
*36056*

As for now we will have to restart apache2 several times a day and thereby terminate all user connection. We have a shit-storm "ordering" us to find another product. But pgadmin is a good product and we love the web-based idea. But it is not stable for us  - it has been some while ago however.

It dosn't look like an apache2 problem
--------------------------------------

Current Time: Tuesday, 17-May-2022 13:07:14 CEST
Restart Time: Monday, 16-May-2022 13:33:28 CEST
Parent Server Config. Generation: 2
Parent Server MPM Generation: 1
Server uptime: 23 hours 33 minutes 46 seconds
Server load: 0.25 0.23 0.12
Total accesses: 135055 - Total Traffic: 344.1 MB - Total Duration: 48036478
CPU Usage: u22.86 s23.34 cu752.81 cs104.19 - 1.06% CPU load
1.59 requests/sec - 4253 B/second - 2671 B/request - 355.681 ms/request
1 requests currently being processed, 74 idle workers

Slot	PID	Stopping	Connections 	Threads	Async connections
total	accepting	busy	idle	writing	keep-alive	closing
1	367919	no	1	yes	1	24	0	1	0
3	373024	no	2	yes	0	25	0	1	0
4	373057	no	1	yes	0	25	0	0	0
Sum	3	0	4	 	1	74	0	2	0

.........................______W__________________..............
...........__________________________________________________...
................................................................
................................................................
............................................

Scoreboard Key:
"_" Waiting for Connection, "S" Starting up, "R" Reading Request,
"W" Sending Reply, "K" Keepalive (read), "D" DNS Lookup,
"C" Closing connection, "L" Logging, "G" Gracefully finishing,
"I" Idle cleanup of worker, "." Open slot with no current process
-------------------------------------------------------------

If we have a closer look at the error, the logfile is full of:

-------------------------------------------------------------
During handling of the above exception, another exception occurred:
[Tue May 17 13:23:17.210593 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718] 
[Tue May 17 13:23:17.210601 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718] Traceback (most recent call last):
[Tue May 17 13:23:17.210610 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
[Tue May 17 13:23:17.210619 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]     rv = self.preprocess_request()
[Tue May 17 13:23:17.210628 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
[Tue May 17 13:23:17.210637 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]     rv = self.ensure_sync(before_func)()
[Tue May 17 13:23:17.210646 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[Tue May 17 13:23:17.210655 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]     self.protect()
[Tue May 17 13:23:17.210664 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 264, in protect
[Tue May 17 13:23:17.210699 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]     self._error_response(e.args[0])
[Tue May 17 13:23:17.210708 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]   File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[Tue May 17 13:23:17.210717 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718]     raise CSRFError(reason)
[Tue May 17 13:23:17.210727 2022] [wsgi:error] [pid 367918:tid 139915691312896] [remote 192.168.252.157:10718] flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
----------------------------------------------------------------

And since we are restarting apache2 several times a day it should / could not ?? be a CSRF timeout (24H). 

Do anybody have en idea what is happening ?

Best and Thanks

Jan

**Comment by dpage** [comment]
Issue closed on Redmine.
