### ISSUE TITLE
[Azure PostgreSQL] Cloud deployment failed for Azure PostgreSQL on Windows (RM #7498)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5163]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7498***
*Originally created by **Fahar Abbas** at 2022-06-22 12:18:19 UTC.*

Snapshot build:
---------------
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-06-22

Cloud deployment failed for Azure PostgreSQL on Windows

1. Open Azure PostgreSQL and Add valid credentials till end
2. Cloud deployment failed

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\pgacloud.py", line 94, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\pgacloud.py", line 84, in main
    providers = load_providers()
  File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\pgacloud.py", line 31, in load_providers
    module = __import__("providers." + basename[:-3],
ModuleNotFoundError: No module named 'providers'

!Screen%20Shot%202022-06-22%20at%204.35.47%20PM.png!

**Comment by dpage** [comment]
Issue closed on Redmine.
