### ISSUE TITLE
Postgres 14.4 test failure (RM #7527)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5185]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7527***
*Originally created by **Florian Brandes** at 2022-07-02 19:55:42 UTC.*

In the recent upgrade of Postgres from version 14.3 to 14.4, the decompilation of a view changed[1]:

"When decompiling a view or rule, show a SELECT output column's AS "?column?" alias clause if it could be referenced elsewhere (Tom Lane)"

This breaks the `regression.re_sql.tests.test_resql.ReverseEngineeredSQLTestCases` test:

<pre><code class="sql">
runTest (regression.re_sql.tests.test_resql.ReverseEngineeredSQLTestCases)
Reverse Engineered SQL Test Cases[  139.284721] postgres[5971]: [5971] WARNING:  changing the foreign-data wrapper validator can cause the options for dependent objects to become invalid
[  139.500468] postgres[5971]: [5971] WARNING:  wal_level is insufficient to publish logical changes
[  139.501412] postgres[5971]: [5971] HINT:  Set wal_level to logical before creating subscriptions.
 ... Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[225 chars]ECT 1\nWITH NO DATA;\n\nALTER TABLE IF EXISTS [145 chars]1\';' != '-- V[225 chars]ECT 1 AS "?column?"\nWITH NO DATA;\n\nALTER TA[159 chars]1\';'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  TABLESPACE pg_default
  AS
-  SELECT 1
+  SELECT 1 AS "?column?"
  WITH NO DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[225 chars]ECT 1\nWITH NO DATA;\n\nALTER TABLE IF EXISTS [283 chars]LIC;' != '-- V[225 chars]ECT 1 AS "?column?"\nWITH NO DATA;\n\nALTER TA[297 chars]LIC;'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  TABLESPACE pg_default
  AS
-  SELECT 1
+  SELECT 1 AS "?column?"
  WITH NO DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
  GRANT ALL ON TABLE public."testmview_$%{}[]()&*^!/@`#" TO postgres;
  GRANT ALL ON TABLE public."testmview_$%{}[]()&*^!/@`#" TO PUBLIC;
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[225 chars]ECT 1\nWITH NO DATA;\n\nALTER TABLE IF EXISTS [216 chars]res;' != '-- V[225 chars]ECT 1 AS "?column?"\nWITH NO DATA;\n\nALTER TA[230 chars]res;'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  TABLESPACE pg_default
  AS
-  SELECT 1
+  SELECT 1 AS "?column?"
  WITH NO DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
  GRANT ALL ON TABLE public."testmview_$%{}[]()&*^!/@`#" TO postgres;
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[225 chars]ECT 1\nWITH NO DATA;\n\nALTER TABLE IF EXISTS [214 chars]LIC;' != '-- V[225 chars]ECT 1 AS "?column?"\nWITH NO DATA;\n\nALTER TA[228 chars]LIC;'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  TABLESPACE pg_default
  AS
-  SELECT 1
+  SELECT 1 AS "?column?"
  WITH NO DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
  GRANT ALL ON TABLE public."testmview_$%{}[]()&*^!/@`#" TO PUBLIC;
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[226 chars]CT 12\nWITH NO DATA;\n\nALTER TABLE IF EXISTS [145 chars]1\';' != '-- V[226 chars]CT 12 AS "?column?"\nWITH NO DATA;\n\nALTER TA[159 chars]1\';'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  TABLESPACE pg_default
  AS
-  SELECT 12
+  SELECT 12 AS "?column?"
  WITH NO DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[258 chars]CT 12\nWITH DATA;\n\nALTER TABLE IF EXISTS pub[142 chars]1\';' != '-- V[258 chars]CT 12 AS "?column?"\nWITH DATA;\n\nALTER TABLE[156 chars]1\';'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  WITH (
      FILLFACTOR = 18
  )
  TABLESPACE pg_default
  AS
-  SELECT 12
+  SELECT 12 AS "?column?"
  WITH DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[334 chars]CT 12\nWITH DATA;\n\nALTER TABLE IF EXISTS pub[142 chars]1\';' != '-- V[334 chars]CT 12 AS "?column?"\nWITH DATA;\n\nALTER TABLE[156 chars]1\';'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  WITH (
      FILLFACTOR = 18,
      autovacuum_enabled = TRUE,
      autovacuum_analyze_scale_factor = 0.2
  )
  TABLESPACE pg_default
  AS
-  SELECT 12
+  SELECT 12 AS "?column?"
  WITH DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 525, in check_re_sql
    self.assertEqual(sql, resp_sql)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/nix/store/i6svmmq24wl4i10dx0m8blrpl3m3fq4b-python3-3.10.5/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: '-- V[258 chars]CT 12\nWITH DATA;\n\nALTER TABLE IF EXISTS pub[142 chars]1\';' != '-- V[258 chars]CT 12 AS "?column?"\nWITH DATA;\n\nALTER TABLE[156 chars]1\';'
  -- View: public.testmview_$%{}[]()&*^!/@`#
  -- DROP MATERIALIZED VIEW IF EXISTS public."testmview_$%{}[]()&*^!/@`#";
  CREATE MATERIALIZED VIEW IF NOT EXISTS public."testmview_$%{}[]()&*^!/@`#"
  WITH (
      FILLFACTOR = 18
  )
  TABLESPACE pg_default
  AS
-  SELECT 12
+  SELECT 12 AS "?column?"
  WITH DATA;
  ALTER TABLE IF EXISTS public."testmview_$%{}[]()&*^!/@`#"
      OWNER TO postgres;
  COMMENT ON MATERIALIZED VIEW public."testmview_$%{}[]()&*^!/@`#"
      IS 'comment1';
[  149.194811] postgres[5971]: [5971] WARNING:  tables were not subscribed, you will have to run ALTER SUBSCRIPTION ... REFRESH PUBLICATION to subscribe the tables
FAIL
======================================================================
FAIL: runTest (regression.re_sql.tests.test_resql.ReverseEngineeredSQLTestCases)
Reverse Engineered SQL Test Cases
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pgadmin/pgadmin4-6.11/web/regression/re_sql/tests/test_resql.py", line 148, in runTest
    self.assertEqual(self.final_test_status, True)
AssertionError: False != True
----------------------------------------------------------------------
Ran 1388 tests in 111.699s
FAILED (failures=1, skipped=133)
</code></pre>

[1] https://www.postgresql.org/docs/release/14.4/

**Comment by dpage** [comment]
Issue closed on Redmine.
