### ISSUE TITLE
User Management not working in dockerized pgadmin4 6.11 (RM #7549)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5203]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7549***
*Originally created by **Bjørn S.** at 2022-07-12 11:07:00 UTC.*

When opening the User Management Window, the user list is empty.
The log shows following error
<pre>
2022-07-12 11:04:15,767: ERROR	pgadmin:	list index out of range
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/venv/lib/python3.9/site-packages/flask_security/decorators.py", line 482, in decorated_view
    return fn(*args, **kwargs)
  File "/pgadmin4/pgadmin/tools/user_management/__init__.py", line 229, in user
    'role': u.roles[0].id,
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
