### ISSUE TITLE
Schema diff fails with: column "none" does not exist (RM #7591)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5237]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7591***
*Originally created by **Pocin Pocin** at 2022-08-03 11:53:02 UTC.*

I have a canonical schema.sql and a folder of migrations.
When making a new migration I `psql -f schema.sql` in `postgres` database and on the same server i create `postgres_migrations` database. I then load all existing migrations into `postgres_migrations`.
Then I run the pgadmin diff tool to create a new diff. This has worked flawlessy so far, but this time I am getting this (with debug log enabled)
<pre>

2022-08-03 13:43:22,252: SQL    pgadmin:        Execute (dict) by pgadmin4@pgadmin.org on postgres@localhost/postgres_migrations #1 - DB:postgres_migrations (Query-id: 2838985):
SELECT
    pl.oid AS oid,
    pl.polname AS name,
    rw.permissive as type,
    rw.cmd AS event,
    rw.qual AS using,
    rw.qual AS using_orig,
    rw.with_check AS withcheck,
    rw.with_check AS withcheck_orig,

    pg_catalog.array_to_string(rw.roles::name[], ', ') AS policyowner
FROM
    pg_catalog.pg_policy pl
JOIN pg_catalog.pg_policies rw ON pl.polname=rw.policyname
JOIN pg_catalog.pg_namespace n ON n.nspname=rw.schemaname
JOIN pg_catalog.pg_class rel on rel.relname=rw.tablename
WHERE
      pl.oid = 20216 and n.oid = 19771 and rel.oid = None;

2022-08-03 13:43:22,256: ERROR  pgadmin:        Failed to execute query (execute_dict) for the server #1- DB:postgres_migrations (Query-id: 2838985):
Error Message:ERROR:  column "none" does not exist
LINE 18:       pl.oid = 20216 and n.oid = 19771 and rel.oid = None;
                                                              ^

2022-08-03 13:43:22,256: ERROR  pgadmin:        cannot unpack non-iterable Response object
Traceback (most recent call last):
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/schema_diff/__init__.py", line 552, in compare_database
    compare_schema_objects(
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/schema_diff/__init__.py", line 862, in compare_schema_objects
    res = view.compare(source_sid=source_sid,
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/schema_diff_utils.py", line 80, in compare
    return compare_dictionaries(view_object=self,
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/schema_diff/directory_compare.py", line 441, in compare_dictionaries
    identical, different = _get_identical_and_different_list(
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/tools/schema_diff/directory_compare.py", line 317, in _get_identical_and_different_list
    diff_ddl = view_object.get_sql_from_submodule_diff(
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/schema_diff_utils.py", line 348, in get_sql_from_submodule_diff
    diff = self._compare_source_and_target(
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/schema_diff_utils.py", line 401, in _compare_source_and_target
    diff_ddl = module_view.ddl_compare(
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/row_security_policies/__init__.py", line 736, in ddl_compare
    diff = self.get_sql_from_diff(gid=tgt_params['gid'],
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/row_security_policies/__init__.py", line 212, in wrap
    return f(*args, **kwargs)
  File "/Applications/pgAdmin 4.app/Contents/Resources/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/row_security_policies/__init__.py", line 618, in get_sql_from_diff
    sql, name = row_security_policies_utils.get_sql(
TypeError: cannot unpack non-iterable Response object
</pre>

I think this is tied to some RLS policy I just created, but not sure which one exactly (there is quite a few of them). Is there an easy way to pintpoint it so i can create reproducible example?

I am on 
<pre>

Version 6.12
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.62.2
Browser Chromium 99.0.4844.84
Operating System macOS-12.0-x86_64-i386-64bit

</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
