### ISSUE TITLE
Error "The CSRF tokens do not match." (RM #7599)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5243]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7599***
*Originally created by **Sally XIE** at 2022-08-08 08:24:08 UTC.*

We are running pgadmin docker version 6.11 at AWS Cloud using ECS.
In front of the pgadmin app, we have an oath proxy integrated with Azure AD.
But recently, it keeps reporting the CSRF error, and the proxy's logs showing unable to connect to upstream server. 
Then all users get 502, we have to restart the pgadmin and clear all sessions.
It brings very much trouble to us. 

Could you pls help with looking into this issue?

2022-08-08T15:40:28.171+08:00

复制
Traceback (most recent call last):
Traceback (most recent call last):

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 261, in protect
File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 261, in protect

2022-08-08T15:40:28.171+08:00

复制
    validate_csrf(self._get_csrf_token())
validate_csrf(self._get_csrf_token())

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf
File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 115, in validate_csrf

2022-08-08T15:40:28.171+08:00

复制
    raise ValidationError("The CSRF tokens do not match.")
raise ValidationError("The CSRF tokens do not match.")

2022-08-08T15:40:28.171+08:00

复制
wtforms.validators.ValidationError: The CSRF tokens do not match.
wtforms.validators.ValidationError: The CSRF tokens do not match.

2022-08-08T15:40:28.171+08:00

复制
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:

2022-08-08T15:40:28.171+08:00

复制
Traceback (most recent call last):
Traceback (most recent call last):

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1521, in full_dispatch_request
File "/venv/lib/python3.9/site-packages/flask/app.py", line 1521, in full_dispatch_request

2022-08-08T15:40:28.171+08:00

复制
    rv = self.preprocess_request()
rv = self.preprocess_request()

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1861, in preprocess_request
File "/venv/lib/python3.9/site-packages/flask/app.py", line 1861, in preprocess_request

2022-08-08T15:40:28.171+08:00

复制
    rv = self.ensure_sync(before_func)()
rv = self.ensure_sync(before_func)()

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect

2022-08-08T15:40:28.171+08:00

复制
    self.protect()
self.protect()

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 264, in protect
File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 264, in protect

2022-08-08T15:40:28.171+08:00

复制
    self._error_response(e.args[0])
self._error_response(e.args[0])

2022-08-08T15:40:28.171+08:00

复制
  File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 307, in _error_response
File "/venv/lib/python3.9/site-packages/flask_wtf/csrf.py", line 307, in _error_response

2022-08-08T15:40:28.171+08:00

复制
    raise CSRFError(reason)
raise CSRFError(reason)

2022-08-08T15:40:28.171+08:00

复制
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF tokens do not match.

**Comment by dpage** [comment]
Issue closed on Redmine.
