### ISSUE TITLE
[Azure PostgreSQL] Cloud Deployment failed for Azure PostgreSQL (RM #7617)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5258]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7617***
*Originally created by **Fahar Abbas** at 2022-08-16 08:03:17 UTC.*

Build:
------
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-08-16/

1. Follow all instructions of cloud instance for Azure PostgreSQL
2. It is failing

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FR8QX5ELE to authenticate.
DeviceCodeCredential.get_token failed: Timed out waiting for the user to authenticate
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\pgacloud.py", line 95, in <module>
main()
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\pgacloud.py", line 91, in main
execute_command(providers, parser, args)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\pgacloud.py", line 71, in execute_command
command(args)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\providers\azure.py", line 338, in cmd_create_instance
rg = self._create_resource_group(args)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\web\pgacloud\providers\azure.py", line 218, in _create_resource_group
for group in list(group_list):
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\paging.py", line 128, in __next__
return next(self._page_iterator)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\paging.py", line 76, in __next__
self._response = self._get_next(self.continuation_token)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\mgmt\resource\resources\v2021_04_01\operations\_resource_groups_operations.py", line 811, in get_next
pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
return first_node.send(pipeline_request) # type: ignore
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
response = self.next.send(request)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
response = self.next.send(request)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
response = self.next.send(request)
[Previous line repeated 2 more times]
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\mgmt\core\policies\_base.py", line 47, in send
response = self.next.send(request)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
response = self.next.send(request)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 446, in send
response = self.next.send(request)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 117, in send
self.on_request(request)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 94, in on_request
self._token = self._credential.get_token(*self._scopes)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\identity\_internal\interactive.py", line 147, in get_token
result = self._request_token(*scopes, **kwargs)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\identity\_internal\decorators.py", line 74, in wrapper
return fn(*args, **kwargs)
File "C:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\python\lib\site-packages\azure\identity\_credentials\device_code.py", line 99, in _request_token
raise ClientAuthenticationError(message="Timed out waiting for user to authenticate")
azure.core.exceptions.ClientAuthenticationError: Timed out waiting for user to authenticate

**Comment by dpage** [comment]
Issue closed on Redmine.
