### ISSUE TITLE
pgAdmin4 not starting on kubuntu 22.04: "The pgAdmin 4 server could not be contacted" (RM #7634)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5272]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7634***
*Originally created by **Thomas Landauer** at 2022-08-22 23:21:23 UTC.*

Well, after https://redmine.postgresql.org/issues/6278 I'm having no luck again ;-) This time I upgraded to kubuntu 22.04.

The "Fatal Error" window says:
> pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"

When I run this in a console, I'm getting:
<pre>
$ /usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 38, in <module>
    import config
  File "/usr/pgadmin4/web/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 23, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'
</pre>

The file `/usr/pgadmin4/venv/bin/python3` is a symlink to `/usr/bin/python3.10` (used to be python3.8 in kubuntu 20.04)

And starting python in a console looks good to me:
<pre>
$ python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
</pre>

I already tried reinstalling pgAdmin (taken from https://www.pgadmin.org/download/pgadmin-4-apt/), but that didn't change anything:
<pre>
$ sudo curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
$ sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
$ sudo apt install pgadmin4-desktop
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
