### ISSUE TITLE
Change password fail on current 6.13 version (Test and User UI) (RM #7648)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5286]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7648***
*Originally created by **Florian Brandes** at 2022-08-27 21:49:57 UTC.*

I am getting the following error when running the test suite:

<pre>
machine # runTest (pgadmin.browser.tests.test_change_password.ChangePasswordTestCase)
machine # TestCase for Changing Valid_Password ... 2022-08-27 21:14:55,077: ERROR       pgadmin:        405 Method Not Allowed: The method is not allowed for the requested URL.
machine # Traceback (most recent call last):
machine #   File "/nix/store/hkn49wv1hiq5yjmn05kcd8gjganaky81-python3-3.10.6-env/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
machine #     rv = self.dispatch_request()
machine #   File "/nix/store/hkn49wv1hiq5yjmn05kcd8gjganaky81-python3-3.10.6-env/lib/python3.10/site-packages/flask/app.py", line 1493, in dispatch_request
machine #     self.raise_routing_exception(req)
machine #   File "/nix/store/hkn49wv1hiq5yjmn05kcd8gjganaky81-python3-3.10.6-env/lib/python3.10/site-packages/flask/app.py", line 1475, in raise_routing_exception
machine #     raise request.routing_exception  # type: ignore
machine #   File "/nix/store/hkn49wv1hiq5yjmn05kcd8gjganaky81-python3-3.10.6-env/lib/python3.10/site-packages/flask/ctx.py", line 397, in match_request
machine #     result = self.url_adapter.match(return_rule=True)  # type: ignore
machine #   File "/nix/store/hkn49wv1hiq5yjmn05kcd8gjganaky81-python3-3.10.6-env/lib/python3.10/site-packages/werkzeug/routing.py", line 2042, in match
machine #     raise MethodNotAllowed(valid_methods=list(have_match_for))
machine # werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
machine # ERROR
</pre>

All other test pass. I am also not able to change the admin password using the "users" menu or during with "Change password" dialog.

In the "users" menu I was able to change my own password with version 6.12. Now it is just grayed out.
In both versions (6.12 and 6.13) I am getting an SMTP error 111 when trying to use the "Change password" dialog.

**Comment by dpage** [comment]
Issue closed on Redmine.
