### ISSUE TITLE
Startup error on Fedora 24 box (RM #1635)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#564]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1635***
*Originally created by **Devrim Gündüz** at 2016-09-02 12:28:51 UTC.*

Hi,

I am trying to RPMify pgadmin4. I started pgadmin4 on commandline as seen below, but then when I visit the web interface, I get the error below. On website, it throws 500.
<pre>
[root@asus-laptop-03-gunduz-org ~]# python3 /usr/lib/python3.5/site-packages/pgadmin4-web/pgAdmin4.py 
Starting pgAdmin 4. Please navigate to http://localhost:5050 in your browser.
2016-09-02 15:23:50,411: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1470, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1497, in try_trigger_before_first_request_functions
    func()
  File "/usr/lib/python3.5/site-packages/pgadmin4-web/pgadmin/utils/__init__.py", line 42, in create_module_preference
    self.register_preferences()
  File "/usr/lib/python3.5/site-packages/pgadmin4-web/pgadmin/tools/sqleditor/__init__.py", line 137, in register_preferences
    help_str=gettext('The font size to use for the SQL text boxes and editors. '
  File "/usr/lib/python3.5/site-packages/flask_babel/__init__.py", line 461, in gettext
    return t.ugettext(string) % variables
TypeError: %u format: a number is required, not dict

</pre>

When I try to reload the web page again, I get:

<pre>
2016-09-02 15:26:55,474: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask_login.py", line 786, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pgadmin4-web/pgadmin/browser/__init__.py", line 575, in browser_css
    sql_font_size = round(float(sql_font_size_pref.get()), 2)
AttributeError: 'NoneType' object has no attribute 'get'
2016-09-02 15:26:55,639: ERROR	werkzeug:	Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.5/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask_login.py", line 786, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pgadmin4-web/pgadmin/browser/__init__.py", line 501, in browser_js
    editor_tab_size = editor_tab_size_pref.get()
AttributeError: 'NoneType' object has no attribute 'get'
</pre>

This is Python 3.5, Flask 0.10, python3-werkzeug-0.11.1,  

What am I missing?

Regards, Devrim

**Comment by dpage** [comment]
Issue closed on Redmine.
