### ISSUE TITLE
pgAdmin4 does not work with Python 2.6 (RM #1636)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#565]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1636***
*Originally created by **Laurenz Albe** at 2016-09-02 12:49:21 UTC.*

The README states that "Python 2.6 or above" is required.

But this causes the error:

Traceback (most recent call last):
  File "/MYSQL/mysqldata/fs1/rpmbuild/pgadmin4-1.0-beta3/web/pgAdmin4.py", line 24, in <module>
    from pgadmin import create_app
  File "/MYSQL/mysqldata/fs1/rpmbuild/pgadmin4-1.0-beta3/web/pgadmin/__init__.py", line 281
    arch_keys = {0}
                  ^
SyntaxError: invalid syntax

See https://www.postgresql.org/message-id/A737B7A37273E048B164557ADEF4A58B5388C035%40ntex2010i.host.magwien.gv.at

**Comment by dpage** [comment]
Issue closed on Redmine.
