### ISSUE TITLE
[Web Based]  User has to wait for 5 and 10 minutes to see actual result if create table without column  (RM #1677)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#588]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1677***
*Originally created by **Fahar Abbas** at 2016-09-09 06:44:25 UTC.*

Tested Platform:
Ubuntu 16.04 Linux 64(Python 3.5)

Tested Server:
EPAS9.6 server

Commit ID:
----------
commit 982c291a31da13581ba4ee8ea345f04f60a175b7

If user create table without column, it's created and when user see the view data to retrieve information, User has to wait for 5 and 10 minutes to see actual result, exception is also displayed related to Exception in thread Thread-398:
Step:
1. Launch pgAdmin4
2. Add EPAS-9.6 server(you can pick from daily build)
3. Server added successfully
4. Expand table node
5. Right Click and create new table with qmg without giving any column
6. Click on Save Button
7. Table created
8. Right Click and select View data
9. Message displayed Retrieving about the column Returned...
10. After this operation User has to wait for 5 and 10 minutes to see actual result
11. Exception displayed

Exception in thread Thread-398:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/fahar/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fahar/venv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 534, in fetch_pg_types
    for col in session_obj['columns_info']:
KeyError: 'columns_info'

**Comment by dpage** [comment]
Issue closed on Redmine.
