### ISSUE TITLE
Python error following application server restart (RM #1707)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#612]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1707***
*Originally created by **Dave Page** at 2016-09-16 14:59:43 UTC.*

I see this on my console:

2016-09-16 15:57:47,834: INFO	werkzeug:	127.0.0.1 - - [16/Sep/2016 15:57:47] "POST /misc/ping HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dpage/git/pgadmin4/web/pgadmin/misc/__init__.py", line 63, in ping
    driver.ping()
  File "/Users/dpage/git/pgadmin4/web/pgadmin/utils/driver/__init__.py", line 49, in ping
    drivers[type].gc()
  File "/Users/dpage/git/pgadmin4/web/pgadmin/utils/driver/psycopg2/__init__.py", line 1738, in gc
    if sess == session['_id']:
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/werkzeug/local.py", line 373, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: '_id'

**Comment by dpage** [comment]
Issue closed on Redmine.
