### ISSUE TITLE
Auto-complete is broken (RM #1725)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#619]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1725***
*Originally created by **Dave Page** at 2016-09-22 11:22:19 UTC.*

2016-09-22 12:21:33,523: INFO	werkzeug:	127.0.0.1 - - [22/Sep/2016 12:21:33] "POST /sqleditor/autocomplete/3175456 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/dpage/git/pgadmin4/web/pgadmin/tools/sqleditor/__init__.py", line 1006, in auto_complete
    res = auto_complete_obj.get_completions(full_sql, text_before_cursor)
  File "/Users/dpage/git/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 239, in get_completions
    suggestions = self.suggest_type(text, text_before_cursor)
  File "/Users/dpage/git/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 671, in suggest_type
    full_text, identifier)
  File "/Users/dpage/git/pgadmin4/web/pgadmin/utils/sqlautocomplete/autocomplete.py", line 709, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'

**Comment by dpage** [comment]
Issue closed on Redmine.
