### ISSUE TITLE
[Web Based]   Exception displayed when user click on Leave page under upload file section for save query option (RM #1739)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#630]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1739***
*Originally created by **Fahar Abbas** at 2016-09-23 12:58:07 UTC.*

Tested Platform:
MAC 10.9(Python 3.5)

Browser:
Safari

Commit ID:
----------
commit 5c855234f865d61e034196830f9afd7bdd391607

Steps:

1.Launch pgAdmin4 on MAC OS X 
2. Click on Database postgres 
3. Launch Query tool window 
4. write select * from  emp;
5. Click on Save Button
6. Click on Upload file
7. pop up message displayed in Are you want to leave this page
8. Click on Leave Page
9. Now user can not cancel the query through cross bar
10. Exception displayed at backend

Exception in thread Thread-1134:

    Traceback (most recent call last):

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner

        self.run()

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run

        self._target(*self._args, **self._kwargs)

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 628, in process_request_thread

        self.handle_error(request, client_address)

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 625, in process_request_thread

        self.finish_request(request, client_address)

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 354, in finish_request

        self.RequestHandlerClass(request, client_address, self)

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 681, in __init__

        self.handle()

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 200, in handle

        rv = BaseHTTPRequestHandler.handle(self)

      File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 422, in handle

        self.handle_one_request()

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 235, in handle_one_request

        return self.run_wsgi()

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 177, in run_wsgi

        execute(self.server.app)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 165, in execute

        application_iter = app(environ, start_response)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__

        return self.wsgi_app(environ, start_response)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app

        response = self.make_response(self.handle_exception(e))

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception

        reraise(exc_type, exc_value, tb)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

        raise value

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app

        response = self.full_dispatch_request()

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request

        rv = self.handle_user_exception(e)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception

        reraise(exc_type, exc_value, tb)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

        raise value

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request

        rv = self.dispatch_request()

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request

        return self.view_functions[rule.endpoint](**req.view_args)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view

        return func(*args, **kwargs)

      File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 802, in file_manager

        kwargs = json.loads(req.data)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/simplejson/__init__.py", line 505, in loads

        return _default_decoder.decode(s)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode

        obj, end = self.raw_decode(s)

      File "/Users/faharmav/myenv/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode

        return self.scan_once(s, idx=_w(s, idx).end())

    simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expected result:
-------------------
Exception should not thrown.

Actual result:
--------------
Exception displayed at backend when user click on Leave page under upload file section in Save query option

**Comment by dpage** [comment]
Issue closed on Redmine.
