### ISSUE TITLE
"Connection to the server has been lost message" displayed with range and external types (RM #1795)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#674]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1795***
*Originally created by **Fahar Abbas** at 2016-10-03 04:28:03 UTC.*

Commit:
-------
commit a91f19a21d1d04cfe9cdc1e1b9c9461f3961fb64

Step:

1. Lunch pgAdmin4
2. Connect to pg-9.6 server
3. Expand Type node
4. create new Type
5. Provide name
6. Click on Definition 
7. select type range
8. Click on Save Button
9. Connection to the server has been lost message displayed

(venv) C:\Projects\pgadmin4\web>python pgAdmin4.py
Starting pgAdmin 4. Please navigate to http://localhost:5050 in your browser.
Exception in thread Thread-1733:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\Lib\SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python27\Lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\Lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Projects\venv\lib\site-packages\werkzeug\serving.py", line 200, in ha
ndle
    rv = BaseHTTPRequestHandler.handle(self)
  File "c:\python27\Lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Projects\venv\lib\site-packages\werkzeug\serving.py", line 235, in ha
ndle_one_request
    return self.run_wsgi()
  File "C:\Projects\venv\lib\site-packages\werkzeug\serving.py", line 177, in ru
n_wsgi
    execute(self.server.app)
  File "C:\Projects\venv\lib\site-packages\werkzeug\serving.py", line 165, in ex
ecute
    application_iter = app(environ, start_response)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 2000, in __call__

    return self.wsgi_app(environ, start_response)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1991, in wsgi_app

    response = self.make_response(self.handle_exception(e))
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1567, in handle_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1988, in wsgi_app

    response = self.full_dispatch_request()
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1641, in full_dis
patch_request
    rv = self.handle_user_exception(e)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1544, in handle_u
ser_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1639, in full_dis
patch_request
    rv = self.dispatch_request()
  File "C:\Projects\venv\lib\site-packages\flask\app.py", line 1625, in dispatch
_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\venv\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\browser\utils.py", line 235, in dispatc
h_request
    return method(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\browser\server_groups\servers\databases
\schemas\types\__init__.py", line 237, in wrap
    return f(*args, **kwargs)
  File "C:\Projects\pgadmin4\web\pgadmin\browser\server_groups\servers\databases
\schemas\types\__init__.py", line 875, in create
    if data['typname'] is None:
KeyError: 'typname'

Expected Result:
----------------
Save Button should not enabled if user does not specify any option while selecting range type

Actual Result:
--------------
"Connection to the server has been lost" displayed if select range type without any option

**Comment by dpage** [comment]
Issue closed on Redmine.
