### ISSUE TITLE
segmentation fault (core dumped) when executing (RM #1841)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#709]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1841***
*Originally created by **Johannes Graën** at 2016-10-06 21:34:19 UTC.*

I followed the guide to build pgAdmin 4. qmake and make succeeded.

When executing the application I get the following message:

Python path:  "/usr/include/python3.5"
Python Home:  ""
Webapp path:  "/home/johannes/make/pgadmin4-1.0/web/pgAdmin4.py"
Traceback (most recent call last):
  File "/home/johannes/make/pgadmin4-1.0/web/pgAdmin4.py", line 24, in <module>
    from pgadmin import create_app
  File "/home/johannes/make/pgadmin4-1.0/web/pgadmin/__init__.py", line 17, in <module>
    from flask import Flask, abort, request, current_app
ImportError: No module named 'flask'

Flask is installed though:

Requirement already satisfied (use --upgrade to upgrade): flask in /usr/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/lib/python3.5/site-packages (from flask)
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in /usr/lib/python3.5/site-packages (from flask)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python3.5/site-packages (from flask)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/lib/python3.5/site-packages (from flask)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/lib/python3.5/site-packages (from Jinja2>=2.4->flask)

The application shows a window called "Configuration" asking me to enter python and application path. If I do that and confirm, it dies with

zsh: segmentation fault (core dumped)  ./pgAdmin4

**Comment by dpage** [comment]
Issue closed on Redmine.
