### ISSUE TITLE
[Web based] User can not do any setup for web based  (RM #1871)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#738]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1871***
*Originally created by **Fahar Abbas** at 2016-10-19 11:00:24 UTC.*

Commit ID:
----------
bc5cc964a3a67a0a5e367524c18e51266faf08f8

While testing of particular RM https://redmine.postgresql.org/issues/1849 User can not do any setup for web based 

Testing Environment
 
Ubuntu 16.04 Linux 64:
--------------------------------

pg-Admin4 Development Environment Setup for Ubuntu:

1) Install GIT

sudo apt-get install git

2) Install pip3

sudo apt-get install python3-pip

3) Install virtualenv

sudo pip3 install virtualenv

4) install below dependency as it is required for psycopg2 & pycrypto module

sudo apt-get install libpq-dev

sudo apt-get install python3-dev

5) Create virtual environment

virtualenv -p python3 venv

6) Create mkdir Projects

7) Clone git repo in Projects

git clone http://git.postgresql.org/git/pgadmin4.git

8) activate virtual environment

source venv/bin/activate

9) Install modules

pip3 install -r requirements_py3.txt

10) Edit the config.py file to config_local.py  resides in Projects\pgAdmin4\web  

11)Now run setup.py file  (\Projects\pgAdmin4\web)
    python setup.py

If user does not create config_local.py and do Python setup.py for new Development then SECURITY_PASSWORD_SALT message is also displayed:

Here is the output:
-------------------------

python setup.py
pgAdmin 4 - Application Initialisation
======================================

The configuration database - '/home/fahar/.pgadmin/pgadmin4.db' does not exist.
Entering initial setup mode...
NOTE: Configuring authentication for SERVER mode.

    Enter the email address and password to use for the initial pgAdmin user     account:

Email address: fahar.abbas@enterprisedb.com
Password:
Retype password:
Traceback (most recent call last):
  File "setup.py", line 449, in <module>
    do_setup(app)
  File "setup.py", line 96, in do_setup
    password = encrypt_password(p1)
  File "/home/fahar/venv/lib/python3.5/site-packages/flask_security/utils.py", line 150, in encrypt_password
    signed = get_hmac(password).decode('ascii')
  File "/home/fahar/venv/lib/python3.5/site-packages/flask_security/utils.py", line 108, in get_hmac
    'set to "%s"' % _security.password_hash)
RuntimeError: The configuration value `SECURITY_PASSWORD_SALT` must not be None when the value of `SECURITY_PASSWORD_HASH` is set to "pbkdf2_sha512"
(venv) fahar@fahar-virtual-machine:~/Projects/pgadmin4/web$

**Comment by dpage** [comment]
Issue closed on Redmine.
