### ISSUE TITLE
[Web Based] Exception displayed when Click on open file through query tool window (RM #1879)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#746]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1879***
*Originally created by **Fahar Abbas** at 2016-10-21 10:17:50 UTC.*

Python version 3.5

Tested Platform:
MAC 10.9
Ubuntu 16.04

Step:

1. Launch pgAdmin4
2. Connect to PG of EPAS-9.6 server
3. Click on Database deb or postgres
4. Click on Query tool window
5. Click on Open File
6. Exception displayed in terminal

Exception in thread Thread-263:
Traceback (most recent call last):
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 448, in list_filesystem
    cmp=custom_sort)]
TypeError: 'cmp' is an invalid keyword argument for this function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 820, in file_manager
    res = func(**kwargs)
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 562, in getfolder
    filelist = self.list_filesystem(dir, path, trans_data, file_type)
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 494, in list_filesystem
    if e.strerror == gettext('Permission denied'):
AttributeError: 'TypeError' object has no attribute 'strerror'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 448, in list_filesystem
    cmp=custom_sort)]
TypeError: 'cmp' is an invalid keyword argument for this function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/faharmav/myenv/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 823, in file_manager
    return getattr(myFilemanager, mode)(**kwargs)
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 562, in getfolder
    filelist = self.list_filesystem(dir, path, trans_data, file_type)
  File "/Users/faharmav/Projects/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 494, in list_filesystem
    if e.strerror == gettext('Permission denied'):
AttributeError: 'TypeError' object has no attribute 'strerror'

Actual result:
-----------
Exception displayed when Click on open file through query tool window

Expected Result:
--------------
No exception should be displayed if Click on open file through query tool window

Please note that this issue is not reproducible with Python 2.7.11(Tested on windows 2012 server 64).

I think, this priority should be higher and it's regression and Assigning as normal priority as Dave set priority of every RM.

**Comment by dpage** [comment]
Issue closed on Redmine.
