### ISSUE TITLE
Debugger enabled when pldbgapi extension not loaded (RM #2026)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#864]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2026***
*Originally created by **Dave Page** at 2016-12-19 09:20:41 UTC.*

I have a server on which the debugger plugin is configured, however I'm still able to attempt to launch the debugger within a database that doesn't have the extension loaded (the debugger works fine in another database which does have the extension installed):

2016-12-19 09:15:44,606: SQL	pgadmin:	Execute (scalar) for server #1 - CONN:9125378 (Query-id: 7211532):
SELECT proxyapiver FROM pldbg_get_proxy_info();
2016-12-19 09:15:44,607: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - CONN:9125378 (Query-id: 7211532):
Error Message:ERROR:  function pldbg_get_proxy_info() does not exist
LINE 1: SELECT proxyapiver FROM pldbg_get_proxy_info();
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

2016-12-19 09:15:44,614: INFO	werkzeug:	127.0.0.1 - - [19/Dec/2016 09:15:44] "GET /debugger/initialize_target/direct/1/283420/286904/289597 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dpage/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/dpage/git/pgadmin4/web/pgadmin/tools/debugger/__init__.py", line 410, in initialize_target
    current_app.logger.debug("Debugger version is: %d", debugger_version)
UnboundLocalError: local variable 'debugger_version' referenced before assignment

**Comment by dpage** [comment]
Issue closed on Redmine.
