### ISSUE TITLE
pgadmin: 'ascii' codec can't decode byte 0xc3 in position 66: ordinal not in range(128) (RM #2160)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#969]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2160***
*Originally created by **Lars Kumbier** at 2017-02-07 18:40:28 UTC.*

I am running pgadmin in version 1.1.

When trying to connect to a new server and setting wrong credentials (wrong username or wrong password), the server is unable to decode the translated text. The UI will show an error, the error log shows the following:

<pre>
[Tue Feb 07 17:44:29 2017] [error] 2017-02-07 17:44:29,670: ERROR\tpgadmin:\t'ascii' codec can't decode byte 0xc3 in position 66: ordinal not in range(128)
[Tue Feb 07 17:44:29 2017] [error] Traceback (most recent call last):
[Tue Feb 07 17:44:29 2017] [error]   File "xxx/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py", line 618, in create
[Tue Feb 07 17:44:29 2017] [error]     errormsg=gettext("Unable to connect to server:\\n\\n%s" % errmsg)
[Tue Feb 07 17:44:29 2017] [error]   File "xxx/pgadmin4/local/lib/python2.7/site-packages/flask_babel/__init__.py", line 542, in gettext
[Tue Feb 07 17:44:29 2017] [error]     s = t.ugettext(string)
[Tue Feb 07 17:44:29 2017] [error]   File "/usr/lib/python2.7/gettext.py", line 404, in ugettext
[Tue Feb 07 17:44:29 2017] [error]     return unicode(message)
[Tue Feb 07 17:44:29 2017] [error] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 66: ordinal not in range(128)
</pre>

This can be fixed by properly decoding the servername like so:
<pre>
// pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py:618
errormsg=gettext(u"Unable to connect to server:\n\n%s" % errmsg.decode('utf-8'))
</pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
